### ISSUE TITLE
VTK on Mac OS X 10.6:  /usr/lib/libIOKit.dylib: not a directory

### ISSUE THREAD

**Issue by jkmacc** [enthought/mayavi#10]
Hi, all.  This is more a problem in the documentation then the software.  Following the instructions on http://code.enthought.com/projects/mayavi/docs/development/html/mayavi/installation.html , I ran unto the following error during the "make -j" step:

cc1plus: error: /usr/lib/libIOKit.dylib: not a directory
make: *** [all] Error 2

I found a solution from: http://vtk.1045678.n5.nabble.com/VTK-5-6-compilation-on-Mac-OS-X-10-6-7-td4388683.html .  One has to change the IOKit:FILEPATH line to:
IOKit:FILEPATH=/System/Library/Frameworks/IOKit.framework

After this, it finishes compiling.

Thanks!

**Comment by stefanoborini** [comment]
Apparently fixed on the homebrew side, and the documentation page is no longer present anyway.
