### ISSUE TITLE
mportlib-resources is missing in requirements.txt

### ISSUE THREAD

**Issue by yurivict** [enthought/mayavi#1006]
Mayavi-4.7.2 requires ```py37-importlib-resources``` but ```requirements.txt``` doesn't mention it.

> ModuleNotFoundError: No module named 'importlib_resources'

**Comment by rahulporuri** [comment]
> Mayavi-4.7.2 requires py37-importlib-resources but requirements.txt doesn't mention it.

Mayavi directly does not require `importlib-resources`. Mayavi depends on `pyface`, which depends on `importlib-resources`. I'm not sure what version of `pyface` was installed because installing `pyface` should automatically install `importlib-resources`.

**Comment by yurivict** [comment]
It was indeed a case of a missing dependency. Thanks for your help!
