### ISSUE TITLE
mlab UI toolkit import error

### ISSUE THREAD

**Issue by IvanAvdeevGth** [enthought/mayavi#1010]
I use Python 3.8.5 on Ubuntu 20.04.2 LTS and have mayavi==4.7.2, PyQt5==5.15.2 and vtk==9.0.1 installed via pip. I wrote a little script mnwe.py (minimal not working example)
```
from mayavi import mlab
fig=mlab.figure()
```
When i try to execute it i get the following error:

> File "/path/to/example/mnwe.py", line 8, in <module>
    fig=mlab.figure()
  File "/home/user/.local/lib/python3.8/site-packages/mayavi/tools/figure.py", line 64, in figure
    engine = get_engine()
  File "/home/user/.local/lib/python3.8/site-packages/mayavi/tools/engine_manager.py", line 93, in get_engine
    return self.new_engine()
  File "/home/user/.local/lib/python3.8/site-packages/mayavi/tools/engine_manager.py", line 138, in new_engine
    check_backend()
  File "/home/user/.local/lib/python3.8/site-packages/mayavi/tools/engine_manager.py", line 41, in check_backend
    raise ImportError(msg)
ImportError: Could not import backend for traitsui.  Make sure you
        have a suitable UI toolkit like PyQt/PySide or wxPython
        installed.

I found that if i modify the script to
```
import PyQt5
from mayavi import mlab
fig=mlab.figure()
```
everything works just fine. I think this issue could be easily resolved so i leave it here.

**Comment by rahulporuri** [comment]
Thanks for opening the issue @IvanAvdeevGth !

Can you tell me if the environment variables `QT_API` or `ETS_TOOLKIT` are set? The error indicates a failure when detecting what toolkit (e.g. PyQt5) is installed in the Python environment.

>  I think this issue could be easily resolved so i leave it here.

Thanks for the report but i'm going to close this issue. Prior knowledge of `ETS_TOOLKIT`/`QT_API` or hacks like importing the toolkit package (e.g. `import PyQt5`) are necessary at the moment when using mayavi. At the moment, we don't have time to address such usability concerns - but we hope to in the near future (Q2 2021).

**Comment by IvanAvdeevGth** [comment]
UPD: now it is completely broken, can you suggest how to make mayavi work again? (almost the same setup, except PyQt5  update from 5.15.2 => 5.15.3)
