### ISSUE TITLE
Extracting numerical data

### ISSUE THREAD

**Issue by max3-2** [enthought/mayavi#1014]
I am looking for a way to extract numerical data from a module, e.g. creating a `ScalarCutPlane` and then outputting it to points, data, and if available, triangulation.

Is there a quick way to do this? I know I can build this in VTK but its quite annoying. Having the ability to see the slice and then pull out the data to a `np.array` would be a great help

**Comment by prabhuramachandran** [comment]
This is not an issue but the `mlab.pipeline.probe_data` should help.  See this: https://mayavi.readthedocs.io/en/latest/data.html?highlight=probe#probing-data-at-given-positions
