### ISSUE TITLE
Can´t finalize mayavi installation

### ISSUE THREAD

**Issue by alexsomoza** [enthought/mayavi#1054]
**Can't finalize install mayavi.
It keeps Building wheel for mayavi (setup.py):**

_>**pip install mayavi**
Collecting mayavi
  Using cached mayavi-4.7.3.tar.gz (7.1 MB)
Requirement already satisfied: apptools in c:\python\python37\lib\site-packages (from mayavi) (5.1.0)
Requirement already satisfied: envisage in c:\python\python37\lib\site-packages (from mayavi) (6.0.1)
Requirement already satisfied: numpy in c:\python\python37\lib\site-packages (from mayavi) (1.19.5)
Requirement already satisfied: pyface>=6.1.1 in c:\python\python37\lib\site-packages (from mayavi) (7.3.0)
Requirement already satisfied: pygments in c:\python\python37\lib\site-packages (from mayavi) (2.8.0)
Requirement already satisfied: traits>=6.0.0 in c:\python\python37\lib\site-packages (from mayavi) (6.2.0)
Requirement already satisfied: traitsui>=7.0.0 in c:\python\python37\lib\site-packages (from mayavi) (7.2.1)
Requirement already satisfied: vtk in c:\python\python37\lib\site-packages (from mayavi) (9.0.2)
Requirement already satisfied: importlib-resources>=1.1.0 in c:\python\python37\lib\site-packages (from pyface>=6.1.1->mayavi) (5.1.2)
Requirement already satisfied: importlib-metadata in c:\python\python37\lib\site-packages (from pyface>=6.1.1->mayavi) (3.7.3)
Requirement already satisfied: zipp>=0.4 in c:\python\python37\lib\site-packages (from importlib-resources>=1.1.0->pyface>=6.1.1->mayavi) (3.4.0)
Requirement already satisfied: configobj in c:\python\python37\lib\site-packages (from apptools->mayavi) (5.0.6)
Requirement already satisfied: six in c:\python\python37\lib\site-packages (from configobj->apptools->mayavi) (1.15.0)
Requirement already satisfied: setuptools in c:\python\python37\lib\site-packages (from envisage->mayavi) (47.1.0)
Requirement already satisfied: typing-extensions>=3.6.4 in c:\python\python37\lib\site-packages (from importlib-metadata->pyface>=6.1.1->mayavi) (3.7.4.3)
Requirement already satisfied: Twisted>=17.5.0 in c:\python\python37\lib\site-packages (from vtk->mayavi) (21.2.0)
Requirement already satisfied: matplotlib>=2.0.0 in c:\users\asomoza\appdata\roaming\python\python37\site-packages (from vtk->mayavi) (3.2.1)
Requirement already satisfied: autobahn>=17.7.1 in c:\python\python37\lib\site-packages (from vtk->mayavi) (21.3.1)
Requirement already satisfied: wslink>=0.1.3 in c:\python\python37\lib\site-packages (from vtk->mayavi) (0.2.0)
Requirement already satisfied: cryptography>=3.4.6 in c:\python\python37\lib\site-packages (from autobahn>=17.7.1->vtk->mayavi) (3.4.6)
Requirement already satisfied: txaio>=21.2.1 in c:\python\python37\lib\site-packages (from autobahn>=17.7.1->vtk->mayavi) (21.2.1)
Requirement already satisfied: hyperlink>=21.0.0 in c:\python\python37\lib\site-packages (from autobahn>=17.7.1->vtk->mayavi) (21.0.0)
Requirement already satisfied: cffi>=1.12 in c:\python\python37\lib\site-packages (from cryptography>=3.4.6->autobahn>=17.7.1->vtk->mayavi) (1.14.5)
Requirement already satisfied: pycparser in c:\python\python37\lib\site-packages (from cffi>=1.12->cryptography>=3.4.6->autobahn>=17.7.1->vtk->mayavi) (2.20)
Requirement already satisfied: idna>=2.5 in c:\python\python37\lib\site-packages (from hyperlink>=21.0.0->autobahn>=17.7.1->vtk->mayavi) (2.10)
Requirement already satisfied: python-dateutil>=2.1 in c:\python\python37\lib\site-packages (from matplotlib>=2.0.0->vtk->mayavi) (2.8.1)
Requirement already satisfied: cycler>=0.10 in c:\python\python37\lib\site-packages (from matplotlib>=2.0.0->vtk->mayavi) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\python\python37\lib\site-packages (from matplotlib>=2.0.0->vtk->mayavi) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\python\python37\lib\site-packages (from matplotlib>=2.0.0->vtk->mayavi) (1.3.1)
Requirement already satisfied: Automat>=0.8.0 in c:\python\python37\lib\site-packages (from Twisted>=17.5.0->vtk->mayavi) (20.2.0)
Requirement already satisfied: twisted-iocpsupport~=1.0.0 in c:\python\python37\lib\site-packages (from Twisted>=17.5.0->vtk->mayavi) (1.0.1)
Requirement already satisfied: constantly>=15.1 in c:\python\python37\lib\site-packages (from Twisted>=17.5.0->vtk->mayavi) (15.1.0)
Requirement already satisfied: incremental>=16.10.1 in c:\python\python37\lib\site-packages (from Twisted>=17.5.0->vtk->mayavi) (21.3.0)
Requirement already satisfied: attrs>=19.2.0 in c:\python\python37\lib\site-packages (from Twisted>=17.5.0->vtk->mayavi) (20.3.0)
Requirement already satisfied: zope.interface>=4.4.2 in c:\python\python37\lib\site-packages (from Twisted>=17.5.0->vtk->mayavi) (5.4.0)
**Building wheels for collected packages: mayavi
  Building wheel for mayavi (setup.py) ... |_**

**Comment by cifang-Kasit** [comment]
I face the same problem

**Comment by cifang-Kasit** [comment]
But I fixed it when I use 
pip install vtk==8.1.2
Then it works

**Comment by danmoser** [comment]
Same problem here...
And my Python3 pip does not find ``vtk==8.1.2``, or  ``"vtk<9"``.

**Comment by dtsiedel** [comment]
@danmoser I had that problem as well, most likely your python version is too new. If you check out the [available download files](https://pypi.org/project/vtk/8.1.2/#files) for `vtk==8.1.2`, you'll see there are only wheels for python3.7 and lower. In my case, I chose to install python3.7 alongside my existing python install, and was then able to complete the above steps using the older version.

**Comment by alexsomoza** [comment]
Thanks to all of you.
With vtk==8.1.2 the problem is finish and mayavi installed.
