### ISSUE TITLE
Mayavi example stalls with VTK 9.0.3

### ISSUE THREAD

**Issue by nchampag** [enthought/mayavi#1057]
The "multiple_mlab_scene_models.py" example from the Mayavi docs (see [here](https://docs.enthought.com/mayavi/mayavi/auto/example_multiple_mlab_scene_models.html)) stalls when using VTK 9.0.3, but works with VTK 9.0.1. The problem may be related to loading MlabSceneModel (based on debugging another project).

macOS 10.15.7
Python 3.8 3.8.11
Mayavi 4.7.3

**Comment by FedeMiorelli** [comment]
+1

Even just importing mayavi.mlab stalls indefinitely with VTK 9.0.3 when it works fine with 9.0.1
Win10, Python 3.9.4, Mayavi 4.7.3

**Comment by alaut** [comment]
same, tried:

```pip install mayavi``` but the setup hangs at ```Building wheel for mayavi (setup.py) ... \```

I'm not sure how to install vtk 9.0.1 to see if that might work though. Running Windows 10 python 3.9

**Comment by rahulporuri** [comment]
closing as the latest 4.7.4 mayavi release fixes this issue. please try reinstalling mayavi.
