### ISSUE TITLE
'from mayavi import mlab' goes into a dead cycle

### ISSUE THREAD

**Issue by alexwangxiang** [enthought/mayavi#1058]
My system is ubuntu 20.04, and I installed mayavi package inside a conda virtual environment with python 3.7.10. Each time when I run the sentence 'from mayavi import mlab', it goes into a dead cycle sometimes, and produces no error information. It stucks at the following screen:

> (openpcdet) alexwangxiang@alexwangxiang:~$ python
Python 3.7.10 (default, Jun  4 2021, 14:48:32) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from mayavi import mlab

I have to press Ctrl+z or Ctrl+\ to stop the session in terminal. But sometimes it works, mlab can be imported successfully, and I don't know the reason why.

**Comment by brankyy** [comment]
Same problem on ubuntu 18.04. I used pip to install mayavi and python version is 3.6.9.

There is no error information. And it works sometimes. I need to take my chance everytime hoping it works.

**Comment by alexwangxiang** [comment]
> Same problem on ubuntu 18.04. I used pip to install mayavi and python version is 3.6.9.
> There is no error information. And it works sometimes. I need to take my chance everytime hoping it works.

I followed the instruction given in issue #1057, uninstalled my previously installed vtk 9.0.3, and installed vtk 9.0.1. Everything works well since then, and I never failed to import mlab. Hope this comment will help you.
