### ISSUE TITLE
Why do "vtkDataEncoder", "vtkWebApplication" cause package build to hang with VTK 9.0.3?

### ISSUE THREAD

**Issue by rahulporuri** [enthought/mayavi#1087]
First reported in #1073 , the package build was hanging with the latest vtk - version 9.0.3. Thankfully, we are able to prevent the build from hanging by ignoring the following vtk classes - `vtkDataEncoder`, `vtkWebApplication` - but we need to understand why these classes are causing the build to hang.

**Comment by rahulporuri** [comment]
closing as the latest 4.7.4 mayavi release fixes this issue.

**Comment by thomasweng15** [comment]
I am on Ubuntu 18.04 and have vtk 9.0.3 installed through conda. I tried to pip install mayavi 4.7.4 but I am getting the error `NameError: name 'vtkDataEncoder' is not defined`. So it seems like mayavi 4.7.4 does not fix the issue.
