### ISSUE TITLE
Unable to install mayavi.

### ISSUE THREAD

**Issue by Atulsingh92** [enthought/mayavi#1090]
I know this issue has been closed before, but wasn't getting any response on the closed issue, hence creating a new one. Hopefully this will be an accepted question. 

The problem is pretty much what the subjecline says. 
Python 3.8.5, for windows 10. Instruction followed were as per the closed ticket response to pip install a few required libraries, and then pip install mayavi. 

the following is the errror,
`running install
running bdist_egg
running egg_info
running build_src
build_src
building extension "tvtk.array_ext" sources
building data_files sources
build_src: building npy-pkg config files
writing mayavi.egg-info\PKG-INFO
writing dependency_links to mayavi.egg-info\dependency_links.txt
writing entry points to mayavi.egg-info\entry_points.txt
writing requirements to mayavi.egg-info\requires.txt
writing top-level names to mayavi.egg-info\top_level.txt
reading manifest file 'mayavi.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'docs\build'
writing manifest file 'mayavi.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
customize MSVCCompiler
customize MSVCCompiler using build_ext
CCompilerOpt.cc_test_flags[999] : testing flags (/O2)
creating C:\Users\aus1n19\AppData\Local\Temp\tmpky84nmz9\Users
creating C:\Users\aus1n19\AppData\Local\Temp\tmpky84nmz9\Users\aus1n19
creating C:\Users\aus1n19\AppData\Local\Temp\tmpky84nmz9\Users\aus1n19\Anaconda3
creating C:\Users\aus1n19\AppData\Local\Temp\tmpky84nmz9\Users\aus1n19\Anaconda3\Lib
creating C:\Users\aus1n19\AppData\Local\Temp\tmpky84nmz9\Users\aus1n19\Anaconda3\Lib\site-packages
creating C:\Users\aus1n19\AppData\Local\Temp\tmpky84nmz9\Users\aus1n19\Anaconda3\Lib\site-packages\numpy
creating C:\Users\aus1n19\AppData\Local\Temp\tmpky84nmz9\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils
creating C:\Users\aus1n19\AppData\Local\Temp\tmpky84nmz9\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils\checks
CCompilerOpt.cc_test_flags[999] : testing flags (/WX)
CCompilerOpt.init[1145] : feature 'AVX512_KNL' is disabled, MSVC compiler doesn't support it
CCompilerOpt.init[1145] : feature 'AVX512_KNM' is disabled, MSVC compiler doesn't support it
CCompilerOpt.init[1674] : check requested baseline
CCompilerOpt.cc_test_flags[999] : testing flags (/arch:SSE)
CCompilerOpt.dist_test[576] : CCompilerOpt._dist_test_spawn[699] : Flags in command (C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\aus1n19\Anaconda3\include -IC:\Users\aus1n19\Anaconda3\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.16.27023\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /TcC:\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils\checks\test_flags.c /FoC:\Users\aus1n19\AppData\Local\Temp\tmpky84nmz9\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils\checks\test_flags.obj /arch:SSE) aren't supported by the compiler, output ->
cl : Command line warning D9002 : ignoring unknown option '/arch:SSE'
test_flags.c

CCompilerOpt.cc_test_flags[1003] : testing failed
CCompilerOpt.cc_test_flags[999] : testing flags (/arch:SSE2)
CCompilerOpt.dist_test[576] : CCompilerOpt._dist_test_spawn[699] : Flags in command (C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\aus1n19\Anaconda3\include -IC:\Users\aus1n19\Anaconda3\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.16.27023\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /TcC:\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils\checks\test_flags.c /FoC:\Users\aus1n19\AppData\Local\Temp\tmpky84nmz9\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils\checks\test_flags.obj /arch:SSE2) aren't supported by the compiler, output ->
cl : Command line warning D9002 : ignoring unknown option '/arch:SSE2'
test_flags.c

CCompilerOpt.cc_test_flags[1003] : testing failed
CCompilerOpt.feature_test[1444] : testing feature 'SSE' with flags ()
CCompilerOpt.feature_test[1444] : testing feature 'SSE2' with flags ()
CCompilerOpt.feature_test[1444] : testing feature 'SSE3' with flags ()
CCompilerOpt.init[1683] : check requested dispatch-able features
CCompilerOpt.feature_test[1444] : testing feature 'SSSE3' with flags ()
CCompilerOpt.cc_test_flags[999] : testing flags (/arch:AVX)
CCompilerOpt.feature_test[1444] : testing feature 'AVX' with flags (/arch:AVX)
CCompilerOpt.feature_test[1444] : testing feature 'F16C' with flags (/arch:AVX)
CCompilerOpt.cc_test_flags[999] : testing flags (/arch:AVX2)
CCompilerOpt.feature_test[1444] : testing feature 'FMA3' with flags (/arch:AVX2)
CCompilerOpt.feature_test[1444] : testing feature 'SSE41' with flags ()
CCompilerOpt.feature_test[1444] : testing feature 'POPCNT' with flags ()
CCompilerOpt.feature_test[1444] : testing feature 'SSE42' with flags ()
CCompilerOpt.feature_test[1444] : testing feature 'AVX2' with flags (/arch:AVX2)
CCompilerOpt.cc_test_flags[999] : testing flags (/arch:AVX512)
CCompilerOpt.feature_test[1444] : testing feature 'AVX512_SKX' with flags (/arch:AVX512)
CCompilerOpt.feature_test[1444] : testing feature 'AVX512CD' with flags (/arch:AVX512)
CCompilerOpt.feature_test[1444] : testing feature 'AVX512F' with flags (/arch:AVX512)
CCompilerOpt.feature_test[1444] : testing feature 'AVX512_CLX' with flags (/arch:AVX512)
CCompilerOpt.feature_test[1444] : testing feature 'AVX512_CNL' with flags (/arch:AVX512)
CCompilerOpt.feature_test[1444] : testing feature 'AVX512_ICL' with flags (/arch:AVX512)
CCompilerOpt.dist_test[576] : CCompilerOpt._dist_test_spawn[711] : Command (C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\aus1n19\Anaconda3\include -IC:\Users\aus1n19\Anaconda3\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.16.27023\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /TcC:\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils\checks\cpu_avx512_icl.c /FoC:\Users\aus1n19\AppData\Local\Temp\tmpky84nmz9\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils\checks\cpu_avx512_icl.obj /arch:AVX512 /WX) failed with exit status 2 output ->
cpu_avx512_icl.c
C:\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils\checks\cpu_avx512_icl.c(6): error C2220: warning treated as error - no 'object' file generated
C:\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils\checks\cpu_avx512_icl.c(6): warning C4013: '_mm512_shrdv_epi64' undefined; assuming extern returning int
C:\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils\checks\cpu_avx512_icl.c(8): warning C4013: '_mm512_popcnt_epi8' undefined; assuming extern returning int
C:\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils\checks\cpu_avx512_icl.c(8): error C2440: '=': cannot convert from 'int' to '__m512i'
C:\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils\checks\cpu_avx512_icl.c(10): warning C4013: '_mm512_popcnt_epi64' undefined; assuming extern returning int
C:\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils\checks\cpu_avx512_icl.c(10): error C2440: '=': cannot convert from 'int' to '__m512i'
C:\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils\checks\cpu_avx512_icl.c(6): error C2440: 'initializing': cannot convert from 'int' to '__m512i'

CCompilerOpt.feature_test[1458] : testing failed
CCompilerOpt.init[1695] : skip features (SSE2 SSE SSE3) since its part of baseline
CCompilerOpt.init[1699] : initialize targets groups
CCompilerOpt.init[1701] : parse target group simd_test
CCompilerOpt._parse_target_tokens[1910] : skip targets (FMA4 XOP VSX VSX3 VSX2 ASIMD NEON) not part of baseline or dispatch-able features
CCompilerOpt._parse_policy_not_keepbase[2022] : skip baseline features (SSE2)
CCompilerOpt.generate_dispatch_header[2236] : generate CPU dispatch header: (build\src.win-amd64-3.8\numpy\distutils\include\npy_cpu_dispatch_config.h)
CCompilerOpt.feature_extra_checks[1519] : Testing extra checks for feature 'AVX512F' (AVX512F_REDUCE)
CCompilerOpt.dist_test[576] : CCompilerOpt._dist_test_spawn[711] : Command (C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\aus1n19\Anaconda3\include -IC:\Users\aus1n19\Anaconda3\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.16.27023\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /TcC:\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils\checks\extra_avx512f_reduce.c /FoC:\Users\aus1n19\AppData\Local\Temp\tmpky84nmz9\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils\checks\extra_avx512f_reduce.obj /arch:AVX512 /WX) failed with exit status 2 output ->
extra_avx512f_reduce.c
C:\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils\checks\extra_avx512f_reduce.c(11): error C2220: warning treated as error - no 'object' file generated
C:\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils\checks\extra_avx512f_reduce.c(11): warning C4244: 'function': conversion from 'double' to '__int64', possible loss of data

CCompilerOpt.feature_extra_checks[1537] : testing failed for checks (AVX512F_REDUCE)
CCompilerOpt.feature_extra_checks[1519] : Testing extra checks for feature 'AVX512_SKX' (AVX512BW_MASK AVX512DQ_MASK)
CCompilerOpt.dist_test[576] : CCompilerOpt._dist_test_spawn[711] : Command (C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\aus1n19\Anaconda3\include -IC:\Users\aus1n19\Anaconda3\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.16.27023\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /TcC:\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils\checks\extra_avx512bw_mask.c /FoC:\Users\aus1n19\AppData\Local\Temp\tmpky84nmz9\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils\checks\extra_avx512bw_mask.obj /arch:AVX512 /WX) failed with exit status 2 output ->
extra_avx512bw_mask.c
C:\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils\checks\extra_avx512bw_mask.c(12): error C2220: warning treated as error - no 'object' file generated
C:\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils\checks\extra_avx512bw_mask.c(12): warning C4013: '_kor_mask64' undefined; assuming extern returning int
C:\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils\checks\extra_avx512bw_mask.c(13): warning C4013: '_kxor_mask64' undefined; assuming extern returning int
C:\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils\checks\extra_avx512bw_mask.c(14): warning C4013: '_cvtu64_mask64' undefined; assuming extern returning int
C:\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils\checks\extra_avx512bw_mask.c(14): warning C4013: '_cvtmask64_u64' undefined; assuming extern returning int

CCompilerOpt.dist_test[576] : CCompilerOpt._dist_test_spawn[711] : Command (C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\aus1n19\Anaconda3\include -IC:\Users\aus1n19\Anaconda3\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.16.27023\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /TcC:\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils\checks\extra_avx512dq_mask.c /FoC:\Users\aus1n19\AppData\Local\Temp\tmpky84nmz9\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils\checks\extra_avx512dq_mask.obj /arch:AVX512 /WX) failed with exit status 2 output ->
extra_avx512dq_mask.c
C:\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils\checks\extra_avx512dq_mask.c(12): error C2220: warning treated as error - no 'object' file generated
C:\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils\checks\extra_avx512dq_mask.c(12): warning C4013: '_kor_mask8' undefined; assuming extern returning int
C:\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils\checks\extra_avx512dq_mask.c(13): warning C4013: '_kxor_mask8' undefined; assuming extern returning int
C:\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils\checks\extra_avx512dq_mask.c(14): warning C4013: '_cvtu32_mask8' undefined; assuming extern returning int
C:\Users\aus1n19\Anaconda3\Lib\site-packages\numpy\distutils\checks\extra_avx512dq_mask.c(14): warning C4013: '_cvtmask8_u32' undefined; assuming extern returning int
CCompilerOpt.feature_extra_checks[1537] : testing failed for checks (AVX512BW_MASK AVX512DQ_MASK)
Detected changes on compiler optimizations, force rebuilding
building 'tvtk.array_ext' extension
compiling C sources
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\aus1n19\Anaconda3\lib\site-packages\numpy\core\include -Ibuild\src.win-amd64-3.8\numpy\distutils\include -IC:\Users\aus1n19\Anaconda3\include -IC:\Users\aus1n19\Anaconda3\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.16.27023\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /Tctvtk\src\array_ext.c /Fobuild\temp.win-amd64-3.8\Release\tvtk\src\array_ext.obj
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\aus1n19\Anaconda3\libs /LIBPATH:C:\Users\aus1n19\Anaconda3\PCbuild\amd64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.16.27023\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64 /EXPORT:PyInit_array_ext build\temp.win-amd64-3.8\Release\tvtk\src\array_ext.obj /OUT:build\lib.win-amd64-3.8\tvtk\array_ext.cp38-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.8\Release\tvtk\src\array_ext.cp38-win_amd64.lib
copying build\lib.win-amd64-3.8\tvtk\array_ext.cp38-win_amd64.pyd -> build\bdist.win-amd64\egg\tvtk
creating stub loader for tvtk\array_ext.cp38-win_amd64.pyd
byte-compiling build\bdist.win-amd64\egg\tvtk\array_ext.py to array_ext.cpython-38.pyc
installing package data to build\bdist.win-amd64\egg
running install_data

Building TVTK classes... vtkContextDevice2D: Ignoring method: Get/SetViewportRect
default: [1128415552, 1195787588, 1263159624, 1330531660], range: None
vtkContextDevice2D: Ignoring method: Get/SetViewportSize
default: [993671480, 1061043516], range: None`

**Comment by rahulporuri** [comment]
@Atulsingh92 this is a known issue. Please see #1073 . I'm going to close this issue as a duplicate. The temporary solution is to either fix vtk to 9.0.1 or to install from either #1088  or #1050
