### ISSUE TITLE
requirements.txt not found in bleeding edge installation

### ISSUE THREAD

**Issue by fbarfi** [enthought/mayavi#1147]

**Comment by rahulporuri** [comment]
Hey @fbarfi . Can I ask why you're looking for the `requirements.txt` file? The information contained within the `requirements.txt` file has been updated and moved into the `mayavi` package, specifically in `mayavi.__init__`.

**Comment by fbarfi** [comment]
Hello @rahulporuri  I tried to install from the source and then run into the error message that the requirements.txt is missing (which indeed as you say is the case). The reason I was trying to do a source installation is because initially the pip installation did not work on Apple M1. However, I  have resolved the issue now (I was missing some of the dependencies). thank you for responding. Everything is working well now.

**Comment by rahulporuri** [comment]
>  Everything is working well now.

In that case, im going to close this issue

> then run into the error message that the requirements.txt is missing

It's still not a 100% clear to me why you were running into the issue but thankfully, it sounds like you no longer have the issue.

**Comment by JAGulin** [comment]
@rahulporuri Hi. I was going to write a similar issue, so I can tell you that requirements.txt is part of the install instructions for "bleeding edge".

pip install -r requirements.txt
http://docs.enthought.com/mayavi/mayavi/installation.html#bleeding-edge

That instruction seems to remain in latest version.
https://github.com/enthought/mayavi/blob/master/docs/source/mayavi/installation.rst#L97
although the test cases seem to rely on other setup.
https://github.com/enthought/mayavi/blob/master/.github/workflows/run-mayavi-tests.yml#L52

If the change is not trivial to you, please open issue for tracking until docs are updated.

PS. My simplistic workaround was to restore (git checkout) the deleted file. As such, also my immediate problem is gone.
