### ISSUE TITLE
Close GUI and Savefig

### ISSUE THREAD

**Issue by jwma0725** [enthought/mayavi#1171]
Hi @prabhuramachandran, I do not want to open GUI window, How can I set?
I have 40000 pictures to save. If I open the window everytime, the efficiency is not high.
The following is the code:
`mlab.view()
mlab.savefig()
mlab.clf()
mlab.close()`

**Comment by prabhuramachandran** [comment]
Try with the tricks here: https://mayavi.readthedocs.io/en/latest/tips.html#avoiding-the-rendering-window
Basically turn on offscreen before you do anything.
