### ISSUE TITLE
BUG: Not 3.11 compatible

### ISSUE THREAD

**Issue by larsoner** [enthought/mayavi#1188]
See https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=598511&view=logs&jobId=9a864fd9-6c8f-52ca-79ce-2aa6dca1a1de&j=9a864fd9-6c8f-52ca-79ce-2aa6dca1a1de&t=10fc5aa2-324e-5982-4c88-6b31fcab16b3 :
```
  tvtk/src/array_ext.c:2313:15: error: too few arguments to function 'PyCode_New'
   2313 |     py_code = PyCode_New(
        |               ^~~~~~~~~~
  In file included from /home/conda/feedstock_root/build_artifacts/mayavi_1666971869466/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include/python3.11/Python.h:71,
                   from tvtk/src/array_ext.c:4:
  /home/conda/feedstock_root/build_artifacts/mayavi_1666971869466/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include/python3.11/cpython/code.h:148:28: note: declared here
    148 | PyAPI_FUNC(PyCodeObject *) PyCode_New(
        |                            ^~~~~~~~~~
  tvtk/src/array_ext.c:2340:13: error: invalid use of incomplete typedef 'PyFrameObject' {aka 'struct _frame'}
   2340 |     py_frame->f_lineno = __pyx_lineno;
```

**Comment by lgramer** [comment]
We have attempted to install mayavi using conda in a python 3.11 environment by following the instructions here: https://docs.enthought.com/mayavi/mayavi/installation.html

We see the following error. This Open PR suggests that python 3.11 is still being worked on at the moment? Any ETA?

`
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - mayavi -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']

Your python: python=3.11
`
