### ISSUE TITLE
How to make the arrow color change with their directions?

### ISSUE THREAD

**Issue by shz224** [enthought/mayavi#1220]
Thanks for the wonderful package. I'm using quiver3d to plot a vector field with (x, y, z, u, v, w). I wonder how to make the arrow color change with their directions instead of length.

**Comment by srk** [comment]
Perhaps precompute a list of scalars, one for each vector, where the scalar is the dot product of the (normalized) vectors and some reference vector, e.g. (0, 0, 1). That will get you a number in the range (-1,1). Use these numbers as a lookup table into a scale of colors .

**Comment by shz224** [comment]
OK, thanks.

**Comment by prabhuramachandran** [comment]
I assume this is solved so am closing.
