### ISSUE TITLE
Open file dialog ignores files without extensions

### ISSUE THREAD

**Issue by jclevesque** [enthought/mayavi#125]
I assume the pattern is `*.*`, hence this will not match files without an extension (e.g., `lab1_data`) and indeed they are not present in the list of files. Any particular reason to this? Why not just use `*`?

**Comment by dmsurti** [comment]
AFAICT, VTK and Mayavi support file formats which have an extension (.obj for ob, .vtk for VTK etc). Is there a VTK reader that exists which supports file format(s) without extension? 

As for Mayavi, even if we allowed opening a file without extension, you would have to tell which reader to use, which is a sensible default. 

http://www.vtk.org/Wiki/VTK/FAQ#What_3D_file_formats_can_VTK_import_and_export.3F
https://github.com/enthought/mayavi/blob/master/mayavi/action/sources.py#L41

**Comment by stefanoborini** [comment]
I am unsure if it's a worthwhile feature. To cover this specific use case, we need to provide a custom file dialog with a combobox allowing to specifying the format. The File Dialog is abstracted by both Qt and Wx, and in general is not implemented by the toolkits, but it just creates the native interface file dialog.

Is the gain offsetting the cost? In my opinion, no. @prabhuramachandran maybe has a different opinion?
Closing, but feel free to reopen if considered relevant.
