### ISSUE TITLE
Mesh control for volumetric data

### ISSUE THREAD

**Issue by sumantkrsoni** [enthought/mayavi#1256]
Hello,
I have volumetric CSV data as: (x, y, z, u1, u2, u3, T) for an inverted T-shaped enclosure., and the 3D surface plot is not true as per the data.

Also, it use to mesh in all available domain, ( Cube type).

Can anyone suggest to control the meshing areas and plot for a complex domain using CSV data.

I am attaching my data here:
[data.csv](https://github.com/enthought/mayavi/files/11590970/data.csv)

**Comment by prabhuramachandran** [comment]
The default delaunay3d will only mesh the convex hull. Boundary conforming meshing is a lot more tricky -- you will need to use some other tool for that. Usually you will need to use some sort of meshing tool along with a clearly defined surface which is the boundary of your mesh.  In any case this is not a Mayavi issue so I will close this issue. I am not sure I can recommend a tool for you.
