### ISSUE TITLE
mayavi2.py complains about missing obsolet libs

### ISSUE THREAD

**Issue by grenoya** [enthought/mayavi#130]
When trying to launch mayavi2, it complains about missing some envisage stuff and proposed me to install 'EnvisageCore' and 'EnvisagePlugins' (see below) which are obsoletes.
The message should ask to install 'envisage'.

BTW, I can see 2 possible improvements:
1) put envisage as a require so pip deals with it directly
2) change text so it talks about pip and no more about easy_install

***********************************************
$ bin/mayavi2 
Traceback (most recent call last):
  File "bin/mayavi2", line 9, in <module>
    load_entry_point('mayavi==4.3.1', 'gui_scripts', 'mayavi2')()
  File "my_virtualenv/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "my_virtualenv/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "my_virtualenv/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "my_virtualenv/lib/python2.7/site-packages/mayavi/scripts/mayavi2.py", line 493, in <module>
    raise ImportError(msg)
ImportError: No module named envisage.ui.workbench.api
________________________________________________________________________________
Could not load envisage. You might have a missing dependency.
Do you have the EnvisageCore and EnvisagePlugins installed?

If you installed Mayavi with easy_install, try 'easy_install <pkg_name>'.
'easy_install Mayavi[app]' will also work.

If you performed a source checkout and installed via 'python setup.py develop',
be sure to run the same command in the EnvisageCore and EnvisagePlugins folders.

If these packages appear to be installed, check that your numpy and
configobj are installed and working. If you need numpy, 'easy_install numpy'
will install numpy. Similarly, 'easy_install configobj' will install
configobj.

**Comment by robmarkcole** [comment]
Hi is there a way to get past this error? Thanks

**Comment by dmsurti** [comment]
http://docs.enthought.com/mayavi/mayavi/installation.html
It is preferable to use a ready made distribution `Canopy` to use Mayavi.

What is your OS? Did you do a manual install?

**Comment by robmarkcole** [comment]
Hi there, I am using anaconda, now I have installed apptools using 'conda install apptools' I no longer get the error and Mayavi is working fine.
Thanks

**Comment by robmarkcole** [comment]
XP btw

**Comment by robmarkcole** [comment]
win7 btw
