### ISSUE TITLE
Continuous integration is broken

### ISSUE THREAD

**Issue by pberkes** [enthought/mayavi#140]
One test (`tests.test_tvtk.test_object_cache`) relies on a VTK fix that is available on our eggs, but not in the package used by Travis CI: http://review.source.kitware.com/#/c/15095/ .

**Comment by dmsurti** [comment]
This is a flaky test and may happen again but has been handled here https://github.com/enthought/mayavi/commit/da306a12d6553a8e5e2982c4ef6394252e77c385. 

Closed.
