### ISSUE TITLE
On large hi-res screen on Mac, LUT color picker mis-identifies palette selection

### ISSUE THREAD

**Issue by jdmarch** [enthought/mayavi#147]
User report. On MacPro with two AMD FirePro D500 graphics cards and two Thunderbolt displays with 2560 x 1440 resolution. Scalar LUT manager chosen, 256 colors, 60 palettes shown (plus one "binary file"). In most cases when a palette is clicked, a different palette (usually but not always to the right of the one clicked) is actually chosen and used. Video available.

**Comment by dmsurti** [comment]
> Video available.

@jdmarch Can you share the video link?

**Comment by jdmarch** [comment]
@dmsurti emailed to you.
