### ISSUE TITLE
move() works only if foreward= is given. Else: xhat referenced before assignment

### ISSUE THREAD

**Issue by IlIll** [enthought/mayavi#153]
in camera.move(): xhat is only set if move is called with 'forward= ...'
if it is only called with 'right = ...' there will be an error message:
"UnboundLocalError: local variable 'xhat' referenced before assignment"

which is actually quite understandable if one takes a look at the souce code:
https://github.com/enthought/mayavi/blob/master/mayavi/tools/camera.py from line 430 onwards

**Comment by trallero** [comment]
The move command works fine in Mayavi 4.4.0-4

**Comment by stefanoborini** [comment]
Fixed in https://github.com/enthought/mayavi/pull/306
