### ISSUE TITLE
GIFs and Video animations with Mayavi - a blog post with examples

### ISSUE THREAD

**Issue by Zulko** [enthought/mayavi#154]
Hi there ! It's not really an issue, just to say that I wrote a [blog post](http://zulko.github.io/blog/2014/11/29/data-animations-with-python-and-moviepy/) that could interest you, I show how to "plug" MoviePy to make GIFs/video animations with Mayavi. Cheers !

**Comment by dmsurti** [comment]
Sorry for the late response. Nevertheless, great work. Thanks for sharing.

PS: closing this as it is not an issue :+1:
