### ISSUE TITLE
Installation Documentation are dead

### ISSUE THREAD

**Issue by jycr753** [enthought/mayavi#155]
The links in how to install and build return 404 error

**Comment by noobermin** [comment]
Unfortunately, the devs are rather terrible about replying to these things.

From watching development of this project, it looks like they are getting ready to ship version 4.4.0 For example, see http://docs.enthought.com/mayavi/mayavi/ that it has been changed to version 4.4.0.

So, my advice is to sit tight and wait for them to officially release 4.4.0

**Comment by stefanoborini** [comment]
No longer relevant. Closing
