### ISSUE TITLE
Problem with upgrading to 4.4.0 on PyPI

### ISSUE THREAD

**Issue by fnielsen** [enthought/mayavi#168]
Upgrading to 4.4.0 with pip and PyPI does not work out of the box with ` $ sudo -H pip2 install --upgrade mayavi` fails.

On https://pypi.python.org/simple/mayavi/ the link is https://github.com/enthought/mayavi/archive/4.4.0.tar.gz. Possibly pip requires the 'mayavi-' prefix. pip reports " wrong project name":

    Skipping link https://github.com/enthought/mayavi/archive/4.4.0.tar.gz (from https://pypi.python.org/simple/mayavi/); wrong project name (not mayavi)

`$ sudo -H pip2 install -U https://github.com/enthought/mayavi/archive/4.4.0.tar.gz` works ok. See http://stackoverflow.com/questions/29564825/upgrade-to-newest-mayavi-4-4-0-with-pip-does-not-upgrade

**Comment by stefanoborini** [comment]
This seems to be fixed. The links now point to the correct filename. Closing.

**Comment by fnielsen** [comment]
Yes, I can confirm that the problem seems to be fixed. I experienced no problem with upgrading to 4.4.4.

**Comment by stefanoborini** [comment]
Thank you. Closing
