### ISSUE TITLE
Fix sdist

### ISSUE THREAD

**Issue by dmsurti** [enthought/mayavi#177]
Currently sdist does not generate the correct archive for distribution. The important missing parts are:
1. `examples`
2. `integrationtests`
3. `docs`

Also need to ensure PKG-INFO is correct for upload to PyPi.

**Comment by itziakos** [comment]
@dmsurti, Do you have more info on this issue?

**Comment by dmsurti** [comment]
@prabhuramachandran Can you check that the `sdist` requirements listed above are correct?
