### ISSUE TITLE
CellArray.number_of_cells is not updated

### ISSUE THREAD

**Issue by itziakos** [enthought/mayavi#178]
The issue is demonstrated below.

```python
In [37]: from tvtk.api import tvtk
In [38]: cell_array = tvtk.CellArray()
In [39]: line = tvtk.Line()
In [40]: cell_array.insert_next_cell(line)
Out[40]: 0L
In [41]: a = tvtk.to_vtk(cell_array)
In [42]: a.GetNumberOfCells()
Out[42]: 1L
In [43]: cell_array.number_of_cells
Out[43]: 0L

```

**Comment by dmsurti** [comment]
```python

>>> from tvtk.api import tvtk
>>> cell_array = tvtk.CellArray()
>>> line = tvtk.Line()
>>> cell_array.insert_next_cell(line)
0L
>>> cell_array.update_traits()
>>> cell_array.number_of_cells
1L
>>> a = tvtk.to_vtk(cell_array)
>>> a.GetNumberOfCells()
1L

```

A quick workaround only fix is to call cell_array.update_traits. The traits wrapper classes are auto-generated. The `number_of_cells` trait is updatable and `vtk_obj.NumberOfCells` are not synced after calling the InsertNextCell method. I need to look further to figure if I need to add an observer or add a special clause in TVTK generator to fix this.

https://github.com/enthought/mayavi/blob/master/tvtk/wrapper_gen.py
