### ISSUE TITLE
Add GLSL Shader Example

### ISSUE THREAD

**Issue by dmsurti** [enthought/mayavi#180]
Add shader example under Mayavi examples to demo GLSL capability.

**Comment by itziakos** [comment]
This sounds very cool!

**Comment by dmsurti** [comment]
This has to wait till VTK 6.2 with OpenGL2 adds shader support. Right now the only way to do it is to enable this backend and extend vtkOpenGLPolyDataMapper with your own custom shaders. possible only on C++.

As for < VTK 6.2, this had vtkShader2/vtkShaderProgram2 classes to add shaders, but that is only GLSL as an extension as < VTK 6.2 uses OpenGL 1.1 backend. Further these shader related classes are not accessible from python.
