### ISSUE TITLE
Update out-of-date documentation

### ISSUE THREAD

**Issue by dmsurti** [enthought/mayavi#186]
The documentation needs a review and edits to bring it up to date.

A list of items that are out-of-data are presented bellow:
- http://docs.enthought.com/mayavi/mayavi/misc.html#development-quick-start, talks about `svn` should discuss development using `git`.
- http://docs.enthought.com/mayavi/mayavi/misc.html#improving-the-documentation, instructions for updating the documentation need to be updated with a github PR workflow.

**Comment by itziakos** [comment]
I have added a list of items/sections that need to be updated in the issue description, please fill out as necessary.

**Comment by itziakos** [comment]
initial work done in #229
