### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by dmsurti** [enthought/mayavi#188]
We have discovered a number of memory leaks which we need to investigate and fix memory leaks

**Comment by itziakos** [comment]
Can you provide more info on the memory leaks or examples on when they happen?

**Comment by dmsurti** [comment]
Refer to #210 for more details on the automated testing for memory leaks.

**Comment by itziakos** [comment]
I think we can close this issue (it is too generic anyway). The basic reference cycles in a scene that could cause issues have been identified and fixed. We can add more specific issues later

**Comment by dmsurti** [comment]
Yes, I agree. References: #218. Closed.
