### ISSUE TITLE
Fix the shebang of scripts  

### ISSUE THREAD

**Issue by itziakos** [enthought/mayavi#189]
We should use ` /usr/bin/python`  instead of  `/use/bin/env python`.

Note:
- As far as I understand this is not expected to cause problems.

**Comment by mdickinson** [comment]
Why is this considered a bug?  What basis do you have for assuming that the system Python can be found at `/usr/bin/python` (rather than `/bin/python`, or `/usr/local/bin/python`, or ...)?

**Comment by rkern** [comment]
`distutils` changes the shebang line anyways upon installation in any case. Leave them be.

**Comment by itziakos** [comment]
It was reported here that it is a problem for debian https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=785627.

**Comment by rkern** [comment]
That's an issue with Debian's packaging, then. We use `gui_scripts` to install the `mayavi2` script.

**Comment by itziakos** [comment]
Thanks @rkern, I was confused a little. Closing the issue
