### ISSUE TITLE
Fix PyPi upload

### ISSUE THREAD

**Issue by dmsurti** [enthought/mayavi#195]
The PyPi upload does not work as there is no `PKG-INFO`.

**Comment by dmsurti** [comment]
Tested the sdist with upload to testpypi and the upload went fine.

https://testpypi.python.org/pypi/mayavi-dmsurti/4.4.3.dev0.

PS: For test purpose, I changed the package name as testpyi already has a mayavi package under your ownership.

Also, see PR https://github.com/enthought/mayavi/pull/198

**Comment by itziakos** [comment]
For consistency lets close the issue as soon as #198 is merged

**Comment by dmsurti** [comment]
#198 merged. Closing this.
