### ISSUE TITLE
VTKFileReader source output not set properly

### ISSUE THREAD

**Issue by itziakos** [enthought/mayavi#213]
It looks that the VTKFileReader outputs attribute is not set to the right value. Here is an example using mayavi 4.4.2 and vtk 6.2.0 and the vtk.vtk file from the VTKData repo (http://www.vtk.org/Wiki/VTK_Datasets)

```python
from mayavi.sources.vtk_file_reader import VTKFileReader

source = VTKFileReader()
source.initialize('vtk.vtk')

print source.outputs[0]  # this dataset does not contain the 12 points and 5 lines stored in vtk.vtk.
print source.reader.output
```

Please note that when loading the file in mayavi2 and adding modules for visualization the pipeline gets the right info.

**Comment by dmsurti** [comment]
This has been fixed in #217.
