### ISSUE TITLE
(VTK 5.8 only) VTKFileReader unable to open vtk file with unstructured grid

### ISSUE THREAD

**Issue by dmsurti** [enthought/mayavi#219]
Refer to #213 which is fixed in #217. 

The test `test_vtk_file_reader.test_unstructured_grid_file` fails on Travis which uses VTK 5.8. The sample file UGridVTK.ext has been added, but it fails with:
`vtkDataSetReader (0x12aa7b20): Unable to open file: /home/travis/build/enthought/mayavi/mayavi/tests/data/UGridEx.vtk`

**Comment by stefanoborini** [comment]
Are we still supporting VTK 5? If it's being phased out, maybe we should close this one.

**Comment by kitchoi** [comment]
The filename is actually `/home/travis/build/enthought/mayavi/mayavi/tests/data/uGridEx.vtk`  (note the lower case `u`).  I bet the test would have passed with vtk 5.8 if the filename is corrected.  See https://github.com/enthought/mayavi/pull/353

**Comment by stefanoborini** [comment]
@kitchoi ok, then it's no longer relevant. Closing.

**Comment by kitchoi** [comment]
Probably good to try un-skipping the test and see if the test passes.

**Comment by stefanoborini** [comment]
@kitchoi trying now.
