### ISSUE TITLE
Mailing list?

### ISSUE THREAD

**Issue by nicolasbock** [enthought/mayavi#226]
Hi,

is the mailing list still up and used? I can't connect to the subscriber webpage:

https://mail.enthought.com/mailman/listinfo/enthought-dev

And the archive on gmane is not current. Or is the preferred way of asking questions github now?

Thanks already,

nick

**Comment by dmsurti** [comment]
@nicolasbock You can ask questions on GH. Thanks.

**Comment by nicolasbock** [comment]
Thanks!
