### ISSUE TITLE
Help / User Guide link is obsolete

### ISSUE THREAD

**Issue by jdmarch** [enthought/mayavi#256]
Points to:
http://code.enthought.com/projects/mayavi/docs/development/html/mayavi/
Should be: 
http://docs.enthought.com/mayavi/mayavi/

**Comment by souravsingh** [comment]
Is the issue related to this [doc?](https://github.com/enthought/mayavi/blob/3896ce6ce4fee2b4e396f8236f7e208a35860392/docs/source/mayavi/installation.rst).If so,I can make a quick PR to fix this

**Comment by jdmarch** [comment]
@souravsingh thanks! All references in this repo to code.enthought.com are obsolete. The file that you cite is one of them but not the only nor the primary one. Any PR to update any of these would be welcome.

**Comment by kitchoi** [comment]
Closed via #295
