### ISSUE TITLE
How to convert orientation to normal vector

### ISSUE THREAD

**Issue by buratono** [enthought/mayavi#260]
Hallo,
I'm using mayavi and vtk to draw a rectangle (Surface).
Mayavi uses a position(F0, F1, F2) a orientation(F0, F1, F2) to locate a rectangle, 
How can I get the normal vector of the rectangle from these parameters (position and orientation)?
Thanks,
Tom

**Comment by stefanoborini** [comment]
Not a bug. also, I don't think mayavi has such interface in place.
