### ISSUE TITLE
Error in vtk_parses while installation on Mac OS X 10.9.5

### ISSUE THREAD

**Issue by ssstuvz** [enthought/mayavi#261]
HI,

I get the following error:
File "tvtk/vtk_parser.py", line 311, in get_method_signature
AttributeError: 'NoneType' object has no attribute 'find'

This happens both when I install from source or use macports. Easy-install also doens't work for me. Is there a way to fix it?

**Comment by opoplawski** [comment]
Seeing this now in Fedora Rawhide builds - https://kojipkgs.fedoraproject.org//work/tasks/2980/11632980/build.log

**Comment by opoplawski** [comment]
Looks like this is the VTK 6.3.0 - to be satisfied by either #247 or #250

**Comment by prabhuramachandran** [comment]
Given that #250 is merged, I think this issue can be closed now, @ssstuvz -- please reopen if this is not the case.
