### ISSUE TITLE
ValueError: cannot set toolkit to wx because it has already been set to qt4

### ISSUE THREAD

**Issue by imranal** [enthought/mayavi#265]
The following import
    
    from mayavi import mlab

generates the error [MayaVi import error][1].

I installed MayaVi using setuptools. The gui works fine (some bugs here and there but still I can use the modules etc.). I am guessing some thing didn't went well with the install. Any suggestions how I can fix my installation (if that is what the problem is) ?

  [1]: http://pastebin.com/aXCBLHuF

**Comment by imranal** [comment]
I uninstalled it and reinstalled (using pip), but the `valueError` is still present.

**Comment by rossbar** [comment]
I just upgraded mayavi via pip and get the same exact error. Any luck fixing this?

**Comment by rossbar** [comment]
I didn't have time to dig through and fix this, but the workaround that worked for me was to install anaconda, conda install mayavi, and downgrade numpy to v 1.9.3 (and make sure that everything that depends on numpy is built against that version as well). Not a "solution" but if you need to get up and running again immediately this will work

**Comment by jenshnielsen** [comment]
Mayavi can run with both WX and Qt4 backends. It looks like you are trying to run it with the WX backend but have something else which imports Qt such as the matplotlib qt backend

Not clear which OS you are on but on Mac and Linux you can force Mayavi to use the Qt backend which should avoid the import of WX by adding `export ETS_TOOLKIT=qt4` to your bash profile 
See http://stackoverflow.com/questions/16350884/how-to-get-mayavi2-to-default-to-use-qt-rather-than-wx

**Comment by imranal** [comment]
I had posted the question on SO as well : http://stackoverflow.com/questions/33708292/valueerror-cannot-set-toolkit-to-wx-because-it-has-already-been-set-to-qt4/33903126#33903126
