### ISSUE TITLE
problem with install in python 3.4.3 ubuntu/elementary freya 64 bit

### ISSUE THREAD

**Issue by auvipy** [enthought/mayavi#282]
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ecsbz9s8/mayavi/setup.py", line 178
        print "Generating the mlab reference documentation"
                                                          ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ecsbz9s8/mayavi

**Comment by jenshnielsen** [comment]
Mayavi only gained support for python3 a couple of weeks ago. You need the very last tip of the master brach for that to work. Judging from the error message that you are seeing you are not running the latest release on master. You also need VTK 7 (just released) along with unreleased versions of other packages for it to run on python3. See #250

**Comment by auvipy** [comment]
thank you :)

**Comment by stefanoborini** [comment]
Closing.
