### ISSUE TITLE
Python console View does not resize side panel

### ISSUE THREAD

**Issue by stefanoborini** [enthought/mayavi#320]
Start mayavi and make sure nothing is activated on the side panel. Then go to View -> Python. This will open the python console, but this is what I see on my OSX (using qt backend). Note the console on the top left corner.

<img width="1440" alt="mayavi-bug" src="https://cloud.githubusercontent.com/assets/132967/13927245/e0d6d1cc-ef87-11e5-8e95-624db549f493.png">

**Comment by kitchoi** [comment]
I am not able to reproduce this on my OSX (10.11).  Can you provide the versions of pyface, traitsui please?  Are you using pyside or pyqt?  which version?

**Comment by corranwebster** [comment]
Pyface/workbench tries to cache layout - it is possible that your cache is
messed up.  Try deleting the pyface/workbench directory in
.enthought/mayavi and see if problem persists.

**Comment by stefanoborini** [comment]
Confirmed it went away after I cleaned the workbench cache. Closing, although I am still curious how I got in that state.
