### ISSUE TITLE
TVTK build failure with vtk-7.0.0

### ISSUE THREAD

**Issue by oudou** [enthought/mayavi#322]
I could not get current git version of mayavi to build with vtk-7.0.0. Here's the log from gdb:

    (gdb) run setup.py build
    Starting program: /usr/bin/python2 setup.py build
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/usr/lib/libthread_db.so.1".
    running build
    ----------------------------------------------------------------------
    Building TVTK classes... vtkContextDevice2D: Ignoring method: Get/SetViewportRect
    default: [-134483824, 32767, -307014816, 32767], range: None
    vtkContextDevice2D: Ignoring method: Get/SetViewportSize
    default: [-462299088, 32767], range: None
    vtkGeoTreeNode: Ignoring method: Get/SetStatus
    default: 0, range: None
    vtkIncrementalForceLayout: Ignoring method: Get/SetGravityPoint
    default: [200.0, 200.0], range: None

    Program received signal SIGSEGV, Segmentation fault.
    0x00007fffa3c04064 in vtkLineIntegralConvolution2D::SetVTShader(vtkShaderProgram*) () from /usr/lib/libvtkRenderingLICOpenGL2.so.1

This is with the vtk-7.0.0-2 build from the Arch repos. I'm not sure if this indicates a problem with vtk, the build I have, or mayavi.

**Comment by isohatalaj** [comment]
I'm having the same problem. Looks like it is VTK bug, as I can reproduce it in C++ with a simple example:

```c++
// test.cc
#include "vtkLineIntegralConvolution2D.h"
#include "vtkSmartPointer.h"

int
main()
{
  vtkSmartPointer<vtkLineIntegralConvolution2D> lic;
  lic = vtkSmartPointer<vtkLineIntegralConvolution2D>::New();
  return 0;
}
```
Running this,
```
g++ test.cc -I /usr/include/vtk/ -L /usr/lib/ -lvtkRenderingLICOpenGL2 -lvtkCommonCore && ./a.out
```
gives a segfault in `SetVTShader`. 

Anyhow, the bug seems trivial. As far as I can see from the source the function, called from `vtkLineIntegralConvolution2D` destructor, dereferences a `NULL`, due to missing checks. I'll try to see if I can submit a fix or a bug report.

**Comment by oudou** [comment]
Thanks for investigating.
