### ISSUE TITLE
how to change the lights via python

### ISSUE THREAD

**Issue by flabowski** [enthought/mayavi#333]
Hey there,
I hope this is the right place to ask, since I could not find any help in the manual, the web page or google.
I am using Mayavi 4.4.4 via Python 3.4 and wondered whether it is possible to change the lighting of a scene using the python code.
I want to visualize scientific data and therefore I am looking for a way to have equal lightig all over the scene. I don't want the spezified colors of the plot changed.

**Comment by flabowski** [comment]
Thank you @stefanoborini. I am looking forward to any helpful comment!

**Comment by flabowski** [comment]
I would greatly appreciate it if someone kindly gives me some feedback on this issue.

**Comment by stefanoborini** [comment]
@prabhuramachandran has the required expertise. comment on this?

**Comment by flabowski** [comment]
Hi,
I found out there is a property called lighting.
In case someone stumbles across this topic, you might want to write something like this:
```
import numpy as np
from mayavi import mlab

fig = figure()
mlab.clf()
phi, theta = np.mgrid[0:np.pi:11j, 0:2*np.pi:11j]
x = np.sin(phi) * np.cos(theta)
y = np.sin(phi) * np.sin(theta)
z = np.cos(phi)
Out = mlab.mesh(x, y, z)
mlab.mesh(x, y, z, representation='wireframe', color=(0, 0, 0))

Out.actor.property.lighting = False

mlab.show()
```
If you want to change the position of a light instead:
```
camera_light0 = fig.scene.light_manager.lights[0]
camera_light0.elevation = elevation_light0
camera_light0.azimuth = azimuth_light0
camera_light0.intensity = 1.0
```
If you like to use more than the 3 default lights:
```
from tvtk.pyface.light_manager import CameraLight
camera_light3 = CameraLight(fig.scene)
fig.scene.light_manager.lights[3:3] = [camera_light3]
camera_light3 = fig.scene.light_manager.lights[3]
camera_light3.elevation = elevation_light3
camera_light3.azimuth = azimuth_light3
camera_light3.intensity = 1.0
camera_light3.activate = True
fig.scene.light_manager.number_of_lights = 4
```

**Comment by prabhuramachandran** [comment]
@flabowski -- am happy you figured this out.  There are also two default modes you can use for the lighting:

```
from mayavi import mlab
s = mlab.test_plot3d()
print s.scene.light_manager.light_mode
```
This defaults to "raymond" mode which provides 3 lights for a more uniform scene.  You can set it to "vtk" for the default VTK lighting with a single light.

```
from mayavi import mlab
s = mlab.test_plot3d()
s.scene.light_manager.light_mode = "vtk"
```

On a scene you can also press the "l" (lower case L) key to pop up a traits UI editor to edit the light configuration yourself.  The parameters can then be used to automatically set it as you have discovered.

I am closing this ticket for now.  If you think this is useful, could you please send a PR with an update to the documentation that we can merge so others can learn about this?  Thanks!
