### ISSUE TITLE
array_ext.so needs to be rebuilt upon upgrading to vtk7

### ISSUE THREAD

**Issue by kitchoi** [enthought/mayavi#336]
Regarding `python3 setup.py develop`, if `tvtk/array_ext.so` already exists and is built from vtk6.x, it needs to be removed and rebuilt for vtk7.

**Comment by stefanoborini** [comment]
Probably a good idea just to remove it before every build?

**Comment by kitchoi** [comment]
yep, probably similar to rebuilding `tvtk_classes.zip`

**Comment by stefanoborini** [comment]
Working on it.

**Comment by stefanoborini** [comment]
reopening. I might have accidentally closed it.

**Comment by stefanoborini** [comment]
After discussion with @cournape we decided it's probably a better idea not to go down this path. You should just clean. Mayavi is doing rather non-standard things with distutils, and we are probably trying to solve the wrong problem.

Closing as wontfix. Just clean instead.

**Comment by stefanoborini** [comment]
@kitchoi pr open.
