### ISSUE TITLE
Error "API 'QString' has already been set to version 1" in IPython console

### ISSUE THREAD

**Issue by indranilsinharoy** [enthought/mayavi#338]
I have installed Mayavi-4.4.4 (after downloading from mayavi-4.4.4+vtk700-cp27-cp27m-win_amd64.whl from Christoph Gohlke's Unofficial Windows Binaries for Python Extension Packages. 

I use Anaconda with Python 2.7 on 64-bit Windows 7 machine.

However, when I try to import mlab, I get the error:

```python
ValueError: API 'QString' has already been set to version 1
```

How can I resolve it?

Thank you.

**Comment by kitchoi** [comment]
Are you using `ipython --gui=qt` with PyQt as backend?
If this is the case, could you please try the following and see if this works for you?
```
$ export QT_API=pyqt
$ export ETS_TOOLKIT=qt4
$ ipython   ### <--- there is no "--gui=qt"
```
See http://ipython.readthedocs.org/en/stable/interactive/reference.html?highlight=QT_API

**Comment by stefanoborini** [comment]
I've already seen this error somewhere else https://github.com/enthought/mayavi/issues/129 

Duplicate i think.

**Comment by stefanoborini** [comment]
Closing as duplicate.
