### ISSUE TITLE
Mayavi2 on Ubuntu 12.04 (64 Bit)

### ISSUE THREAD

**Issue by ghost** [enthought/mayavi#34]
Hello,

I used to use Mayavi2 on my Ubuntu 10.04 (python 2.6) machine.  After a new installation of Ubuntu 12.04 (and Python 2.7.3), mayavi2 does not work.

I get the following error:

The program 'python' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadRequest (invalid request code or no such operation)'.
  (Details: serial 2610 error_code 1 request_code 154 minor_code 19)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

After running in the verbose mode, the error is:

INFO|2012-06-08 14:45:02,095|********************************************************************************
INFO|2012-06-08 14:45:02,095|logfile is: '/home/deniz/.enthought/mayavi_e3/mayavi.log'
INFO|2012-06-08 14:45:02,095|********************************************************************************
DEBUG|2012-06-08 14:45:02,095|---------- workbench application ----------
DEBUG|2012-06-08 14:45:02,095|---------- application starting ----------
DEBUG|2012-06-08 14:45:02,096|plugin envisage.core starting
DEBUG|2012-06-08 14:45:02,102|extensions to <envisage.preferences> <[[], ['pkgfile://envisage.ui.workbench/preferences.ini'], ['pkgfile://mayavi/preferences/preferences.ini'], ['pkgfile://tvtk.plugins.scene/preferences.ini'], ['pkgfile://apptools.logger/plugin/preferences.ini'], [], [], [], []]>
DEBUG|2012-06-08 14:45:02,103|loading preferences from <<open file '/usr/lib/python2.7/dist-packages/envisage/ui/workbench/preferences.ini', mode 'rb' at 0x50eb420>>
DEBUG|2012-06-08 14:45:02,103|loading preferences from <<open file '/usr/lib/python2.7/dist-packages/mayavi/preferences/preferences.ini', mode 'rb' at 0x50eb4b0>>
DEBUG|2012-06-08 14:45:02,104|loading preferences from <<open file '/usr/lib/python2.7/dist-packages/tvtk/plugins/scene/preferences.ini', mode 'rb' at 0x50eb420>>
DEBUG|2012-06-08 14:45:02,104|loading preferences from <<open file '/usr/lib/python2.7/dist-packages/apptools/logger/plugin/preferences.ini', mode 'rb' at 0x50eb4b0>>
DEBUG|2012-06-08 14:45:02,109|extensions to <envisage.class_load_hooks> <[[], [], [], [], [], [], [], [], []]>
DEBUG|2012-06-08 14:45:02,115|extensions to <envisage.categories> <[[], [], [], [], [], [], [], [], []]>
DEBUG|2012-06-08 14:45:02,120|extensions to <envisage.service_offers> <[[], [<envisage.service_offer.ServiceOffer object at 0x5342590>, <envisage.service_offer.ServiceOffer object at 0x5342bf0>], [], [], [], [], [], [], []]>
DEBUG|2012-06-08 14:45:02,120|service <1> registered apptools.preferences.ui.preferences_manager.PreferencesManager
DEBUG|2012-06-08 14:45:02,120|service <2> registered envisage.ui.workbench.workbench.Workbench
DEBUG|2012-06-08 14:45:02,120|plugin envisage.core started
DEBUG|2012-06-08 14:45:02,121|plugin envisage.ui.workbench starting
DEBUG|2012-06-08 14:45:02,121|plugin envisage.ui.workbench started
DEBUG|2012-06-08 14:45:02,121|plugin mayavi starting
DEBUG|2012-06-08 14:45:02,121|plugin mayavi started
DEBUG|2012-06-08 14:45:02,121|plugin tvtk.scene starting
DEBUG|2012-06-08 14:45:02,121|plugin tvtk.scene started
DEBUG|2012-06-08 14:45:02,121|plugin apptools.logger starting
WARNING|2012-06-08 14:45:02,122|plugin <envisage.plugins.text_editor.text_editor_plugin.TextEditorPlugin object at 0x53420b0> has no Id - using <envisage.plugins.text_editor.text_editor_plugin.TextEditorPlugin>
WARNING|2012-06-08 14:45:02,590|view <envisage.plugins.python_shell.view.namespace_view.NamespaceView object at 0x562a3b0> has no Id - using <envisage.plugins.python_shell.view.namespace_view.NamespaceView>
The program 'python' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadRequest (invalid request code or no such operation)'.
  (Details: serial 2610 error_code 1 request_code 154 minor_code 19)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

Can you please help.

**Comment by stefanoborini** [comment]
Impossible to reproduce. Likely cause is a change in X libraries with the upgrade. A fresh reinstall of a recent version of mayavi after the upgrade is probably the best strategy. Closing
