### ISSUE TITLE
mayavi2: segfaults as soon as a module is loaded from object editor

### ISSUE THREAD

**Issue by varunh** [enthought/mayavi#39]
Hi,

Please check this bug report filed in Debian:
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=677421

""""
Steps to reproduce:

 0) take some data to visualize and start mayavi2; for instance:

    $ zcat /usr/share/doc/mayavi2/examples/mayavi/data/fire_ug.vtu.gz > fire_ug.vtu
    $ zcat /usr/share/doc/mayavi2/examples/mayavi/data/room_vis.wrl.gz > room_vis.wrl
    $ mayavi2 -d room_vis.wrl -d fire_ug.vtu

 1) add a module; for instance: Streamline, or IsoSurface, or something else using the Mayavi Object Editor
      In the tree-like view of the objects, click on "+Add module or filter" (under "VTK XML file (fire_ug.vtu)"), then in the Mayavi object editor ("Visualization modules" tab) double-click on "Streamline".     

 2) mayavi2 exits and the only output on the terminal is
    "Segmentation fault"

""""

Thanks,
Varun

**Comment by stefanoborini** [comment]
It is of my understanding that mayavi cannot work on ubuntu with wx due to ABI incompatibilities. The default qt backend works. As a result, I think this bug can be archived as wontfix. @jdmarch do you have any comment?

**Comment by kitchoi** [comment]
Ubuntu 12 (VM, 64bit) + wxPython (2.8.10) + Mayavi 4.4.4 + VTK 6.3.0 does not cause the said problem for me.

**Comment by jdmarch** [comment]
When present: general wx issue, not mayavi-specific, AFAIK. 
For workaround, see https://support.enthought.com/hc/en-us/articles/207229586-Unable-to-run-wxPython-3-0-x-on-Ubuntu-e-g-using-wx-as-matplotlib-backend-

**Comment by stefanoborini** [comment]
@jdmarch thank you. Closing
