### ISSUE TITLE
vtkOutput Error message when using tvtk.tools.visual.Sphere

### ISSUE THREAD

**Issue by sebastian-prep** [enthought/mayavi#423]
This was working fine but after the latest Enthought Canopy (64-bit) updates to mayavi 4.4.3-10 and VTK 6.3.0-4, I get this annoying error message (python 2.7.6 | 64-bit ) when I construct a wireframe sphere:

from mayavi import mlab
from enthought.tvtk.tools import visual

engine = mlab.get_engine();
mlab_fig = mlab.figure(figure=None, bgcolor=(0,1,1), fgcolor=(1,1,1), size=(1000, 1000));     visual.set_viewer(mlab_fig);
mlab_scene = engine.scenes[0].scene;
mlab_camera = mlab_scene.camera;
mlab_scene.camera.distance = 1;
sph = visual.Sphere( pos = (0, 0, 0),
                         radius = 1.0 / 0.02, representation = 'w', 
                         opacity=0.1, color=(0.38, 0, 1.0) );

Gives:
"
ERROR: In C:\pisi\tmp\VTK-6.3.0-4\work\VTK-6.3.0\Common\ExecutionModel\vtkDemandDrivenPipeline.cxx, line 710
vtkCompositeDataPipeline (00000000137EFBF0): Input port 0 of algorithm vtkPolyDataNormals(00000000135FD3B0) has 0 connections but is not optional.

ERROR: In C:\pisi\tmp\VTK-6.3.0-4\work\VTK-6.3.0\Common\ExecutionModel\vtkDemandDrivenPipeline.cxx, line 710
vtkCompositeDataPipeline (00000000137EFBF0): Input port 0 of algorithm vtkPolyDataNormals(00000000135FD3B0) has 0 connections but is not optional.

ERROR: In C:\pisi\tmp\VTK-6.3.0-4\work\VTK-6.3.0\Common\ExecutionModel\vtkDemandDrivenPipeline.cxx, line 710
vtkCompositeDataPipeline (00000000137EFBF0): Input port 0 of algorithm vtkPolyDataNormals(00000000135FD3B0) has 0 connections but is not optional.

ERROR: In C:\pisi\tmp\VTK-6.3.0-4\work\VTK-6.3.0\Common\ExecutionModel\vtkDemandDrivenPipeline.cxx, line 710
vtkCompositeDataPipeline (00000000137EFBF0): Input port 0 of algorithm vtkPolyDataNormals(00000000135FD3B0) has 0 connection
"

The sphere is displayed fine and the rendering works fine.

**Comment by prabhuramachandran** [comment]
visual was in terrible shape and this has been fixed in mayavi-4.5.0 which was just released a couple of days ago.  See #416 and #387 which is now fixed.  Closing for now.
