### ISSUE TITLE
3D Visualizer / TVTK Window (Not Responding) on Windows 7 64-Bit

### ISSUE THREAD

**Issue by brymz** [enthought/mayavi#43]
I am working to install Mayavi2 on my Windows 7 (64 Bit), but am not able to fully interact with the visualizer or TVTK window. They freeze immediately upon first opening. I have tried to install Mayavi2 using both the Enthought (64 Bit & 32 Bit) and Python(x,y) distributions with full system cleans before the installation to ensure that all Python materials are removed. Each installation allows me to interact with Python with no noticeable trouble and I am able to "import mayavi" to my shell. The problem comes when calling a mayavi function (e.g., mlab.plot3d) or simply running the Mayavi2 GUI. Immediately the window freezes and shows a (Not Responding) message. I have tried to install the package on another Windows 7 (64 Bit) machine with no problem. Thanks for the help. I am very interested to see if there is a machine-specific solution to my problem or what I might try to get around this window crash.

**Comment by stefanoborini** [comment]
Seems to be solved. Closing.

**Comment by gowthamikandru** [comment]
can any one of you please tell me how to remove my default mayavi ToolBar

import scipy as np
from mayavi import mlab


x,y = np.mgrid[-3:3:100j, -3:3:100j]

a = 0.3

a0 = 0.2

r1=np.sqrt((x-a)**2 + y**2)

values = np.sinc(-r1/a0)



mlab.surf(values, warp_scale='auto')

mlab.outline()

mlab.axes()
# mlab.test_contour3d()
mlab.show()

**Comment by SFETNI** [comment]
adding  "mlab.show(stop=True)"  may help to avoid "not responding mlab" 
that works for me
