### ISSUE TITLE
BUG: mayavi segfaults at program exit

### ISSUE THREAD

**Issue by larsoner** [enthought/mayavi#436]
I have Mayavi up and running on an Ubuntu CI using Anaconda, and locally on my Ubuntu machine using a recent (last ~month) `master` and both machines experience segmentation faults that look like this (often when a program is in the process of closing, which makes me think it could be a cleanup problem):

```
X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
  Major opcode of failed request:  72 (X_PutImage)
  Resource id in failed request:  0x3a00002
  Serial number of failed request:  74
  Current serial number in output stream:  78
make: *** [html_dev] Error 1
```

It happens in our use case that involves doing lots of off-screen drawing and screen captures. Unfortunately the failures are intermittent so it's not trivial to reproduce. Are there additional debugging steps (like making a debug build maybe?) that I could take to debug this?

**Comment by Eric89GXL** [comment]
This seems to be due to Ubuntu's packaged VTK -- when I use a self-built 7.0.0 the problem goes away. I guess we'll have to wait for the Anaconda folks to bump versions to get our CIs happy.

**Comment by prabhuramachandran** [comment]
Can't you use the conda-forge build? I believe the menpo package repo also has a working VTK+mayavi-4.5.0 that you can install with conda.

**Comment by Eric89GXL** [comment]
I haven't tried that yet, thanks for the hint

**Comment by Eric89GXL** [comment]
This problem persists even with 4.5.0 and VTK 6.3 currently packaged with conda, e.g. the end of the log here:

https://circleci.com/gh/mne-tools/mne-python/4613#build-timing/containers/0

This makes me think that it's a persistent problem. Not sure if it's `mayavi` or (more likely) VTK that is the root of the problem.

**Comment by larsoner** [comment]
I think this is a VTK 6 problem, I no longer experience this with 7+.
