### ISSUE TITLE
BUG: importing mayavi corrupts memory of other libraries

### ISSUE THREAD

**Issue by Eric89GXL** [enthought/mayavi#437]
On my Ubuntu system, adding `import mayavi.mlab` (but not just `import mayavi`) to a script will cause *other libraries* to start computing things (e.g. `scipy.linalg.svd`) incorrectly. I suspect that `mayavi.mlab` import is probably overwriting memory where it shouldn't. This one is hard for me to reproduce with a simple example.

Has anyone seen this before? If not, I can try selectively commenting out bits of whatever `mayavi.mlab` does to try to isolate it to maybe some sub-package or call.

(As far as I can tell, this is actually a separate problem from #436, since it presumably isn't related to X cleanup.)

**Comment by Eric89GXL** [comment]
... now I have it isolated to being caused by a call within `mayavi` to:
```
from tvtk.common import is_old_pipeline
```
In other words, that import line also causes library corruption. I'll keep digging...

**Comment by Eric89GXL** [comment]
Looks like this is actually caused by a VTK problem, as this also corrupts:
```
import vtk
```
I'll close this, sorry for the noise!

**Comment by prabhuramachandran** [comment]
@Eric89GXL -- Ubuntu by default ships a libvtk-6.2 which links to Qt5.  So importing anything that needs qt4 will cause a crash.  Mayavi is therefore broken on ubuntu (16.04 as well).
