### ISSUE TITLE
instructions for installing jupyter notebook extensions fail with error message: Unrecognized flag: '--py'

### ISSUE THREAD

**Issue by mikeroberts3000** [enthought/mayavi#441]
Hello,

The instructions for installing the jupyter notebook extensions for Mayavi (listed at http://docs.enthought.com/mayavi/mayavi/tips.html) are to type the following shell command:

```
$ jupyter nbextension install --py mayavi --user
```

Doing so yields the following error on my system:

```
[InstallNBExtensionApp] CRITICAL | Bad config encountered during initialization:
[InstallNBExtensionApp] CRITICAL | Unrecognized flag: '--py'
```

I have jupyter 4.1.0 installed (verified by typing `jupyter --version` on the command line) and Mayavi 4.2.0 installed (verified by running `import mayavi; print mayavi.__version__;` from within a python session).

**Comment by kitchoi** [comment]
Hi Mike,
I am sorry that the jupyter notebook functionality is new in Mayavi version 4.5.0
I think the documentation tips page would benefit from a note on which version the feature is available.
Thanks for your report.  Closing.

**Comment by mikeroberts3000** [comment]
Ah, makes sense. Thanks for the reply. I'll keep an eye out for when version 4.5 makes it into the Canopy package manager, which currently only has version 4.4.3.

@kitchoi Silly question, are Mayavi animations (e.g., created with the `@mayavi.mlab.animate` function decorator) supported in Jupyter notebooks?

**Comment by prabhuramachandran** [comment]
@mikeroberts3000 -- actually, if you do not run `jupyter nbextension install --py mayavi --user` you should still be able to use the new feature. You won't be able to see the plots without an internet connection though.  The installation just installs the JS files, so to get this working all you need to do is:

```
mlab.init_notebook(local=False)
```

and it should work and pull the JS files from the internet.

**Comment by prabhuramachandran** [comment]
@mikeroberts3000 -- to answer your question on the animate decorator, yes it *should* work on the notebook. However, it will produce meaningful output only if screenshots are properly generated in offscreen mode -- unfortunately this is often tricky and platform/build dependent.

**Comment by prabhuramachandran** [comment]
@mikeroberts3000 -- I am terribly sorry, I got all confused with the jupyter version and the mayavi version.  Indeed you need mayavi-4.5.0 for the new `init_notebook` function!  I will document this.
