### ISSUE TITLE
Rendering issues in docs

### ISSUE THREAD

**Issue by rahulporuri** [enthought/mayavi#442]
http://docs.enthought.com/mayavi/mayavi/mlab_case_studies.html

**Comment by prabhuramachandran** [comment]
Can you please be a bit more specific with what the actual issue is?  Thanks.

**Comment by rahulporuri** [comment]
sorry. i thought i included the screenshot. 
<img width="1185" alt="screen shot 2016-10-05 at 8 12 44 pm" src="https://cloud.githubusercontent.com/assets/1926457/19117892/409c9c80-8b38-11e6-9e10-e2fd37d941b1.png">

**Comment by prabhuramachandran** [comment]
@rahulporuri -- sorry, I still don't understand, what specifically is the issue, can you please elaborate?

**Comment by rahulporuri** [comment]
prolly a non issue, closing.
