### ISSUE TITLE
'f' key (move camera focus) not working

### ISSUE THREAD

**Issue by subnivean** [enthought/mayavi#464]
While viewing the output of `mlab.test_mesh()` in IPython qtconsole (Mayavi 4.4.3/VTK 6.2.0/IPython 2.4.1/Python 2.7.12/Ubuntu 16.04, 64 bit), hitting the 'f' key produces the following traceback:

<code><pre>TraitError                                Traceback (most recent call last)
/usr/lib/python2.7/dist-packages/tvtk/pyface/ui/wx/scene.pyc in OnKeyUp(self=<mayavi.core.ui.mayavi_scene.MayaviScene object>, event=<wx._core.KeyEvent; proxy of <Swig Object of type 'wxKeyEvent *' at 0x7ffe46d9c710> >)
    482                         x = event.GetX()
    483                         y = self._vtk_control.GetSize()[1] - event.GetY()
--> 484                     data = self.picker.pick_world(x, y)
        data = undefined
        self.picker.pick_world = <bound method Picker.pick_world of <tvtk.pyface.picker.Picker object at 0x7f1be3a62890>>
        x = 237
        y = 205
    485                     coord = data.coordinate
    486                     if coord is not None:

/usr/lib/python2.7/dist-packages/tvtk/pyface/picker.pyc in pick_world(self=<tvtk.pyface.picker.Picker object>, x=237, y=205)
    393             # does not seem to work properly.
    394             probe = tvtk.ProbeFilter()
--> 395             probe.source = data
        probe.source = None
        data = <tvtk.tvtk_classes.poly_data.PolyData object at 0x7f1be0ea5170>
    396             probe.input = self.probe_data
    397             probe.update()

/usr/lib/python2.7/dist-packages/traits/trait_handlers.pyc in _read_only(object=<tvtk.tvtk_classes.probe_filter.ProbeFilter object>, name='source', value=<tvtk.tvtk_classes.poly_data.PolyData object>)
    102 def _read_only ( object, name, value ):
    103     raise TraitError, "The '%s' trait of %s instance is 'read only'." % (
--> 104                       name, class_of( object ) )
        name = 'source'
        global class_of = <function class_of at 0x7f1c50013d70>
        object = <tvtk.tvtk_classes.probe_filter.ProbeFilter object at 0x7f1be068cc50>
    105 
    106 def _undefined_get ( object, name ):

TraitError: The 'source' trait of a ProbeFilter instance is 'read only'.
</pre></code>

I've found that changing line #484 in `/usr/lib/python2.7/dist-packages/tvtk/pyface/ui/wx/scene.py` from:

`data = self.picker.pick_world(x, y)`
to either:
`data = self.picker.pick_cell(x, y)`
or:
`data = self.picker.pick_point(x, y)`
fixes the problem.

I've also applied the same fix to the same behavior in the latest version of WinPython (VTK 7/Mayavi 4.5.0/Python 3.5.2.3/IPython 4.5/Win7 64bit)

**Comment by spescha** [comment]
I experience the same problem and the same solution works for me, also with the pyface backend set to qt4 and editing the file `.../tvtk/pyface/ui/qt4/scene.py` on line 128. 

I am working with mayavi 4.5.0-4 on Win7 64bit.

I would appreciate if you could fix this bug. Thanks.

**Comment by subnivean** [comment]
Fixed in 4.6.2
