### ISSUE TITLE
python cv2.remap creates nothing

### ISSUE THREAD

**Issue by snuchitp** [enthought/mayavi#481]
After I run this code, imageL and imageR display normally. but undistortion images display nothing. What is wrong with my code?

Thanks

R1, R2, P1, P2, Q, roi1, roi2 = cv2.stereoRectify(cameraMatrix1, distCoeffs1, cameraMatrix2, distCoeffs2,(width, height), R, T, R1, R2, P1, P2, Q=None,  alpha = rectify_scale, newImageSize=(0,0))

map1x, map1y = cv2.initUndistortRectifyMap(cameraMatrix1, distCoeffs1, R1, P1, (width, height), cv2.CV_32FC1)

map1x_32 = map1x.astype('float32')

map1y_32 = map1y.astype('float32')

map2x, map2y = cv2.initUndistortRectifyMap(cameraMatrix2, distCoeffs2, R2, P2, (width, height), cv2.CV_32FC1)

map2x_32 = map2x.astype('float32')

map2y_32 = map2y.astype('float32')

imgL = cv2.imread('vaseClastl.png')

heightL, widthL, depthL  = imgL.shape

imgR = cv2.imread('vaseClastr.png')

imgUL = cv2.remap(imgL, map1x_32, map1y_32, cv2.INTER_LINEAR)

imgUR = cv2.remap(imgR, map2x_32, map2y_32, cv2.INTER_LINEAR)

cv2.imshow("imageL", imgL);

cv2.imshow("imageR", imgR);

cv2.imshow("image1L", imgUL);

cv2.imshow("image2R", imgUR);

**Comment by prabhuramachandran** [comment]
This is not related to Mayavi at all, please submit this on the OpenCV or other relevant package issues.  Closing.
