### ISSUE TITLE
BUG: Opacity of streamlines interacting with visual ordering of visualization modules

### ISSUE THREAD

**Issue by Mallcock1** [enthought/mayavi#491]
Changing the opacity of streamlines to anything other than its default value (1.0) brings the streamlines to the front of the scene even when there are other objects that should obscure them.

For example, I refer you to the magnetic fieldline example given here: http://docs.enthought.com/mayavi/mayavi/auto/example_magnetic_field_lines.html.

Running the code as it is gives the following scene:
![test_bug_1](https://cloud.githubusercontent.com/assets/16650576/23604332/6e7d8e5e-0250-11e7-88da-18aa01590801.png)

However, if we change the opacity of the fieldlines so that it is different it its default value of 1.0 (either by adding `field_lines.actor.property.opacity = 0.99` or by manually adjusting the opacity in the Mayavi pipeline) we get something like the following scene:
![test_bug_2](https://cloud.githubusercontent.com/assets/16650576/23604357/7cd1d58c-0250-11e7-983c-5a365a010399.png)
The fieldlines are now at the front of the scene, however the isocontours should still obscure then like in the previous image.

**Comment by Mallcock1** [comment]
Is this an issue which will be fixable in the near future? If not, I would appreciate knowing so that I can find another way around my problem. Thank you

**Comment by luukko** [comment]
This seems to apply to other objects as well. I'm using contour3d with points3d and setting the opacity of the points to anything other than 1.0 causes the surface not to obscure them anymore.

**Comment by jeswcollins** [comment]
Yes I have what I think is the same issue with two points3d objects. Here's some examples of 2 spheres rendered showing how their appearance depends on rendering order if the opacity is set to .99 but not if set to 1.

```python
mlab.figure()
mlab.points3d(0,0,1,color=(.8,.8,.8),resolution=100,opacity=.99)
mlab.points3d(0,0,0,color=(.8,.8,.8),resolution=100,opacity=.99)
```
![2](https://user-images.githubusercontent.com/4534080/30778768-128a19fa-a0ac-11e7-8277-121654980e15.png)

```python
mlab.figure()
mlab.points3d(0,0,0,color=(.8,.8,.8),resolution=100,opacity=.99)
mlab.points3d(0,0,1,color=(.8,.8,.8),resolution=100,opacity=.99)
```
![4](https://user-images.githubusercontent.com/4534080/30778772-20f81c4e-a0ac-11e7-8808-cac80d4c08b6.png)

```python
mlab.figure()
mlab.points3d(0,0,1,color=(.8,.8,.8),resolution=100)
mlab.points3d(0,0,0,color=(.8,.8,.8),resolution=100)
```
![1](https://user-images.githubusercontent.com/4534080/30778756-dc1efab6-a0ab-11e7-9415-a4c6ca6b5d18.png)

```python
mlab.figure()
mlab.points3d(0,0,0,color=(.8,.8,.8),resolution=100)
mlab.points3d(0,0,1,color=(.8,.8,.8),resolution=100)
```
![3](https://user-images.githubusercontent.com/4534080/30778762-0b91731e-a0ac-11e7-8928-6c16f2b59c51.png)

**Comment by prabhuramachandran** [comment]
You probably need to set the front-face culling option on.  Try this:
```
mlab.figure()
g1 = mlab.points3d(0,0,1,color=(.8,.8,.8),resolution=100,opacity=.99)
g2 = mlab.points3d(0,0,0,color=(.8,.8,.8),resolution=100,opacity=.99)
g1.actor.property.frontface_culling = True
g2.actor.property.frontface_culling = True
```

**Comment by jeswcollins** [comment]
I reproduced my observation in vtk alone (it's a lower level issue).

After more reading, I think there is a solution or two built into vtk, but another solution may be to sort the objects before rendering.

Here are a couple links about vtk that seemed relevant:
https://www.vtk.org/Wiki/VTK/Examples/Cxx/Visualization/CorrectlyRenderingTranslucentGeometry
https://www.vtk.org/Wiki/VTK/Depth_Peeling

And a couple links I used for reproducing the sphere case:
https://lorensen.github.io/VTKExamples/site/Python/GeometricObjects/Sphere/
https://www.vtk.org/Wiki/VTK/Examples/Cxx/Visualization/Opacity

**Comment by Mallcock1** [comment]
Thanks for adding to the discussion and for the helpful links. I am not very knowledgeable about VTK or depth peeling, but a simple solution that I found that worked for my original example and the project I am working on was to include this:

`scene = mlab.gcf().scene
scene.renderer.set(use_depth_peeling=True)`

which I adapted from [this](http://enthought-dev.117412.n3.nabble.com/Trouble-during-on-depth-peeling-td3304740.html) question about a similar issue..

**Comment by jeswcollins** [comment]
Thanks for the help Matt and Prabhu. 

I tried depth_peeling, but compared to reordering the spheres, the edges seem less...anti-aliased I think might be the term? 

f=mlab.figure()
f.scene.renderer.use_depth_peeling=1
g0=mlab.points3d(0,0,1,color=(.8,.8,.8),resolution=100,opacity=.99)
g1=mlab.points3d(0,0,0,color=(.8,.8,.8),resolution=100,opacity=.99)  
g1.actor.property.frontface_culling = True
g2.actor.property.frontface_culling = True
![image](https://user-images.githubusercontent.com/4534080/30997344-33cf589a-a495-11e7-864e-ddd00e1efd02.png)

For my 3d plotting, I have a list of points and a list of colors. So instead of depth peeling I used this function to reorder those lists together before plotting:

```def orderTransparentRender(cl,c):
    '''Opacity < 1 rendering results in appearance of spheres incorrectly in front of or behind other spheres
    One solution is setting f.scene.renderer.use_depth_peeling=1, however this seemed to result in less anti-aliased edges?
    This function sorts the cluster list cl and color list c together.
    '''
    cz=zip(cl,c)
    cz=sorted(cz,key=lambda x:-1*x[0][2])
    cz=zip(*cz)
    return cz[0],cz[1]
```

Otherwise the sorted call could be all that's required.  I learned that from the python docs: https://wiki.python.org/moin/HowTo/Sorting

**Comment by prabhuramachandran** [comment]
With recent VTK versions this works well for me:

```
from mayavi import mlab
f = mlab.figure()
mlab.points3d(0,0,1,color=(.8,.8,.8),resolution=100,opacity=.99)
mlab.points3d(0,0,0,color=(.8,.8,.8),resolution=100,opacity=.99)
f.scene.renderer.use_depth_peeling = True
```

Also, there is an `f.scene.renderer.maximum_number_of_peels` that you could potentially use.  It is 4 by default but you could set it to zero for no limit although this will slow down rendering.  You could tinker with this.  

May I close this issue?  I think this does seem to fix many problems I have seen before.

**Comment by Mallcock1** [comment]
Thank you. I will be able to work with this. You can close this issue.

Matthew Allcock  |  PhD researcher
University of Sheffield  |  School of Mathematics and Statistics
www.matthewallcock.co.uk

**Comment by prabhuramachandran** [comment]
Great, thanks.
