### ISSUE TITLE
Plans for mayavi with python 3.6

### ISSUE THREAD

**Issue by gnurser** [enthought/mayavi#496]
Hi,
Neither conda nor macports seem to have a mayavi working with python 3.6.  Does anybody know whether this is a problem with mayavi, or simply that the packaging hasn't been done yet?

Regards, George Nurser.

**Comment by prabhuramachandran** [comment]
Enthought's [edm](http://www.enthought.com/products/edm) does provide mayavi for Python 3.6.0.  I suspect it is just that the packaging hasn't been done yet for the others.  As regards mayavi plans, I've been busy with other things so far and hope to get back to looking at mayavi issues and tickets over the next few weeks. Am closing this for now. Please reopen if there is an issue.  Thanks!
