### ISSUE TITLE
Masking points does not work in e.g. vectors or vector_cut_plane modules

### ISSUE THREAD

**Issue by Mallcock1** [enthought/mayavi#500]
The masking of points, which should display fewer arrows in either the vectors or vector_cut_plane modules does not work.

For example, the following code (taken from the example at the bottom of this page http://docs.enthought.com/mayavi/mayavi/mlab.html) which does not include an attempt to mask points produces the following plot:
```
from mayavi import mlab
import numpy as np
x, y, z = np.mgrid[0:1:20j, 0:1:20j, 0:1:20j]

u =    np.sin(np.pi*x) * np.cos(np.pi*z)
v = -2*np.sin(np.pi*y) * np.cos(2*np.pi*z)
w = np.cos(np.pi*x)*np.sin(np.pi*z) + np.cos(np.pi*y)*np.sin(2*np.pi*z)

#mlab.quiver3d(u, v, w)
#mlab.outline()

src = mlab.pipeline.vector_field(u, v, w)
mlab.pipeline.vectors(src, scale_factor=3.)
```

![test](https://cloud.githubusercontent.com/assets/16650576/24800309/7bb42b04-1b97-11e7-8a2e-330e4fa07f3c.png)

When we ad an argument to the final line to mask points like this:
`mlab.pipeline.vectors(src, mask_points=20, scale_factor=3.)`
we get the same plot produced, with no points masked:

![test_masked](https://cloud.githubusercontent.com/assets/16650576/24800346/a1546e46-1b97-11e7-8726-dba4c66cf883.png)

This must have been raised as an error before or else it is something to do with my setup which disables the masking points function. Any ideas?

Thanks,
Matt

**Comment by prabhuramachandran** [comment]
Thank you for the report.  This is fixed in master, am closing this for now. Please reopen if there is still an issue.
