### ISSUE TITLE
Hi! guys,I found a bug in mayavi/examples/mayavi/mlab/mri.py

### ISSUE THREAD

**Issue by 577528249** [enthought/mayavi#505]
I run the file mayavi/examples/mayavi/mlab/mri.py in 
Mac OS 10.12.4 
Python 2.7.12
VTK 6.3.0
Traits 4.6.0
but it crashed in Line 66 

`voi = mlab.pipeline.extract_grid(blur)`

Do you know how to fix it? Waiting for your reply,Thx!

> 
> Python 2.7.12 |Anaconda 4.2.0 (x86_64)| (default, Jul  2 2016, 17:43:17) 
> [GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> Anaconda is brought to you by Continuum Analytics.
> Please check out: http://continuum.io/thanks and https://anaconda.org
> >>> runfile('/Users/ruiwendaier/Documents/Application/exampleFiles/mri.py', wdir='/Users/ruiwendaier/Documents/Application/exampleFiles')
> ERROR: In /Users/ilan/minonda/conda-bld/work/VTK-6.3.0/Common/ExecutionModel/vtkStreamingDemandDrivenPipeline.cxx, line 857
> vtkCompositeDataPipeline (0x12a870390): The update extent specified in the information for output port 0 on algorithm vtkImageGaussianSmooth(0x12a3d2540) is 0 2147483647 0 2147483647 0 2147483647, which is outside the whole extent 0 255 0 255 0 108.
> 
> python(57268,0x70000c092000) malloc: *** mach_vm_map(size=13835058045618487296) failed (error code=3)
> *** error: can't allocate region
> *** set a breakpoint in malloc_error_break to debug
> ERROR: In /Users/ilan/minonda/conda-bld/work/VTK-6.3.0/Common/Core/vtkDataArrayTemplate.txx, line 142
> vtkUnsignedShortArray (0x12ab0cd40): Unable to allocate 6917529022809243648 elements of size 2 bytes. 
> 
> libc++abi.dylib: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc

**Comment by prabhuramachandran** [comment]
I can reproduce the crash.  Will try to take a closer look next week.

**Comment by bhavesh2109** [comment]
Hi @577528249  and @braidedlogix. This has been addressed in #510 . Do check it out.

**Comment by 577528249** [comment]
I checked it,the problem has been soloved,you help me a lot,Thank you very much!
