### ISSUE TITLE
Bug in data sharing in Mayavi 4.5?

### ISSUE THREAD

**Issue by christianbrodbeck** [enthought/mayavi#511]
I was trying to build a simple example for a problem when I realized that the second example [here](http://gael-varoquaux.info/programming/mayavi-representing-an-additional-scalar-on-surfaces.html) does not woro properly. The only change I made to the listed sample code is `from enthought.mayavi import mlab` -> `from mayavi import mlab`. When I run it I get this dialog:

![screen shot 2017-06-13 at 8 25 30 pm](https://user-images.githubusercontent.com/145771/27111817-ab9259f4-5080-11e7-8f8d-b99fefd98540.png)

And then this:

![screen shot 2017-06-13 at 8 25 39 pm](https://user-images.githubusercontent.com/145771/27111819-b8819aa8-5080-11e7-8046-1141fe388fd9.png)

Can others reproduce this issue or is it specific to my configuration? I am using Mayavi 4.5 from anaconda `defaults` channel with Python 2.7 on the latest macOS 10.12 (beta).

**Comment by christianbrodbeck** [comment]
It turns out this can be fixed by removing the `mlab.axes()` line, thanks @Eric89GXL, as far as I'm concerned this issue can be closed but it might be relevant for others?

**Comment by christianbrodbeck** [comment]
@Eric89GXL reproduced the problem on Linux but not on OS X.

**Comment by prabhuramachandran** [comment]
@christianbrodbeck -- isn't this fixed now with #514 merged?

**Comment by christianbrodbeck** [comment]
Yes, thanks @prabhuramachandran !
