### ISSUE TITLE
Regarding VTK 7.0.0 

### ISSUE THREAD

**Issue by ramsinghdayal** [enthought/mayavi#520]
VTK-7.0.0-cp34-cp34m-win_amd64.whl is not avalable at http://www.lfd.uci.edu/~gohlke/pythonlibs/#vtk, from where I can get VTK-7.0.0-cp34-cp34m-win_amd64.whl.

**Comment by solarjoe** [comment]
https://github.com/enthought/mayavi/issues/84#issuecomment-313869503

**Comment by solarjoe** [comment]
VTK-7.0.0-cp34-cp34m-win_amd64.whl

http://ge.tt/8QvtGkl2

**Comment by ramsinghdayal** [comment]
Thank you. I am getting this error, for that what will be solution

Error: in D:\Build\VTK\VTK-7.1.1\rendering\OpenGL2\vtkOpenGLRenderWindow.cxx, line 640
vtkWin32OpenGLRenderWindow (05768FE8): GL version 2.1 with gpu_shader4 extension is not supported by your graphics driver.

**Comment by ramsinghdayal** [comment]
Requirement: VTK-7.0.0-cp35-cp35m-win_amd64.whl 
Since I am following https://www.scivision.co/mayavi-qt5-create-conda-env-qt4/, so in this mayavi 4.5 installed so here is the requirement of  VTK-7.0.0-cp35-cp35m-win_amd64.whl. Please share this version of VTK. Thank you.

**Comment by solarjoe** [comment]
I found a similar file I downloaded a while ago, name contains 'none' instead of 'cp35m'.
Don't know if that's it what you need. Added it to the folder.

http://ge.tt/8QvtGkl2

**Comment by ramsinghdayal** [comment]
How can I solve this error: 

Error: in D:\Build\VTK\VTK-7.1.1\rendering\OpenGL2\vtkOpenGLRenderWindow.cxx, line 640
vtkWin32OpenGLRenderWindow (05768FE8): GL version 2.1 with gpu_shader4 extension is not supported by your graphics driver.

**Comment by solarjoe** [comment]
> is not supported by your graphics driver.

Which GPU are you using?

**Comment by prabhuramachandran** [comment]
This is really not a Mayavi issue, so can I please close this issue?
