### ISSUE TITLE
traits.trait_errors.TraitError

### ISSUE THREAD

**Issue by webMing** [enthought/mayavi#521]
this code snippet from http://docs.enthought.com/mayavi/tvtk/README.html#basic-usage

>>> from tvtk.api import tvtk
>>> cs = tvtk.ConeSource()
>>> cs.resolution = 36
>>> m = tvtk.PolyDataMapper()
>>> m.input = cs.output

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/apple/anaconda/envs/python3.5/lib/python3.5/site-packages/traits/trait_handlers.py", line 105, in _read_only
    name, class_of( object ) ))
traits.trait_errors.TraitError: The 'input' trait of a PolyDataMapper instance is 'read only'.

my develop env configures as follows:
vtk version:7.0.0
mayavi version:4.5.0
traits version:4.5.0

anyone encounter this problem,and how to resolve ?

**Comment by prabhuramachandran** [comment]
That example is old and outdated and only relevant for VTK < 7 (or even perhaps 6.x). VTK 7.x does not have the output and input attributes.  You should instead use
```
   m.input_connection = cs.output_port
```

**Comment by webMing** [comment]
this work for me.  great thanks. @prabhuramachandran

**Comment by webMing** [comment]
is there a doc about different between  old version  and vtk7.0 ?
