### ISSUE TITLE
What does the scale_mode = 'vector' do?

### ISSUE THREAD

**Issue by solarjoe** [enthought/mayavi#529]
I could only find the same sentence in the docs over and over again :)

> scale_mode: the scaling mode for the glyphs (‘vector’, ‘scalar’, or ‘none’).

https://stackoverflow.com/questions/45217380/mayavi-what-does-the-scale-mode-vector-do

[This](http://docs.enthought.com/mayavi/mayavi/mlab_changing_object_looks.html) page explains `scale_factor` quite well. `scale_mode = 'scalar'` applies to scalar values passed to the plotting functions. But what does `vector` do?

You can also earn some points on [stackoverflow](
https://stackoverflow.com/questions/45217380/mayavi-what-does-the-scale-mode-vector-do) :)

**Comment by prabhuramachandran** [comment]
It scales the glyphs according to the magnitude of the currently active vector.

**Comment by solarjoe** [comment]
Thanks for your quick reply. 
What is the definition of 'currently active vector'? Do I have to pass a (n, 3) array as scalars?

**Comment by prabhuramachandran** [comment]
Aren't you plotting vectors using quiver3d?  If scale_mode is 'vector' they will be scaled as per the vector magnitude. quiver takes 6 args x, y, z, u, v, w.   u, v, w are the components of the vector.  Not sure what is confusing here?

**Comment by solarjoe** [comment]
Ok, thanks, I get it now for quiver3d, but I saw that also `triangular_mesh`, `mesh`, and `point3d` mention 'vector' as `scalar_mode`. Is 'vector'` only used when when `mode` for the plotting functions is set to e.g. `arrow` or `2darrow`? Or is `scale_mode = 'vector'` only valid for use with `quiver3d`?

**Comment by prabhuramachandran** [comment]
You can associate vector data with some of the other datasets too.  The scale_mode is a general attribute present on the glyph filter and it will use scalar or vector data.  For the triangular_mesh, you cannot set the vectors attribute as it does not have one (see the MTriangularMeshSource in mayavi/tools/sources.py) so it doesn't make sense.  However, you must realize that mayavi allows you to use glyphs for other datasets that do support vectors and scalars.  Therefore the scalar_mode allows you to specify how you want to scale the glyphs.  Using arrow/2darrow or any of the other glyph sources do not change how the scaling is done.  Anyway am closing this as this is not an issue per-se.  HTH.

**Comment by solarjoe** [comment]
Ok, I guess I get it now.
The parameter tells which part of the underlying data set to use for the scaling.
e.g.
```
mlab_source.dataset.point_data.vectors
mlab_source.dataset.point_data.scalars
mlab_source.scalars
```
Thanks!

**Comment by jonathanrocher** [comment]
@solarjoe For future discussions, you may consider the Mayavi mailing list (mayavi-users@lists.sf.net) . Also, FYI, last weekend during the SciPy2017 sprint, we created a new mailing list for Enthought Tool Suite packages in general so you might also consider joining https://groups.google.com/forum/#!forum/ets-users .
