### ISSUE TITLE
Multiple pick callbacks seem to be broken

### ISSUE THREAD

**Issue by bcorfman** [enthought/mayavi#549]
I have some code where I set up two separate callbacks, one to show detail for 3D points on a scene and the other to select cells in a RectilinearGrid. I added both callbacks, e.g.,

`   cell_picker = figure.on_mouse_pick(cell_picker_callback, type='cell')`
`   point_picker = figure.on_mouse_pick(point_picker_callback, type='point')`

These callbacks both get added to the _active_pickers inside the MousePickDispatcher class, but inside the on_pick method of the same class, there is a break statement at the end of the method that seems to be at the wrong indentation level, and only allows one of the events to fire. Is there a reason for this, or is it just an unintended mistake? Thanks.

**Comment by FedeMiorelli** [comment]
This was fixed in PR https://github.com/enthought/mayavi/pull/507 so it works if you use the master branch.
