### ISSUE TITLE
State of mayavi/ support for vtk8, qt5?

### ISSUE THREAD

**Issue by cwerner** [enthought/mayavi#551]
Hi all.

Not sure if this is the right channel (feel free to close or direct me to the proper location, however the mailing list seems to be dead?), but I recently started using mayavi for plotting some stuff into PNG files.
I had things running 6 months ago on a different machine (after days of compiling and recompiling things), but settings up the environment is/ was major pain and now I cannot get things going anymore at all..

I was just wondering what the status of mayavi is? I'm on macOS using homebrew and things are not smooth here...

- default VTK there is vtk8.0.1 (but this is not compatible right?)
- the backend is still qt4 (homebrew moved to Qt5, too)
- using the wxpython backend freezes my script, too.

Anaconda is not an option for me at the moment unfortunately.
Will there be moves to support vtk8 and qt5 in the near future or should I look somewhere else? What would be my best option for getting things going on macOS? Compile everything from source?

Please don't take that as criticism, I just want to get a better understanding how things are and what to do...

Cheers

**Comment by jvkersch** [comment]
> the mailing list seems to be dead?

@chrwerner Not related to your specific query, but there is a new Google Group that serves the same purpose as the original mailing list at https://groups.google.com/forum/#!forum/ets-users

**Comment by chrwerner** [comment]
Thanks. I'll post my question over there...

**Comment by prabhuramachandran** [comment]
@chrwerner -- sorry for being slow to respond, I have been very busy for the last few weeks.  To keep things short, Mayavi from master (on this repository) should work with 8.0 (not sure I tested with 8.1) and should also work with Qt5.  I finished the port this summer here: https://github.com/enthought/mayavi/pull/528  you will also need the latest versions of traitsui. pyface etc.  So as soon as those are all released we should be able to cut a release for Mayavi as well.  There are many more issues I do need to address though.  You will need to set ETS_TOOLKIT=qt4 and set QT_API=pyqt5 to have this work though.  HTH.

**Comment by chrwerner** [comment]
@prabhuramachandran Thanks. I now have a cutting-edge system ;-). Old script works (with offline rendering to PNG), but whenever I try to run anything (examples) that plots to screen I get a black window and if files are saved they are grey...
Is there anything I could do here?
I'm on MacOSX 10.13

**Comment by patricksnape** [comment]
Any estimate of when a new release might be made?

**Comment by raphmur** [comment]
bump

Great work

Can we get a release soon to try and integrate this new version in conda-forge?

**Comment by adeak** [comment]
Should this issue still be open? Mayavi seems to work with VTK 8 and qt5 now (my specific installation shows the weird bug https://github.com/enthought/mayavi/issues/656 but from the comments this seems to be a bug in something other than mayavi).

**Comment by prabhuramachandran** [comment]
@patricksnape -- 4.6.1 was released on 6th July, 2018.
@adeak -- yes I think this should really be closed, thanks.  If there is a specific mayavi specific issue, you could always open a new issue.  Thanks!
