### ISSUE TITLE
mlab.init_notebook ignores the `local` parameter

### ISSUE THREAD

**Issue by gdlmx** [enthought/mayavi#553]
https://github.com/enthought/mayavi/blob/9730c320a8f52764a03210e9f3f376e547944077/mayavi/tools/notebook.py#L30

The `local` parameter of the `mayavi.mlab.init_notebook` function has no effect due to a missing `global` declaration inside `mayavi/tools/notebook.py`:

```python
def init(backend='x3d', width=None, height=None, local=True):
"""Initialize a suitable backend for Jupyter notebooks."""
    global _backend, _width, _height # _local is missing here
    ...
    _local = local
```
## To reproduce the problem

Open a new notebook in Jupyter

```python
from mayavi import mlab
mlab.init_notebook(local=False)
import mayavi.tools.notebook as nb
nb._local
## True (False is expected here)
## If the "x3dom.js" is not available from the Jupyter server, all `x3d` elements cannot be rendered.
```
If inspected using the browser's debug tool, the javascript begins with:
```javascript
require(["nbextension/..."], ...);
```
, instead of,
```javascript
require(["https://www.x3dom.org/download/1.7.2/x3dom"]
```

**Comment by prabhuramachandran** [comment]
Yes indeed, I will fix this soon.  Thanks for the bug report.
