### ISSUE TITLE
plot3d issue：how can I update my data which are in different length in every iteration step?

### ISSUE THREAD

**Issue by vonlippmann** [enthought/mayavi#592]
I want to use plot3d to show my convergence curve in every iteration step when computing. My scheme is initialize the plot with only one point at position (0.0 ,0.0, 0.0), and after each iteration i can got an new point , but when i use function  mlab_source.set(x = my_new_list , y =... , z= ....) to update my data , it will raise error ,and reminders me that i have set the initial length = 0 ,so it cannot use three new lists with different length to replace the origin data. 
Does there have any other function can realize my request? or can i embed matplotlib module in mayavi scene , so i can plot all kinds of curves to trace  the computing process and show not only 3D picture but also 2D curves?

**Comment by prabhuramachandran** [comment]
Use `mlab_source.reset(...)`.   This is discussed here: http://docs.enthought.com/mayavi/mayavi/mlab_animating.html?highlight=reset

Also for these sort of questions please use one of the mailing lists and not the issues page, thanks.  https://github.com/enthought/mayavi#bug-tracker-mailing-list-etc

**Comment by vonlippmann** [comment]
Thank you so much . Please forgive me , I am a newer of github ,and i mistunderstand the function of  issues page. Thank you again.

**Comment by prabhuramachandran** [comment]
@vonlippmann -- not a problem at all, the issues page is to report what you think are bugs or problems with anything.  Enjoy!
