### ISSUE TITLE
mayavi rendering in quarter of the window

### ISSUE THREAD

**Issue by satra** [enthought/mayavi#593]
i can't figure out how to make this take the entire window.

![image](https://user-images.githubusercontent.com/184063/35491578-473c55f0-0475-11e8-8c75-a820bf33a1b1.png)

code:
```python
from mayavi import mlab
fig = mlab.figure(1)
mlab.clf()
for i, f in enumerate(files):
    objsource = mlab.pipeline.open(f)
    if opacity[i] is not None:
        surf = mlab.pipeline.surface(objsource, opacity=opacity[i],
                                     color=tuple(np.random.rand(1, 3)[0]))
        if i==3:
            surf.actor.mapper.scalar_visibility = True
    else:
        surf = mlab.pipeline.surface(objsource,
                                     color=tuple(np.random.rand(1, 3)[0]))
```

environment:
osx 10.12
pyface, traitsui, mayavi from github master - had to reinstall pyface, traitsui after mayavi 
python 3
pyqt5
i'm running inside jupyter notebook but rendering outside the browser.

**Comment by prabhuramachandran** [comment]
Hi @satra! This is an issue with your version of VTK.  If you use 8.x this will work fine, see #528 where I mention this. I think it has to do with retina displays, Qt5, and VTK.

**Comment by satra** [comment]
@prabhuramachandran - thanks - i'm using 7.1 right now. i'll see if i can install 8.x without too much trouble :)

**Comment by prabhuramachandran** [comment]
@satra -- I've pushed new VTK 8.1.0 wheels on pypi.  You should be able to pip install vtk now. :)  See here: http://prabhuramachandran.blogspot.in/2018/01/vtk-810-wheels-for-all-platforms-on-pypi.html

**Comment by satra** [comment]
@prabhuramachandran - works beautifully with VTK 8.1 (thanks for the wheels).

**Comment by prabhuramachandran** [comment]
@satra -- great to hear! :)

**Comment by prabhuramachandran** [comment]
To be honest, I haven't fully tested Mayavi on VTK-8.1, that is next (perhaps this weekend).
