### ISSUE TITLE
Plot size and window size mismatch 

### ISSUE THREAD

**Issue by ktavabi** [enthought/mayavi#598]
Why is this happening? 

<img width="408" alt="screen shot 2018-02-06 at 10 36 32 am" src="https://user-images.githubusercontent.com/4381290/35877231-a158c18a-0b29-11e8-9d15-629828ecc452.png">

```
from mayavi import mlab
%gui qt
mlab.test_plot3d()
```

> 
> Platform:      Darwin-17.4.0-x86_64-i386-64bit
> Python:        3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:04:09)  [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
> Executable:    /Users/ktavabi/miniconda3/envs/mne3/bin/python
> CPU:           i386: 8 cores
> Memory:        16.0 GB
> mne:           0.16.dev0
> numpy:         1.13.3 {blas=mkl_rt, lapack=mkl_rt}
> scipy:         1.0.0
> matplotlib:    2.1.0
> sklearn:       0.19.1
> nibabel:       2.2.0
> mayavi:        4.5.1.dev0
> pycuda:        Not found
> skcuda:        Not found
> pandas:        0.21.0

**Comment by prabhuramachandran** [comment]
Repeat of this: https://github.com/enthought/mayavi/issues/593 and the solution is there.  Use the latest VTK wheels and Mayavi from master.

**Comment by ktavabi** [comment]
@prabhuramachandran that seems to resolve with the exception of 

> 
> WARNING: Imported VTK version (8.1) does not match the one used
>          to build the TVTK classes (7.1). This may cause problems.
>          Please rebuild TVTK.

`conda list | grep vtk` returns 

> vtk 8.1.0 <pip>
> vtk 7.1.0 py36_3    clinicalgraphics

Should I remove with `pip uninstall vtk` and reinstall with `pip install vtk`?

**Comment by prabhuramachandran** [comment]
You need to re-install Mayavi after you install vtk.  I would suggest that you uninstall the conda version of mayavi and then you can remove the conda version of vtk with whatever conda command.  Then do `pip install vtk` and thereafter install mayavi from the version on github.
