### ISSUE TITLE
class ImageChangeInformation has no update_extent

### ISSUE THREAD

**Issue by voodoogit** [enthought/mayavi#600]
Hello,

in the file: [mayavi/sources/array_source.py](https://github.com/enthought/mayavi/blob/master/mayavi/sources/array_source.py), the `class ImageChangeInformation` is called with the attribute` update_extent`. This attribute does not exist in the file [mayavi/filter/image_change_information.py](https://github.com/enthought/mayavi/blob/master/mayavi/filters/image_change_information.py), thus raising an error. We fixed the error by commenting out the line no. 197 in [array_source.py](https://github.com/enthought/mayavi/blob/master/mayavi/sources/array_source.py). Hopefully, we don't encounter other weird behaviour in the future by doing this.

We discovered this issue because we had a lot of trouble plotting most of the [examples from the mlab docs](http://docs.enthought.com/mayavi/mayavi/mlab.html) and the error messages that showed up were often ambigous. 

I am by no means an experienced programmer so please excuse me if I got technical terms wrong.

**Comment by prabhuramachandran** [comment]
What version of VTK is this?  If this is 8.x then the code in master is correct as update_extent is no longer available in newer VTK versions?  This is also already fixed.  For older versions this does seem necessary.

**Comment by voodoogit** [comment]
`pip2.7 search vtk` revealed that I have installed version `8.1.0`

**Comment by prabhuramachandran** [comment]
Well, OK in which case are you running Mayavi from git master or the last release?  It looks like you are running it from either a release or an older version.  If you install Mayavi from git you should not run into this.  Thank you for reporting the matter though. Am closing this for now please reopen if it persists.
