### ISSUE TITLE
When ETS will suport PyQt5?

### ISSUE THREAD

**Issue by vonlippmann** [enthought/mayavi#603]

**Comment by vonlippmann** [comment]
Qt company no longer support PyQt4,  So When ETS will upgrade to support PyQt5?

**Comment by prabhuramachandran** [comment]
Already does but not as part of a release on PyPI which is coming soon, next couple of weeks hopefully.

**Comment by prabhuramachandran** [comment]
Closing as this is not really an issue per se currently.
