### ISSUE TITLE
PDF export causes random red splotch on surface

### ISSUE THREAD

**Issue by notmatthancock** [enthought/mayavi#604]
The following code creates a triangular mesh of a sphere:
```
import numpy as np
from skimage.measure import marching_cubes
import matplotlib.pyplot as plt
from mayavi import mlab


# Create a 3D scalar field whose level sets are spheres.
xyz = np.indices((71,71,71), dtype=np.float)
s = np.linalg.norm(xyz-35, axis=0)

verts, faces, _, _ = marching_cubes(s, 30, step_size=6)
x,y,z = verts.T

mlab.figure(size=(600,600))
surf = mlab.triangular_mesh(x,y,z,faces,colormap='viridis')
mlab.show()
```

When I save a snapshot as PNG, I get 

![snapshot](https://user-images.githubusercontent.com/1588456/36236841-6983f6a0-11c6-11e8-9e23-36893328c83f.png)

However, when I save the snapshot as PDF, a red splotch on the surface appears:

[snapshot.pdf](https://github.com/enthought/mayavi/files/1726153/snapshot.pdf)

This has to do with lighting I think since if I add

```
surf.actor.property.lighting = False                                            
surf.actor.property.interpolation = 'flat'
```
Then the resulting PDF has no red splotch.

Other color schemes cause similar wackiness on PDF export. 

EPS export is fine, but the resulting file size is 536KB vs 148KB for the PDF file. SVG also produces the correct output, but the filesize balloons to 1.5MB.

---

Versions info:

VTK: 5.10.1
Mayavi: 4.5.0
Python: 2.7.12
OS: Ubuntu 16.04

**Comment by prabhuramachandran** [comment]
This is a super old version of VTK.  This works fine for me with VTK-8.1, Mayavi master and Python 3.6 on OSX.

**Comment by prabhuramachandran** [comment]
Closing for now, please comment if this occurs with a more recent installation.

**Comment by notmatthancock** [comment]
The available versions of vtk on Ubuntu under `apt` are `5.1` and `6.2`. I upgraded to 6.2, and after [installing and using wx instead of qt](https://github.com/enthought/mayavi/issues/450), I found that the red splotch is still there on PDF export.

I'm not in the mood to build VTK 8 from source, so I will just take your word that it is fixed in this version :)

**Comment by prabhuramachandran** [comment]
You don't need to build from source, you can pip install VTK. :)

**Comment by notmatthancock** [comment]
Thanks, I wasn't aware of that. After upgrading to VTK 8 via pip, I ran into another [issue](https://github.com/enthought/mayavi/issues/615). I went bleeding edge via [ETS](https://github.com/enthought/ets), and it all works fine now, including the original red splotch issue of this thread.
