### ISSUE TITLE
Is there a method for saving multiple surfaces into one output?

### ISSUE THREAD

**Issue by ibrahimshibani** [enthought/mayavi#606]
Right now, I can only export each surface as a seperate file : 
`mesh = mlab.triangular_mesh(x, y, z, triangles,resolution=20)#,colormap='PuBuGn')`
 `mesh.module_manager.source.save_output('test.vtp')`

` s_1 = mlab.plot3d(xG[0:1000],yG[0:1000],zG[0:1000], color(1,0,0), line_width=0.4, tube_radius=0.014, tube_sides=20)`
` s_1.module_manager.source.save_output('test1.vtp')`

```
mlab.draw()
mlab.show()
```

Is it possible to output all the contents of the figure into one file? 
Thanks

**Comment by prabhuramachandran** [comment]
You cannot do this as is, you will need to use VTK to do this.  You could use something like this (untested):
```
from tvtk.api import tvtk, write_data
ap = tvtk.AppendPolyData()
ap.add_input_data(mesh.module_manager.source.outputs[0])
ap.add_input_data(s_1.module_manager.source.outputs[0])
ap.update()
write_data(ap.get_output_data_object(0), 'output.vtp')
```
