### ISSUE TITLE
TypeError: GetPixelData argument 6

### ISSUE THREAD

**Issue by ktavabi** [enthought/mayavi#610]
Does this mean anything to anyone?
>   File ".../miniconda3/envs/mne3/lib/python3.6/site-packages/mayavi/tools/figure.py", line 330, in screenshot
>     pixel_getter(*pg_args)
>   File "tvtk_classes/render_window.py", line 360, in get_pixel_data
>   File ".../miniconda3/envs/mne3/lib/python3.6/site-packages/tvtk/tvtk_base.py", line 569, in _wrap_call
>     ret = vtk_method(*args)
> TypeError: GetPixelData argument 6: an integer is required (got type vtkCommonCorePython.vtkUnsignedCharArray)

> Platform:      Linux-4.4.0-112-generic-x86_64-with-debian-stretch-sid
> Python:        3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:09:58)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
> Executable:    .../miniconda3/envs/mne3/bin/python
> CPU:           x86_64: 24 cores
> Memory:        94.4 GB
> mne:           0.16.dev0
> numpy:         1.13.3 {blas=mkl_rt, lapack=mkl_rt}
> scipy:         1.0.0
> matplotlib:    2.0.2
> sklearn:       0.19.1
> nibabel:       2.2.0
> mayavi:        4.5.1.dev0
> pycuda:        2017.1.1
> skcuda:        0.5.1
> pandas:        0.22.0
> vtk:              8.1.0

**Comment by prabhuramachandran** [comment]
I've fixed this in #609 merged last night, please update and try.
