### ISSUE TITLE
Can‘t  creat movie 

### ISSUE THREAD

**Issue by vonlippmann** [enthought/mayavi#612]
I tried the method mentioned in online help documents:
![g8884y pg7 1v6 z9g 5 n](https://user-images.githubusercontent.com/25638200/36881979-2652f94c-1e0c-11e8-973b-b673cd8e2596.png)
and  i set my mayavi scene as follows:
![doxn 1 i9i1 5xd1 z fc](https://user-images.githubusercontent.com/25638200/36881984-3829d67c-1e0c-11e8-8c1c-8104a8d14c23.png)
but I got nothing in the directory!
I don't know what's wrong with it .

**Comment by prabhuramachandran** [comment]
This works for me. You will need to update to the latest Mayavi version I suspect.  If this still happens, please reopen this issue or comment on it. Thanks.

**Comment by vonlippmann** [comment]
I download the mater branches .After i run setup.py , a new folder appeared in my anoconda site-packages as follows: 
![m6c66lob53efi jr 1sdq w](https://user-images.githubusercontent.com/25638200/36956747-f95e671c-206a-11e8-887c-2ce6251baba3.png)
and then i copied the mayavi and tvtk folder to the site-packages ,and i tested the version as follows:
![43m6 kzq y hl65d43 0s0](https://user-images.githubusercontent.com/25638200/36956790-40d63840-206b-11e8-817d-d4287e2c759f.png)
But when i run my program an error occured:
![z04ixl2kj dg4oc cu 416k](https://user-images.githubusercontent.com/25638200/36956815-6e8fbf04-206b-11e8-8f65-ea19dbd1cb26.png)
i cann't boot my app now.
Is there something wrong with dependent packages?
In my python environment ,there are VTK 8.1, PyQt4, traits.
For the latest version of mayavi ,what's the required packages and their version ? I suspect there are something wrong with the dependent packages

**Comment by prabhuramachandran** [comment]
Thanks for reporting this.  Is this pyqt4 or 5?  I did not realize pyqt4  works on python 3.6!

**Comment by vonlippmann** [comment]
My environment is python 3.6.3  and pyqt4 , because mayavi don't support pyqt5.
When i use mayavi 4.5.0 ,pyqt4 really works on python 3.6.3 ,but i just can not save figs and make movie.

**Comment by prabhuramachandran** [comment]
Well, Mayavi does work with PyQt5 also if you use it from master but anyway I will look into this and fix the issue.

**Comment by vonlippmann** [comment]
OK , i will set up a new python environment , and install all relevant packages. Then try it again ,if that works i will comment on it , Many thanks for your help

**Comment by prabhuramachandran** [comment]
@vonlippmann -- can you update to latest master and see if this no longer happens?  Thanks.

**Comment by vonlippmann** [comment]
I updated to the lastest master and i did not work .
I have fixed this problem by delete line 466 in tvtk\pyface\tvtk_scene.py to save png fig in everry iteration ,and then to make gif by ffmpeg.
And i find my  program works in  PyQt4.11 but raise error in PyQt4.12 .
I download canopy , it indeed can save fig ,but my program will crash.
So i think the may reason is the version of PyQt4

**Comment by prabhuramachandran** [comment]
Can you please send me the specific errors you are getting?  I'd like this fixed if it is an issue in Mayavi.

**Comment by prabhuramachandran** [comment]
I guess you do not have the latest version then as line 466 is an empty line in master!

https://github.com/enthought/mayavi/blob/master/tvtk/pyface/tvtk_scene.py#L466

**Comment by vonlippmann** [comment]
I tried the master branches of which the version is '4.5.1.dev0'  , but i can not even boot my app. so i can not test whether i can save png fig and make movies. the errror information is mention before. 
If i use '4.5.1.dev0' , which PyQt4  (4.11 or 4.12 or both is OK) edition should i use?

**Comment by vonlippmann** [comment]
I just download the master branch and the version is indeed 4.5.1.dev0 , but this time it can save figs ,but still can not make movie , and there is a bug in the UI as follows:
![tim 20180307163056](https://user-images.githubusercontent.com/25638200/37081806-8ca9d3d8-2225-11e8-8221-beed803d639e.png)
there is nothing in Lut mode .
So i just use mayavi 4.5.0 and  fix some unkown bugs by myself  , If mayavi release new vertion ,i will then update it .
Many thanks

**Comment by prabhuramachandran** [comment]
OK, good that Mayavi is now running and you don't get that recursion error.  This particular issue (not seeing the images) is not a Mayavi issue but a traitsui/pyface issue  -- notice that the menubar is not there and there are no images in the tree either unless of course the tree is not Mayavi's but your own.  Are you using pyface/traitsui from their respective masters?  Anyway, there will be a public release of all the relevant projects in a short while there are still a few issues in traitsui with Qt5.  @corranwebster -- is the above a known issue in traitsui?  
As regards the movie, without a reproducible example it is impossible for me to fix the issue. Error messages or a log will help me debug errors.  The original example you cited above works fine for me on OSX, Python 3.6 with PyQt5, VTK 8.1 and Mayavi from master as does it with Python 2.7 and PySide.

**Comment by vonlippmann** [comment]
I didn't use traitui from their respective masters. Maybe everything will work fine ,if all the packages--traits,traitsui, mayavi--is the latest version. When you release the latest version ,i will update them right away,
expect your release!
