### ISSUE TITLE
'NoneType' object is not callable

### ISSUE THREAD

**Issue by vonlippmann** [enthought/mayavi#614]
I want to convert an optimization result formated by .vtu to STL format file. And  have following codes:
![tpesusto5nn y cycbpwodt](https://user-images.githubusercontent.com/25638200/36932718-67314340-1f08-11e8-9e48-28452e413b6a.png)
but an error occured as follows:
![image](https://user-images.githubusercontent.com/25638200/36932734-9cae6110-1f08-11e8-8454-3ed9607824a5.png)
I also tried XMLUnstructuredGridReader ,but it will generate the same error.
this is my vtu file:
 
[L_shape.zip](https://github.com/enthought/mayavi/files/1777329/L_shape.zip)
Is there something wrong with my vtu file or i just find the wrong api?

**Comment by prabhuramachandran** [comment]
Basic Python error, `reader.file_name` is not a callable but a trait, try:
```
reader.file_name = "your path here"
```
