### ISSUE TITLE
Cannot set the undefined 'magnification' attribute of a 'WindowToImageFilter' object.

### ISSUE THREAD

**Issue by vonlippmann** [enthought/mayavi#615]
I want to save a picture ,when i click the save fig button and choosed the path ,and click save ,an error occured, :
![cxo_7y5 4 r3rp5xsf4cf3](https://user-images.githubusercontent.com/25638200/36941726-2981fd2e-1f9d-11e8-95ab-f2d75589abed.png)
Also when i checked record item in movie_ maker UI , and then animate my results , i got nothing in the specified path, but there is no error occured.

**Comment by prabhuramachandran** [comment]
Fixed in #597.  Please pull from master and try again.  Your other issues may also be related.
