### ISSUE TITLE
BadWindow (invalid Window parameter)

### ISSUE THREAD

**Issue by arinbjornk** [enthought/mayavi#621]
Ubuntu 16.04
vtk 8.1.0
mayavi 4.5.0 (installed after vtk using pip)

Trying to plot a simple demo:

```
from mayavi import mlab
import numpy as np

a = np.random.random((4, 4))
mlab.surf(a)
```

Results in the error:
```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  10 (X_UnmapWindow)
  Resource id in failed request:  0x3000014
  Serial number of failed request:  60
  Current serial number in output stream:  62
```

**Comment by prabhuramachandran** [comment]
Are you using Mayavi from master?  You will need the latest Mayavi from github.  I am waiting for a couple of other packages to be released before I release a new version of Mayavi.  What version of Python are you using?

**Comment by arinbjornk** [comment]
Thanks for the fast reply. I have just updated to the latest on gihub, still get the same error. All of this is in python 2.7.

I do see the window outline appear for a split second before it closes.

**Comment by prabhuramachandran** [comment]
What UI toolkit are you using?  Qt or wxPython, which versions of these?

**Comment by arinbjornk** [comment]
wxPython 4.0.1

Would it be possible for me to bypass the UI and window generation by directly saving the image to a png/svg file?

**Comment by prabhuramachandran** [comment]
Technically wxPython 4.0.1 should work with master, it did for me on OS X but traitsui will not work at all.  However, I am not sure if you ran your code on an IPython session or if you wrote a script and ran it as `python script.py`?  Put this code in a script 
```
from mayavi import mlab
import numpy as np

a = np.random.random((4, 4))
mlab.surf(a)
mlab.show()
```
Does this work at all?

As regards bypassing the UI, yes you can, you can do:

```
mlab.options.offscreen = True
```
before you run any mlab commands and then do an `mlab.savefig(...)` and it should work. You could also do this on an ipython notebook (see http://docs.enthought.com/mayavi/mayavi/tips.html#using-mayavi-in-jupyter-notebooks).

**Comment by arinbjornk** [comment]
`mlab.show()` fixed it. It's all working now.

I was running the previous code in a regular python script too, just forgot to use show()

Many thanks for the help

**Comment by prabhuramachandran** [comment]
OK great.

**Comment by mattschaff** [comment]
Ubuntu 16.04
VTK 8.1.0
Mayavi 4.5.0
pysurfer 0.8.0

Hi. I'm encountering the same issue here, except in implementing mayavi through pysurfer (https://pysurfer.github.io). Testing basic functionality with arinbjornk's mini script, I get the same error, unless I add mlab.show() at the end. Pysurfer makes a lot of calls to mlab through its "Brain" class (https://github.com/nipy/PySurfer/blob/master/surfer/viz.py) ... do you know what could be going wrong?

Thanks for your help.

**Comment by xinsuinizhuan** [comment]
How about this issure? I meet it, also. Ubuntu Qt5.13.2：
Error in X: BadMatch (invalid parameter attributes)
XRequest MajorCode 1: X_CreateWindow
error->resourceid = 0x4a00031
XRequest MinorCode = 0: 
ErrorSerial = 1686
CurrentSerial = #1695
Error in X: BadWindow (invalid Window parameter)
XRequest MajorCode 18: 
X_ChangeProperty
ResourceID = 0x4e000f3
XRequest MinorCode = 0: 
ErrorSerial = 1687
CurrentSerial = #1695
Error in X: BadWindow (invalid Window parameter)
how to fixed it?
