### ISSUE TITLE
BUG: Build on Windows locks up on latest PyQt5

### ISSUE THREAD

**Issue by larsoner** [enthought/mayavi#624]
It looks like this is a known issue:

https://ci.appveyor.com/project/mne-tools/mne-python/build/1.0.2189

And the workaround is to pin 5.9.2?

https://github.com/enthought/mayavi/commit/63820fd14b3b4916819c5a179deacca429a241b3

**Comment by prabhuramachandran** [comment]
Yes, this seems like a broken pyqt build?  Closing as this isn't really a Mayavi issue.
