### ISSUE TITLE
Pyface and TraitsUI accept "qt" as a synonym for "qt4"

### ISSUE THREAD

**Issue by corranwebster** [enthought/mayavi#626]
We now allow "qt" as a synonym for `ETSConfig.toolkit` being set to `qt4` in Pyface and TraitsUI.  Allowing for Mayavi would be good; may require revisiting toolkit code in Mayavi, possibly to use `pkg_resources` extension points.

**Comment by prabhuramachandran** [comment]
Thanks! What does this entail, is there a place I should look for how to do this correctly?  I know I can dig around and look but it would help if you could tell me where specifically so I don't make a mess.
