### ISSUE TITLE
BUG: SetAAFrames (anti_aliasing_frames) is deprecated

### ISSUE THREAD

**Issue by larsoner** [enthought/mayavi#634]
In my CircleCI builds with VTK8.1 I see a lot of these:
```
Generic Warning: In ../Rendering/Core/vtkRenderWindow.cxx, line 1492
vtkRenderWindow::SetAAFrames was deprecated for VTK 8.1 and will be removed in a future version.
```
I see in `tvtk` and `mayavi` this ends up in `anti_aliasing_frames`. Perhaps `mayavi` should `warn` about deprecation of this feature for a release (4.5.?), then remove `figure.scene.anti_aliasing_frames` (and related option in `screenshot`) in a subsequent release (4.6?)? If so I can try adding such a warning.

My CircleCI workflow only ever uses `mlab.savefig`, which I don't *think* should be setting this parameter, so I'm also not entirely sure why I see this warning.

**Comment by prabhuramachandran** [comment]
Doesn't seem like a Mayavi issue.  `anti_aliasing_frames` is a Mayavi specific trait, the VTK trait is `aa_frames` which depends on the VTK version.  The `aa_frames` is set by version specific code, so I am not sure where this warning is showing up from?

**Comment by larsoner** [comment]
That makes sense, I can't replicate on VTK 8.1 locally. Perhaps there is something strange about the CircleCI job, which runs through Xvfb / MESA rendering.
