### ISSUE TITLE
Installation Problems of Mayavi

### ISSUE THREAD

**Issue by Kekushke** [enthought/mayavi#636]
Mayavi2 is just **TRULY** awesome in terms of capabilities. However, this is a general issue... and I have huge trouble every time I want to install `mayavi` in `ubuntu` inside `virtualenv` or on the core system.  It is just not a clean 'pip' install even after  all `vtk` etc. dependencies are installed in core. Dependencies and options are just too many and too varied. Many packages it requires are not identified automatically. Countless people have seen these problem - and every-time I have to go looking for solutions online. May be I am doing something wrong... but this has **always**  been the case. May be `mayavi` should think about just limiting the backend options to just a few but have it all really cleanly install-able and easily usable without problems.  Will it ever be possible to ever install `mayavi` with just a simple command `pip install mayavi` and work completely ready out-of-box without any errors? I will be glad to help the owners in development.  I understand `vtk` etc. dependencies, however looks like it is now available through `pip`.

After single `pip` install, all options could be simply controllable via environmental variable... For example, Use of `mesa` or `xvfb`. One install should do everything, possibly; and everything else should be controllable via a simple `.mayavi `startup file or environment variables.  There may be just multiple copies of the libraries which are differently compiled under their respective trees... or an option to do so by the user.

`mayavi` does super heavy-duty lifting, but the true glory will be even greater in super easy install.  Not the only option... but `pip` may be the best way to do this well and completely.

**Comment by Kekushke** [comment]
For example, brand new  install and now I see this... 

```
$ array_handler.py:268: FutureWarning: Conversion of the second argument of issubdtype from `complex` to `np.complexfloating` is deprecated. In future, it will be treated as `np.complex128 == np.dtype(complex).type`.
  assert not numpy.issubdtype(z.dtype, complex), \
QVariantMap DBusMenuExporterDBus::getProperties(int, const QStringList&) const: Condition failed: action 
```

**Comment by Kekushke** [comment]
For example, a fresh install and I see these errors:
`QVariantMap DBusMenuExporterDBus::getProperties(int, const QStringList&) const: Condition failed: 
action 
`

**Comment by prabhuramachandran** [comment]
@Kekushke -- I am working on this and I was the one who pushed the VTK wheels to PyPI. Some of your errors are because you are using the last released version of Mayavi.  pip install will not work as I need time to make a release.  Unfortunately, I have a problem this weekend which has meant staying away from my computer and over the rest of the week, end semester work.  I was hoping to release mayavi this weekend or the next but I am afraid it is going to have to wait until I feel better and I am able to get some time.  I am hoping by next weekend to have a release.

**Comment by Kekushke** [comment]
Prof. @prabhuramachandran Thank you so much for your comments. Hope you feel better soon. No hurry at all. I just wanted to point of users' perspective and experience; hoping to help. This is an **awesome** **awesome** tool - and as the user experience gets better this is going to be here for another 10-, 25-years and beyond!  

It is amazing that you can do so much with `mayavi` and there are just numerous options... and I think latter has added too much complexity, but may be there are ways to simplify things so that it is easy to choose those options with ultra-simple installation process .  I will be glad to help test/write docs/tutorials and simplify things if you wish.

Thanks again!

**Comment by prabhuramachandran** [comment]
@Kekushke -- please don't call me Prof., I understand your pain and am trying to make things a bit easier to install.  Thank you for your kind words and encouragement.  I also have other tools I have been maintaining and perhaps I have bitten off more than I can chew!  Any help is welcome. I think if I just push a new Mayavi release, Mayavi will be fully pip installable which will help loads.  Hopefully by the coming weekend.

**Comment by Kekushke** [comment]
@prabhuramachandran No problem!  Looking at the history of `mayavi`, I figured you are the creator!  Really awesome!

**Comment by erbas** [comment]
@prabhuramachandran Mayavi is awesome! I am trying to animate some quantum dynamics simulations and this is the only tool I know which will let me do what I want, so thank you. But I have to ask, why is the dependency tree such a nightmare? I've been trying for a day and half to get it working on my new MacBook Pro and the sequence of errors is unbelievable. It probably doesn't help that this issue has existed for several years and so I keep finding out of date advice, but honestly, this is not sustainable.

**Comment by prabhuramachandran** [comment]
I understand but the following steps should suffice on the three major platforms (Python 3.x), even without recourse to :

```
pip install vtk traits traitsui pyface envisage apptools pyqt5
git clone https://github.com/enthought/mayavi.git
cd mayavi
python setup.py install
```
In a few days I hope to push a new release and that should make it possible to simply do a `pip install mayavi`.

**Comment by erbas** [comment]
Thank you, that actually worked! You should put these clear instructions in the README

**Comment by prabhuramachandran** [comment]
I think this issue is now resolved so closing.  Thanks for your patience.

**Comment by Atulsingh92** [comment]
Not sure if this is the way to open it again , but pip install mayavi still hangs!
