### ISSUE TITLE
Charmap cannot encode character when running pip install mayavi

### ISSUE THREAD

**Issue by MaxKrapp** [enthought/mayavi#639]
When I try to install mayavi via pip install mayavi I get an error:

\appdata\local\programs\python\python35\lib\encodings\cp1252.py", line 19, in encode
      return codecs.charmap_encode(input,self.errors,encoding_table)[0]
  UnicodeEncodeError: 'charmap' codec can't encode character '\u2264' in position 3665: character maps to <undefined>

This encodes a less equal sign and cant be resolved. Is this a known issue and how can it be solved? thanks in advance

**Comment by prabhuramachandran** [comment]
This is not enough information for me to go on as the error seems to have nothing to do with Mayavi.  The tests are running on Python 2 and 3 and I am using it all the time with Python3 now.  Please share the full traceback.

**Comment by MaxKrapp** [comment]
Cloned the git repo, used python setup.py build and python setup.py install without any errors. How can I test if mayavi is running. Should I clone the build in my sitepackages folder or is this done by the setup automatically?

**Comment by MaxKrapp** [comment]
Was able to import mayavi and included it into my python path. I ran the example and got the following error raised (is this because the code is not compatible anymore or is something wrong with my build?):


`# Create the data.
from numpy import pi, sin, cos, mgrid
dphi, dtheta = pi/250.0, pi/250.0
[phi,theta] = mgrid[0:pi+dphi*1.5:dphi,0:2*pi+dtheta*1.5:dtheta]
m0 = 4; m1 = 3; m2 = 2; m3 = 3; m4 = 6; m5 = 2; m6 = 6; m7 = 4;
r = sin(m0*phi)**m1 + cos(m2*phi)**m3 + sin(m4*theta)**m5 + cos(m6*theta)**m7
x = r*sin(phi)*cos(theta)
y = r*cos(phi)
z = r*sin(phi)*sin(theta)

# View it.
from mayavi import mlab
s = mlab.mesh(x, y, z)
mlab.show()` 

> Traceback (most recent call last):
>   File "C:\Users\Inveox Employee\eclipse-workspace\Inveox\Testing.py", line 68, in <module>
>     from mayavi import mlab
>   File "C:\Users\Inveox Employee\AppData\Local\Programs\Python\Python35\lib\site-packages\mayavi-4.5.1.dev0-py3.5-win-amd64.egg\mayavi\mlab.py", line 27, in <module>
>     from mayavi.tools.camera import view, roll, yaw, pitch, move
>   File "C:\Users\Inveox Employee\AppData\Local\Programs\Python\Python35\lib\site-packages\mayavi-4.5.1.dev0-py3.5-win-amd64.egg\mayavi\tools\camera.py", line 24, in <module>
>     from .engine_manager import get_engine
>   File "C:\Users\Inveox Employee\AppData\Local\Programs\Python\Python35\lib\site-packages\mayavi-4.5.1.dev0-py3.5-win-amd64.egg\mayavi\tools\engine_manager.py", line 14, in <module>
>     from mayavi.core.engine import Engine
>   File "C:\Users\Inveox Employee\AppData\Local\Programs\Python\Python35\lib\site-packages\mayavi-4.5.1.dev0-py3.5-win-amd64.egg\mayavi\core\engine.py", line 28, in <module>
>     from mayavi.core.base import Base
>   File "C:\Users\Inveox Employee\AppData\Local\Programs\Python\Python35\lib\site-packages\mayavi-4.5.1.dev0-py3.5-win-amd64.egg\mayavi\core\base.py", line 30, in <module>
>     from mayavi.core.common import get_engine
>   File "C:\Users\Inveox Employee\AppData\Local\Programs\Python\Python35\lib\site-packages\mayavi-4.5.1.dev0-py3.5-win-amd64.egg\mayavi\core\common.py", line 21, in <module>
>     from pyface import api as pyface
>   File "C:\Users\Inveox Employee\AppData\Local\Programs\Python\Python35\lib\site-packages\pyface\api.py", line 34, in <module>
>     from .python_editor import PythonEditor
>   File "C:\Users\Inveox Employee\AppData\Local\Programs\Python\Python35\lib\site-packages\pyface\python_editor.py", line 21, in <module>
>     PythonEditor = toolkit_object('python_editor:PythonEditor')
>   File "C:\Users\Inveox Employee\AppData\Local\Programs\Python\Python35\lib\site-packages\pyface\base_toolkit.py", line 144, in __call__
>     module = import_module(mname, package)
>   File "C:\Users\Inveox Employee\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "C:\Users\Inveox Employee\AppData\Local\Programs\Python\Python35\lib\site-packages\pyface\ui\qt4\python_editor.py", line 27, in <module>
>     from pyface.ui.qt4.code_editor.code_widget import AdvancedCodeWidget
>   File "C:\Users\Inveox Employee\AppData\Local\Programs\Python\Python35\lib\site-packages\pyface\ui\qt4\code_editor\code_widget.py", line 23, in <module>
>     from .pygments_highlighter import PygmentsHighlighter
>   File "C:\Users\Inveox Employee\AppData\Local\Programs\Python\Python35\lib\site-packages\pyface\ui\qt4\code_editor\pygments_highlighter.py", line 14, in <module>
>     from pygments.lexer import RegexLexer, _TokenType, Text, Error
> ImportError: No module named 'pygments'

**Comment by MaxKrapp** [comment]
Installed pygments with pip solved it. Maybe you can include it in your setup

**Comment by corranwebster** [comment]
Pygments is an optional dependency and is only required for the qt backends.  Possibly the best solution is an `extras_require` as we are now doing in Pyface and TraitsUI.

**Comment by prabhuramachandran** [comment]
I think it is an easy enough dependency to just add in to Mayavi?
