### ISSUE TITLE
VTK Errors when trying to run an animation

### ISSUE THREAD

**Issue by geajack** [enthought/mayavi#644]
I tried to run the following animation code, which I got off of a StackOverflow thread:

```
from mayavi import mlab
import numpy as np
import math

alpha = np.linspace(0, 2*math.pi, 100)  

xs = np.cos(alpha)
ys = np.sin(alpha)
zs = np.zeros_like(xs)

mlab.points3d(0,0,0)
plt = mlab.points3d(xs[:1], ys[:1], zs[:1])

@mlab.animate(delay=100)
def anim():
    while True:
        for (x, y, z) in zip(xs, ys, zs):
			plt.mlab_source.set(x=x, y=y, z=z)
			yield


anim()
mlab.show()
```

The animation comes up, but so does a window displaying a constant stream of the following error message:

```
ERROR: In C:\Minonda\conda-bld\work\VTK-6.3.0\Common\ExecutionModel\vtkExecutive.cxx, line 784
vtkCompositeDataPipeline (000000000D218990): Algorithm vtkAssignAttribute(00000000052BD210) returned failure for request: vtkInformation (000000000CFDF4D0)
  Debug: Off
  Modified Time: 1181153
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FORWARD_DIRECTION: 0
  ALGORITHM_AFTER_FORWARD: 1
```

PS: The documentation _really_ needs to be updated... the reason I had to go looking for demo code on StackOverflow is because the animation examples on the website simply don't work.

**Comment by prabhuramachandran** [comment]
I will take a look at the errors.  Also, which animation examples don't work?  I think they work, its just that they probably don't show as if they are "animated", but if your intent was to just dump a bunch of images, then they would all work.

**Comment by geajack** [comment]
I'm thinking of this page: http://docs.enthought.com/mayavi/mayavi/mlab_animating.html

Certainly if the code snippets are copy pasted into  python script they don't produce a useful result. The text of the page hints that we should try running mlab.test_simple_surf_anim(), which opens a window, but doesn't seem to produce any animation. More importantly, there's no indication of how to actually write your own animation, since following the pattern of the example code on that page (uploading mlab_source in a for loop, without calling mlab.show() or anything) obviously doesn't work.

**Comment by prabhuramachandran** [comment]
Did you try `mlab.test_simple_surf_anim`?  Did you look at the source of that example?  All of the `mlab` documentation is written with the general assumption that you are running things inside an IPython console with a GUI toolkit set (this is written right up at the top in red here: http://docs.enthought.com/mayavi/mayavi/mlab.html). 

When you say "running mlab.test_simple_surf_anim()" what did you do?  Did you run it as a Python script? In that case you need to add an `mlab.show()`.

If you see the code for the various animation examples, they all use a similar pattern:

https://github.com/enthought/mayavi/blob/master/mayavi/tools/helper_functions.py#L931

I'm happy to review and merge any PRs that folks send on improving the documentation.

**Comment by geajack** [comment]
Thank you for pointing me to the source code, but this is still nothing like what I need as a new user of the library. In order to understand mlab.test_simple_surf_anim() in that file, I need to understand mlab.test_points3d(). That calls points3d(), which is itself defined using document_pipeline, which makes various calls from one of the dozen imports at the top of the module. I can't even just copy paste this into my script since the imports are relative. 

On a page introducing the animation features of a library, the first thing I expect to see is a minimal working example that can be copy pasted into a script, to illustrate the basic ideas. I just don't see how an opaque test function from within the bowels of the library is a substitute for that, or for an actual high level conceptual explanation of the API. If generators and the @animate decorator are apparently such key parts of animation with mlab, why are neither of them mentioned in the documentation?

I'm running as a python script, yes. Maybe this is part of the problem.

**Comment by prabhuramachandran** [comment]
@geajack -- We cannot use `mlab.whatever` in the test functions as they are themselves made available via `mlab` leading to an import loop.  The test functions are useful when you are doing things with IPython and want a quick example, the changes to make to the function are small enough although I agree that you can't just cut/paste them and have them run.   There is a cut/pasteable example here though:

http://docs.enthought.com/mayavi/mayavi/tips.html#animating-a-visualization

I'll use the example you give above and put it there.  I've fixed the error message also and updated the docs a bit in #646 .  I will not be making any more changes and will push a release tomorrow.
