### ISSUE TITLE
Unusable window until matplotlib import

### ISSUE THREAD

**Issue by benmatwil** [enthought/mayavi#650]
I have installed the new version 4.6 on both Windows and Linux through conda and pip with python 3. However, I cannot interact with the figure window if matplotlib.pyplot has not been imported i.e.

```
import mayavi.mlab as ml
import numpy as np

x = np.array([0., 1.])
ml.plot3d(x, x, x)
```

doesn't work but

```
import matplotlib.pyplot
import mayavi.mlab as ml
import numpy as np

x = np.array([0., 1.])
ml.plot3d(x, x, x)
```

does work. In only the second example, the figure window can be interacted with.

**Comment by prabhuramachandran** [comment]
Yes indeed, you always need the GUI toolkit setup on IPython, so if you are using Qt, you need to do:
```
%gui qt
```
to activate the Qt event loop, I thought this was mentioned here: http://docs.enthought.com/mayavi/mayavi/mlab.html

If something needs to change, please let us know.  I am closing this for now, you may continue to reply on this and I will reopen it if there is a problem.

**Comment by benmatwil** [comment]
This is unrelated but I'm getting this error when using the new mayavi (and vtk8, qt5 etc.) over ssh:

"Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication."

This may be due to qt5 or vtk but wondered whether you knew what was going on.
