### ISSUE TITLE
Error messages galore: mayavi, mlab

### ISSUE THREAD

**Issue by nameisnot** [enthought/mayavi#653]
While searching the web for applications in the world of Python, I came across mayavi and tried some basic (as suggested) steps.

Accordingly I tried an example (docs.enthought.com/mayavi/mayavi/mlab.html) and the following happened:
1. (The) Mayavi scene opened and as stated in the documentation, the given visualization was reproduced. I was also able to rotate the image, take a snapshot etc.
2. However, a lot of error message was spat being out, like given below:
2a. Before the mayavi visualization appeared:

Warning (from warnings module):
  File "......~/site-packages/pyface/wx/drag_and_drop.py", line 94
    PythonObject = wx.CustomDataFormat('PythonObject')
wxPyDeprecationWarning: Call to deprecated item. Use wx.DataFormat instead.

Warning (from warnings module):
  File ".......~/site-packages/pyface/ui/wx/clipboard.py", line 24
    PythonObjectFormat = wx.CustomDataFormat('PythonObject')
wxPyDeprecationWarning: Call to deprecated item. Use wx.DataFormat instead.

Warning (from warnings module):
  File ".....~/site-packages/pyface/ui/wx/action/action_item.py", line 367
    self.control_id, label, bmp, wx.NullBitmap, kind, tooltip, longtip, None
wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.

Warning (from warnings module):
  File ".....~/site-packages/pyface/ui/wx/action/action_item.py", line 385
    wx.EVT_TOOL(parent, self.control_id, self._on_tool)
wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.

2b. As the window with the image (mayavi "scene") was moved around:
Warning (from warnings module):
  File "......~/site-packages/pyface/ui/wx/window.py", line 194
    self._position = event.GetEventObject().GetPositionTuple()
wxPyDeprecationWarning: Call to deprecated item. Use GetPosition instead
Traceback (most recent call last):
  File ".......~/site-packages/pyface/ui/wx/window.py", line 194, in _wx_on_control_move
    self._position = event.GetEventObject().GetPositionTuple()
  File "......~/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The '_position' trait of a MayaviViewer instance must be a tuple of the form: (a value of class 'int', a value of class 'int'), but a value of wx.Point(472, 111) <class 'wx._core.Point'> was specified.

3. As I can see, the messages are pointing to deprecated items (during generation of the scene and while the position of the window is changed) but am unable to find my way around.

4. I am using the following:
a. Python 3.6 on Mac Sierra
b. Numpy ver. 1.14.2
c. VTK ver. 8.1.0
d. wxPython 4.0.1
e. configobj 5.0.6

Kindly provide me the direction to take in understanding / resolution of the problem.

Thanks

**Comment by corranwebster** [comment]
TraitsUI is not currently compatible with wxPython 4.  If you want to use Python 3.x you will need to use PyQt instead.  Or you will need to downgrade to Python 2.7 and wxPython 3.

**Comment by nameisnot** [comment]
Thanks for your reply. 

Do I need to uninstall wxPython before installing PyQt? Which version of Qt & PyQt should I attempt (https://pypi.org/project/mayavi/ suggests "Qt version 4.8 with PyQt 4.11.4")?

Thanks

**Comment by prabhuramachandran** [comment]
The pypi info is outdated and I noticed it only after the release (this is already fixed and will show up in the next release I push to PyPI).  Instead see the instructions here:
https://github.com/enthought/mayavi

**Comment by prabhuramachandran** [comment]
@nameisnot -- Either PyQt5 or PyQt4 will work and no need to uninstall wxPython.  If you still have trouble you may try that.

**Comment by nameisnot** [comment]
Much appreciated. Yeah, I did go ahead with PyQt5 (and that without uninstalling wxPython). No issues afterwards.

Thanks.
