### ISSUE TITLE
import mlab not working

### ISSUE THREAD

**Issue by sbonaretti** [enthought/mayavi#659]
Hi,   
I am new to Mayavi. I have just installed it and I want to use it in my Jupyter Notebook. If I type `import mayavi` it works, but if I type `from mayavi import mlab` it kind of freezes. Suggestions?   
Thanks  a lot!  

![screen shot 2018-06-27 at 10 27 09 am](https://user-images.githubusercontent.com/13563701/41989602-b7a69860-79f4-11e8-9d68-2897dd2e2e2d.png)

**Comment by prabhuramachandran** [comment]
Use `%gui qt` as the first line on your notebook.  See here: http://docs.enthought.com/mayavi/mayavi/mlab.html

**Comment by sbonaretti** [comment]
Hi!  
Thanks a lot for your quick reply! I get an error. I am using Jupyter Notebook lab. It says "Importing PySide disabled by IPython, which has already imported an Incompatible QT Binding: pyqt5". How can I solve this? Thanks a lot!!!!

![screen shot 2018-06-27 at 10 59 23 am](https://user-images.githubusercontent.com/13563701/41991190-754842e8-79f9-11e8-9969-400176c9f4c4.png)
![screen shot 2018-06-27 at 10 59 34 am](https://user-images.githubusercontent.com/13563701/41991196-786337a8-79f9-11e8-8524-44f71287e10c.png)
![screen shot 2018-06-27 at 10 59 45 am](https://user-images.githubusercontent.com/13563701/41991200-7b304c5a-79f9-11e8-95d2-380c9e3f9f6f.png)

**Comment by prabhuramachandran** [comment]
There are a dizzying number of things that can potentially be wrong.  So please report the following: Mayavi version and how it was installed, what UI toolkits you have installed and are using.  The latest mayavi works with pyqt5.  PySide does not work with Python 3.6 only pyside 2 does but that is not supported.  So if you just have pyqt5 everything ought to work unless you are using an older package.  Another thing to try is to do the mayavi import first and then the %gui line.

**Comment by sbonaretti** [comment]
Thanks again for your quick reply!   
- Mayavi version:  `mayavi==4.5.0`    
- How it was installed:  `pip install mayavi`, `pip install PyQt5`, `jupyter nbextension install --py mayavi --user`  (following: http://docs.enthought.com/mayavi/mayavi/installation.html)   
  But when I type `jupyter nbextension enable --py mayavi --user` I get:   
  ```
  S-MacBook-Pro:docs sb$ jupyter nbextension enable --py mayavi --user
Traceback (most recent call last):
  File "/Users/sb/anaconda3/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/Users/sb/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/sb/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/sb/anaconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/Users/sb/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/Users/sb/anaconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 896, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "/Users/sb/anaconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 872, in toggle_nbextension_python
    logger=self.log)
  File "/Users/sb/anaconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 483, in enable_nbextension_python
    logger=logger)
  File "/Users/sb/anaconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 386, in _set_nbextension_state_python
    for nbext in nbexts]
  File "/Users/sb/anaconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 386, in <listcomp>
    for nbext in nbexts]
KeyError: 'require'
  ```
- python version:  `Python 3.6.4 :: Anaconda custom (64-bit)`  
- pyQt version: `PyQt5==5.9.2`  
- pyside version: `PySide2==5.9.0a1.dev1526570571`  

I have inverted the lines but no change.   

Thanks again, I really need and want to use it!

**Comment by prabhuramachandran** [comment]
Mayavi 4.6.0 is the latest version not 4.5.0.  4.6.0 fixes many issues and I recommend that you upgrade.  Can you remove pyside2, that should also help.

**Comment by sbonaretti** [comment]
OK, getting there!!!!!!! :)))
Mayavi updated and pyside2 removed. I can import mlab! :)  
Two more things not working:    
- the renderer is not embedded in the notebook  
- the renderer is black   
Thanks so much, really, for helping me so quickly! I really deeply value your help!

![screen shot 2018-06-27 at 11 50 02 am](https://user-images.githubusercontent.com/13563701/41993463-614e7080-7a00-11e8-8908-09ea0cf83eff.png)

**Comment by prabhuramachandran** [comment]
Hmm, try upgrading to pyqt5 5.10.x, that fixed some issues for me on MacOS.

**Comment by sbonaretti** [comment]
upgrading pyqt5 does the job for the rendering!!! :))))    
now I just would like to have the renderer embedded in the notebook. I have tried to upgrade ipywidgets (if this makes sense), but no improvement. Any last idea?   
Thank you so, so, so much!!!!!!! :)))))))))))) 


![screen shot 2018-06-27 at 1 48 50 pm](https://user-images.githubusercontent.com/13563701/41998948-e2c4a6f6-7a10-11e8-9853-59a5ac4cb313.png)

**Comment by prabhuramachandran** [comment]
This has nothing to do with ipywidgets or anything, you now need to read a bit to see how this is done:
http://docs.enthought.com/mayavi/mayavi/tips.html#using-mayavi-in-jupyter-notebooks

**Comment by sbonaretti** [comment]
Hi, 

I have played quite a bit with mayavi again, and I have figured out that the rendering works when I use `jupyter notebook`, not when I use `jupyter lab`. 

Best regards

**Comment by prabhuramachandran** [comment]
Sorry, I haven't used the lab enough to know the answer.  You may need to ask the jupyter lab folks.

**Comment by MarcGondran** [comment]
Hi,
I experienced the same issue and I soved it using the following command :
`conda install -c viscid-hub vtk`
