### ISSUE TITLE
Size of the glyph

### ISSUE THREAD

**Issue by wangjiawen2013** [enthought/mayavi#671]
Hi,
When I use plot3d() to plot 3D points, I am confused about the size of the points. In mayavi documents, it is  said that "the largest is proportional to inter-point distance". However, I don't know how to understand it, because there are many points. Does "inter-point distance" means the largest distance among the points or the sum of the distance ?

**Comment by prabhuramachandran** [comment]
This is not the place to ask this as this is not an issue or a bug.  For those, please use one of the mailing lists.  In any case the answer is here:
 https://github.com/enthought/mayavi/blob/master/mayavi/tools/tools.py#L225
