### ISSUE TITLE
prefer np.* to numpy.*

### ISSUE THREAD

**Issue by sciunto** [enthought/mayavi#673]
Hello,

In the documentation (and the code as well), there is a mix of numpy imports, either as np or as numpy.
From the user point of view, the documentation that uses numpy.* is not ideal. Indeed, using the np alias is now extremely common in the scientific community (numpy, scipy, many scikits...).

I would suggest to replace all the numpy.* by np.* It the maintainers agree, I can take care of it of course.

**Comment by prabhuramachandran** [comment]
Yes please do so.  Thank you.
