### ISSUE TITLE
obtain scalar values filtered by lightning

### ISSUE THREAD

**Issue by ruyuanzhang** [enthought/mayavi#682]
I am new to mayavi and really love the mayavi. I have a question about the lightning render in mayavi.

I assume mayavi can somehow transform the scalar values based on the position of the camera and the information of the light. Namely, give the camera and light information, some scalar values should be darker because of the shadow and some of the others should be brighter because of the reflection. How can I access to these "rendered" scalar values? Does mayavi provide some low-level APIs for controlling the rendering process?? 

Thanks so much!

**Comment by prabhuramachandran** [comment]
Thank you for your kind comments.  By default I don't think shadows are rendered.  To do what you want you would need to use a low-level VTK API.  You can access VTK's low level pixel data and the z buffer data if you want.  Mayavi provides a screenshot (http://docs.enthought.com/mayavi/mayavi/auto/mlab_figure.html#screenshot) call that gives you the scene's pixel data but not the zbuffer but that is relatively easy.  For example if you have an mlab figure you can do this:

```
s = mlab.test_plot3d()
pixel_data = mlab.screenshot()
f = mlab.gcf()

from tvtk.api import tvtk
z = tvtk.FloatArray()
figure.scene.render_window.get_zbuffer_data(0, 0, pixel_data.shape[0], pixel_data.shape[1], z)
zarr = z.to_array()
```
Now you have access to the z buffer and the pixel data.

Anyway this is not an issue so I am closing this.  If you have questions please post on the mailing lists.
