### ISSUE TITLE
No output shown in Jupyter

### ISSUE THREAD

**Issue by DudeMcDude** [enthought/mayavi#690]
Hi,
I'm running Jupyter Notebook on Python 3.6.

The example 3D test scene returns a blank:

![image](https://user-images.githubusercontent.com/11220053/43380041-1068ca8e-93d8-11e8-942a-f7adaf92501d.png)

Doesn't work with 'png' backend either.

**Comment by prabhuramachandran** [comment]
Well, you haven't shown anything on the notebook. You need to show the object and use IPython's display facility.  Do this by evaluating the object in the last line, by simply typing `s` in your case, i.e. your cell should read:

```
s = mlab.test_plot3d()
s
```

See here: http://docs.enthought.com/mayavi/mayavi/tips.html#using-mayavi-in-jupyter-notebooks

**Comment by DudeMcDude** [comment]
That shows the image with 'png' backend, but not with x3d.

![image](https://user-images.githubusercontent.com/11220053/43439369-92ccb1e8-949b-11e8-9398-a50d97f943a2.png)

**Comment by prabhuramachandran** [comment]
Can you try without the `local=True` (or try with `local=False`) so it pulls down the x3dom.js from CDN?

**Comment by DudeMcDude** [comment]
That works, but only when I display it in Internet Explorer.
In Chrome I get a tiny dot graphical output.

**Comment by prabhuramachandran** [comment]
Try refreshing the page?  I am afraid, at this point this is really an issue between x3dom and chrome.  Perhaps later we may have a better way to do this.

**Comment by DudeMcDude** [comment]
Thanks for your help!
