### ISSUE TITLE
How to show tow ply file

### ISSUE THREAD

**Issue by swl5571147a** [enthought/mayavi#698]
I have tow ply file, such as: a.ply and b.ply

Now, i use
`mlab.pipeline.surface(mlab.pipeline.open("a.ply"))`
`mlab.show()`

`mlab.pipeline.surface(mlab.pipeline.open("b.ply"))`
`mlab.show()`

the _a.ply_ is show, but how i control the _b.ply_ show?

In fact,  i need to control the difference ply file to show, but i don't know how to do that.
can i have some help? thanks

**Comment by prabhuramachandran** [comment]
Use `mlab.show()` just as you would `plt.show()` in matplotlib, so do it at the end when you want to block the UI.  If you are using jupyter/ipython you can do `ipython --gui qt` or `%gui qt` once you start to activate the mainloop of the UI toolkit and you then do not have to do show at all.

I have no idea what difference ply file means so am afraid I can't help there.
