### ISSUE TITLE
Install without Visual C++ Build Tools on Windows 10 64 bit

### ISSUE THREAD

**Issue by jdpigeon** [enthought/mayavi#707]
Hey there,

I know Windows-specific installation issues have arisen a couple times for this package, especially as a dependency for MNE https://github.com/mne-tools/mne-python/issues/5288

I ran into a similar problem today trying to install MNE on a fresh Windows machine. I got the `Visual C++ 14.0 is required` when trying to install mayavi via MNE's environment.yml.

I was able to fix the problem by simply installing Visual Studio Build Tools 2017. However, I'm curious if there might be a way to circumvent this requirement as the app I'm building (https://github.com/makebrainwaves/brainwaves) will eventually be deployed on high school lab computers where the 4GB download and long installation time will be an issue.

I'm not familiar with appveyor, but it sounds like that should deliver pre-compiled mayavi dependencies when installing through pip? Why might that not be working? Alternatively, is there some way I can force mayavi to not require Visual C++ build tools?

Thanks

**Comment by prabhuramachandran** [comment]
I believe I have fixed this in master (#683) but there isn't a release with this. Would it be possible for you to please try installing without a visual c++ compiler like so:

`pip install git+https://github.com/enthought/mayavi.git#egg=mayavi`

If this works, please do let me know and if you would prefer a release, I can see if I can push out a release early next week with these changes.

**Comment by jdpigeon** [comment]
It works! No visual c++ build tools needed.

This is good news. Whenever you want to cut a new release go ahead and do it. We won't need to do all the installs until October, though, so no rush.

**Comment by prabhuramachandran** [comment]
@jdpigeon -- Thanks for testing, I will try to cut a release sometime soon with important fixes.

**Comment by prabhuramachandran** [comment]
@jdpigeon -- I just pushed 4.6.2 to pypi so you could test against that if you want to.
