### ISSUE TITLE
crash down when "from mayavi import mlab"

### ISSUE THREAD

**Issue by Irenexzwen** [enthought/mayavi#714]
I installed the newest version of mayavi 4.6.1  with pyqt5 python3.6 win10
However, when I import mlab, the computer says "python stops working."

**Comment by prabhuramachandran** [comment]
Must be a PyQt5 issue.  Just run from PyQt5 import QtCore or QtGui and see.  If this crashes too, either downgrade to an older version of PyQt5 or use PySide2.

**Comment by Irenexzwen** [comment]
thanks, I could run mayavi now by reinstall it in .whl from uci precompiled database and reinstalled pyqt5 as well.
