### ISSUE TITLE
Getting  PyThreadState_Get: no current thread when installing mayavi on OSX, py3.6.6

### ISSUE THREAD

**Issue by gnurser** [enthought/mayavi#718]
Hi,
OSX 10.13.6 with prerequisites from conda, mayavi from pip

conda list 
....
pip                       18.0                     py36_1    conda-forge
python                    3.6.6                hc167b69_0  
pyqt                      5.9.2            py36h655552a_2  
qt                        5.9.6                h45cd832_2  
traits                    4.6.0            py36h470a237_2    conda-forge
traitsui                  6.0.0                      py_1    conda-forge
vtk                       8.1.1           py36hdfe3907_203    conda-forge
....

~/miniconda3 $ pip install --user mayavi
Collecting mayavi
  Using cached https://files.pythonhosted.org/packages/83/9e/293ba57353ed258c2f64d54bf00ca1447c1f38f4eb60d0e762ddec57bf51/mayavi-4.6.2.tar.bz2
Requirement already satisfied: apptools in ./lib/python3.6/site-packages (from mayavi) (4.4.0)
Requirement already satisfied: envisage in ./lib/python3.6/site-packages (from mayavi) (4.7.0)
Requirement already satisfied: numpy in ./lib/python3.6/site-packages (from mayavi) (1.13.1)
Requirement already satisfied: pyface>=6.0.0 in ./lib/python3.6/site-packages (from mayavi) (6.0.0)
Requirement already satisfied: pygments in ./lib/python3.6/site-packages (from mayavi) (2.2.0)
Requirement already satisfied: traits>=4.6.0 in ./lib/python3.6/site-packages (from mayavi) (4.6.0)
Requirement already satisfied: traitsui>=6.0.0 in ./lib/python3.6/site-packages (from mayavi) (6.0.0)
Requirement already satisfied: vtk in ./lib/python3.6/site-packages (from mayavi) (8.1.1)
Requirement already satisfied: configobj in ./lib/python3.6/site-packages (from apptools->mayavi) (5.0.6)
Requirement already satisfied: six in ./lib/python3.6/site-packages (from configobj->apptools->mayavi) (1.11.0)
Building wheels for collected packages: mayavi
  Running setup.py bdist_wheel for mayavi ... error
  Complete output from command /Users/agn/miniconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/ys/892qnv_x06v4pp5hy8sw6str0000gp/T/pip-install-s81yk34g/mayavi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/ys/892qnv_x06v4pp5hy8sw6str0000gp/T/pip-wheel-s6d7jgae --python-tag cp36:
  running bdist_wheel
  running build
  Fatal Python error: PyThreadState_Get: no current thread
  
  
  ----------------------------------------
  Failed building wheel for mayavi
  Running setup.py clean for mayavi
Failed to build mayavi
Installing collected packages: mayavi
  Running setup.py install for mayavi ... error
    Complete output from command /Users/agn/miniconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/ys/892qnv_x06v4pp5hy8sw6str0000gp/T/pip-install-s81yk34g/mayavi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/ys/892qnv_x06v4pp5hy8sw6str0000gp/T/pip-record-dsut6_4y/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    Fatal Python error: PyThreadState_Get: no current thread

**Comment by prabhuramachandran** [comment]
Seems like a build issue with VTK, can you try with VTK from pip?  If that works, I suspect this is a conda-forge build issue.

**Comment by gnurser** [comment]
That does work. Thanks for replying so quickly.

**Comment by gnurser** [comment]
Yes, it works with VTK from pip
