### ISSUE TITLE
How to use info.ui.dispose() with mayavi 4.6.2

### ISSUE THREAD

**Issue by rc** [enthought/mayavi#720]
Hi,

I have a custom app on top of Mayavi, that uses the following code to close the window and exit:
```
traits_view = View(
<snip>
                HGroup(spring,
                       <snip>
                       Item('button_quit', show_label=False)),
                resizable=True,
                buttons=[],
                handler=ClosingHandler(),
<snip>
)

class ClosingHandler(Handler):
    def object_button_quit_changed(self, info):
        if not info.initialized: return
        info.ui.dispose()
```

I have just installed mayavi 4.6.2 using the Anaconda3-5.3.0, and the code stopped working: the window disappears, but then the process hangs indefinitely and has to be killed (even Ctrl-C does not work). What am I doing wrong?

Notes:
- using CancelButton works, but I would need to have it in the group of other buttons, and with the  'quit' label.
- adding sys.exit() call to the `object_button_quit_changed()` function helps, but then this raises SystemExit with Mayavi 4.1.0 - I would like to have a code that works in both versions without exceptions :)

**Comment by prabhuramachandran** [comment]
Hi Robert, I am not sure what has changed to make this.  I don't think this is something that has changed in Mayavi.  My suspicion is that this is probably a PyQt5 issue.  Can you try with pyside2 for example and see if that works? Some older PyQt5 versions have had issues in my experience. It could be a pyface/traitsui issue but I am not sure if that could be the problem either. @corranwebster, are you aware of anything like this?

**Comment by rc** [comment]
Thank you both for the tips! I will report back, when I have more information.

**Comment by rc** [comment]
@corranwebster your code helped, thank you very much! I am closing this issue.
