### ISSUE TITLE
about wxpython

### ISSUE THREAD

**Issue by giswangsj** [enthought/mayavi#726]
The examples examples/mayavi/interactive/wx_embedding and wx_mayavi_embed_in_notebook can't run .
My environment is win7 , python3.6 , mayavi-4.6.2+vtk81 and wxPython4.0.3.

**Comment by prabhuramachandran** [comment]
Well, wxPython 4.0.3 is not supported by ETS currently.  There is this old PR: https://github.com/enthought/pyface/pull/287 but that has not been updated.

**Comment by jmoraleda** [comment]
What is the status of being able to embed mayavi in wxPython 4? I tried porting the examples, but eventually I was not able to get passed `traits` and `traitsui` issues. Are those being ported? Thank you.

**Comment by prabhuramachandran** [comment]
The latest traitsui/pyface do work somewhat with wxPython 4.0.x but not quite with 4.1.  Mayavi itself should work, i.e. the scene does work but the rest of the UI relies on traitsui/pyface working flawlessly and there are issues there.  This would be a good time to kick the wheels though and report/fix issues in pyface/traitsui.  Thanks!

**Comment by jmoraleda** [comment]
For what is worth, I adapted the code at https://docs.enthought.com/mayavi/mayavi/auto/example_wx_embedding.html#example-wx-embedding as follows to try to make it work with the latest wxPython compiled from source:

``` python

from numpy import ogrid, sin

from traits.api import HasTraits, Instance
from traitsui.api import View, Item

from mayavi.sources.api import ArraySource
from mayavi.modules.api import IsoSurface

from mayavi.core.ui.api import SceneEditor, MlabSceneModel


class MayaviView(HasTraits):

    scene = Instance(MlabSceneModel, ())

    # The layout of the panel created by Traits
    view = View(Item('scene', editor=SceneEditor(), resizable=True,
                    show_label=False),
                    resizable=True)

    def __init__(self):
        HasTraits.__init__(self)
        # Create some data, and plot it using the embedded scene's engine
        x, y, z = ogrid[-10:10:100j, -10:10:100j, -10:10:100j]
        scalars = sin(x*y*z)/(x*y*z)
        src = ArraySource(scalar_data=scalars)
        self.scene.engine.add_source(src)
        src.add_module(IsoSurface())

#-----------------------------------------------------------------------------
# Wx Code
import wx

class MainWindow(wx.Frame):

    def __init__(self, parent, id):
        wx.Frame.__init__(self, parent, id, 'Mayavi in Wx')
        self.mayavi_view = MayaviView()
        # Use traits to create a panel, and use it as the content of this
        # wx frame.
        self.control = self.mayavi_view.edit_traits(
                        parent=self,
                        kind='subpanel').control

        vsizer = wx.BoxSizer(wx.VERTICAL)
        vsizer.Add(self.control, 1, wx.EXPAND)
        self.SetSizer(vsizer)
        self.SetAutoLayout(True)


app = wx.App()
frame = MainWindow(None, wx.ID_ANY)
frame.Show(True)
app.MainLoop()
```
But it fails on Linux without displaying anything with the following error:
```
Traceback (most recent call last):
  File "sample1.py", line 53, in <module>
    frame = MainWindow(None, wx.ID_ANY)
  File "sample1.py", line 47, in __init__
    vsizer.Add(self.control, 1, wx.EXPAND)
TypeError: Sizer.Add(): arguments did not match any overloaded call:
  overload 1: argument 1 has unexpected type 'QWidget'
```

**Comment by corranwebster** [comment]
We're in an awkward position with TraitsUI and wxPython right now:

- we did a first cut at moving from wxPython 3.x to wxPython 4.0 over the last few months, which was released a couple of weeks ago in TraitsUI and Pyface 7.0.  This release is somewhat experimental: most tests pass, but coverage is not great.
- on the same day as TraitsUI was released, and independently,  wxPython 4.1 was released by the wxPython maintainers, which was not compatible with our release of TraitsUI
- at Enthought, wxPython is not a priority as we use Qt exclusively for internal projects, so wxPython support is reliant on volunteer efforts.

So if you want to use wxPython, then right now your choices are (I think):

- Python 3.5+ (3.6 is probably most stable), wxPython 4.0.x, TraitsUI 7, Mayavi master
- Python 2.7, wxPython 3.x, TraitsUI 6.x, last released Mayavi

Any help to get things working on wxPython 4.1 would be appreciated

**Comment by jmoraleda** [comment]
Shouldn't the issue remain open until it is fixed?

**Comment by prabhuramachandran** [comment]
@jmoraleda -- `TypeError: Sizer.Add(): arguments did not match any overloaded call:
  overload 1: argument 1 has unexpected type 'QWidget'`. Suggests that you are perhaps not using the wx ETS_TOOLKIT?  Did you set the environment variable `ETS_TOOLKIT=wx`?  I am just checking to make sure this isn't the issue.

**Comment by jmoraleda** [comment]
@prabhuramachandran I did not know about setting `ETS_TOOLKIT`. It definitely was the first issue. Thank you.

@corranwebster I solved the two critical issues that stopped the demo from working in the latest wx (See https://github.com/enthought/traitsui/issues/828 and https://github.com/enthought/traitsui/issues/827)

With those two fixes the demo fully runs. There remain several wx deprecation warnings across multiple enthought mantained libraries that should be easy to fix as the deprecation warning messages themselves point out.

For reference, the code below 
```python
# Adapted from https://docs.enthought.com/mayavi/mayavi/auto/example_wx_embedding.html#example-wx-embedding

from traits.etsconfig.api import ETSConfig
ETSConfig.toolkit = 'wx'

from numpy import ogrid, sin

from traits.api import HasTraits, Instance
from traitsui.api import View, Item

from mayavi.sources.api import ArraySource
from mayavi.modules.api import IsoSurface

from mayavi.core.ui.api import SceneEditor, MlabSceneModel


class MayaviView(HasTraits):

    scene = Instance(MlabSceneModel, ())

    # The layout of the panel created by Traits
    view = View(Item('scene', editor=SceneEditor(), resizable=True,
                    show_label=False),
                    resizable=True)

    def __init__(self):
        HasTraits.__init__(self)
        # Create some data, and plot it using the embedded scene's engine
        x, y, z = ogrid[-10:10:100j, -10:10:100j, -10:10:100j]
        scalars = sin(x*y*z)/(x*y*z)
        src = ArraySource(scalar_data=scalars)
        self.scene.engine.add_source(src)
        src.add_module(IsoSurface())

#-----------------------------------------------------------------------------
# Wx Code
import wx

class MainWindow(wx.Frame):

    def __init__(self, parent, id):
        wx.Frame.__init__(self, parent, id, 'Mayavi in Wx')
        self.mayavi_view = MayaviView()
        # Use traits to create a panel, and use it as the content of this
        # wx frame.
        self.control = self.mayavi_view.edit_traits(
                        parent=self,
                        kind='subpanel').control

        vsizer = wx.BoxSizer(wx.VERTICAL)
        vsizer.Add(self.control, 1, wx.EXPAND)
        self.SetSizer(vsizer)
        self.SetAutoLayout(True)


app = wx.App()
frame = MainWindow(None, wx.ID_ANY)
frame.Show(True)
app.MainLoop()
```

produces 

![image](https://user-images.githubusercontent.com/23492126/82256496-4d5f4280-990b-11ea-8872-e66de6c8c5c0.png)

In my opinion this issue may now be closed. Thank you.

**Comment by giswangsj** [comment]
ok，thank you
