### ISSUE TITLE
Wrong axes of surf

### ISSUE THREAD

**Issue by JosefJerabek** [enthought/mayavi#727]
Have a code below which plots `surf`. 
According to presence of line `mlab.title("Title present")` I have two outputs (see enclosed pictures).
Both cases are noncorrect.

1. Presence of title
Axes end points are correct, but the axes lengths are wrong.

1. No title
Axes end points are wrong, but axes lengths are correct.

How to have a proper axes?

`from mayavi import mlab`
`from numpy import random, arange, array`

`x_axis = array(0.333 * (arange(13) - 6.0))  # values: -2, -1.66, -1.33 ... 2`
`y_axis = array(0.5 * (arange(11)))          # values: [0,] 0.5, 1 ... 5`

`data = random.rand(x_axis.size, y_axis.size)`
`mlab.surf(x_axis, y_axis, data, warp_scale="auto")  # toto OK`

`mlab.title("Title present") # LINE TO BE COMMENTED`

`h_axes = mlab.axes(xlabel="x", ylabel="y", zlabel="")`
`mlab.show()`

![title_error](https://user-images.githubusercontent.com/30431510/47014919-eafcf980-d14b-11e8-9f19-31c7e2b4ed35.png)
![title_error_no_title](https://user-images.githubusercontent.com/30431510/47014931-f18b7100-d14b-11e8-8aa2-473dfa399d64.png)

python 3.6.5
mayavi 4.6.2

**Comment by prabhuramachandran** [comment]
So if you call `title` after the `axes`, it does show the title and the axes.  The extent of the actor is set to the bounds of the previous object shown so in this case it shows the "warped" surface extent.  To change this you can pass the extent kwarg with [xmin, xmax, ymin, ymax, zmin, zmax] and it will set the axes as specified. Am not sure if this is really a bug, so am closing this.  Please comment/reopen if this is a bug.
