### ISSUE TITLE
3D Polygon Mesh in Mayavi

### ISSUE THREAD

**Issue by kuttamuwa** [enthought/mayavi#732]
Hi,
I need to make 3d triangulation between my polygons. I made delaunay but those triangles are not inside of boundary. I thought that i need constrained delaunay in 3d.. However, is there any way to do that?
![rs](https://user-images.githubusercontent.com/26677935/47791381-9f8d4280-dd2a-11e8-9d15-ce7a1b8f67d3.png)

As you see on SS. There are wrong triangles on xy plane and Z plane. I need to protect my boundaries. Otherwise my triangles are stepping outside of mesh and volumes are so high.

**Comment by prabhuramachandran** [comment]
VTK's 2D delaunay filter does support constrained triangulation but not in 3D AFAIK.  See here: https://github.com/Kitware/VTK/blob/master/Examples/Modelling/Python/constrainedDelaunay.py

This is per se not a Mayavi issue as we are just using VTK underneath.  Tools like tetgen should do this.  There is even a python interface to tetgen that I can see.  I have no experience with those tools though.  Closing this ticket for now.
