### ISSUE TITLE
Mayavi scene 1 'not responding' 

### ISSUE THREAD

**Issue by aconceicao** [enthought/mayavi#746]
I'm new using Mayavi. I tried several approaches to visualize my 3D data with Mayavi in Ipython console at Spyder. As recommended on the Install section of Mayavi documentation, I used pip (install PyQt5 and Mayavi) but didn't work. Then, I uninstalled and tried using conda-forge but was the same. The code seems to be ok, but when I run the second window (Mayavi Scene 1) appears as '**Not responding**.' Below is the version of the latest packages version I'm using now and the code.

Python 3.6.6 |Anaconda custom (64-bit)|
spyder                  3.3.2
pyqt                     5.6.0
PyQt5                   5.9.2            
PyQt5_sip             4.19.13  <pip>
vtk                        8.1.1    py36_vc14h99a48a5_200  [vc14]  conda-forge
mayavi                 4.6.2    <pip>

import skimage.io as io
from skimage import filters, exposure
import numpy as np
import matplotlib.pyplot as plt
import vtk
from mayavi import mlab 

image_collection = io.ImageCollection('D:/2018/DATA/recon_dir/*.tiff')
image_3d = io.concatenate_images(image_collection)

mlab.volume_slice(image_3d)
mlab.outline()

Can some help me? I'm for three days trying.

**Comment by aconceicao** [comment]
Now, additionally to the blank windows another one also opened:


![picture1](https://user-images.githubusercontent.com/43742277/50291312-7f4a4c00-046e-11e9-9d40-ed60ac8446cb.png)

**Comment by prabhuramachandran** [comment]
Are you running this on an IPython console?  If so you must first type `%gui qt` to enable Qt interactivity (see here: http://docs.enthought.com/mayavi/mayavi/mlab.html).  The second error suggests that you have an OpenGL driver problem but lets eliminate the first one.  Can you try a simple Python script, like so in a separate text file:
```
# tm.py
from mayavi import mlab
mlab.test_plot3d()
mlab.show()
```
Then run this, `python tm.py`.  Does this work?

**Comment by aconceicao** [comment]
Dear @prabhuramachandran 

thank you for your suggestion. Yes, I'm using the IPython console in Spyder. I tried %gui qt to enable Qt interactivity but didn't work. 
I also tested the python script you've suggested in Spyder as well as in Ipython console at Linux CentOS 7 Terminal but didn't work too. The following error appears:

In ../Rendering/OpenGL2/vtkShaderProgram.cxx, line 431
vtkShaderProgram (0x4296f60)

Do you have any idea about the problem?

**Comment by dtmaidenmueller** [comment]
As far as the messages about wglChoosePixelFormatARB.  I've seen those show up on VMs without graphics hardware (for instance, Windows VMs in Azure).  I was able to resolve that error by replacing the opengl32 dll file on the VM with one that uses software-only rendering:

https://fdossena.com/?p=mesa/index.frag

**Comment by shash29-dev** [comment]
Unresponsive window. (On windows)
conda install -c anaconda mayavi

my script:
**from mayavi import mlab** (imports successfully)
**mlab.test_plot3d()**  (A window pos, doesn't wait for mlab.show() and shows nothing. Not responding window.)

**Comment by prabhuramachandran** [comment]
If you run this on ipython you need to do `%gui qt`, if this is a Python script, you need to do `mlab.show()` at the end.  This is documented here: https://docs.enthought.com/mayavi/mayavi/mlab_running_scripts.html

**Comment by RiccSil** [comment]
> If you run this on ipython you need to do `%gui qt`, if this is a Python script, you need to do `mlab.show()` at the end. This is documented here: https://docs.enthought.com/mayavi/mayavi/mlab_running_scripts.html

Had a similar problem, that solved it. Thanks a lot!
