### ISSUE TITLE
Does Mayavi have something to force drawing? 

### ISSUE THREAD

**Issue by CJ-Wright** [enthought/mayavi#760]
For instance matplotlib has [`draw`](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.draw.html#matplotlib-pyplot-draw) which forces drawing a figure and `draw_idle` which causes a figure to be drawn when the system is idle. I'm trying to put drawing of mayavi plots on an event loop similar to how matplotlib is handled here: https://github.com/NSLS-II/bluesky/blob/master/bluesky/utils.py#L771

**Comment by prabhuramachandran** [comment]
With version 4.6.1 I had added a `mlab.process_ui_events()` function that will at least process UI events.  Will that help?

**Comment by CJ-Wright** [comment]
I'm not certain that is doing what I need, here is a minimal example:
```python
import mayavi.mlab as mlab
import time
import numpy as np

x = mlab.pipeline.scalar_field(np.random.random((10, 10, 10)))
z = mlab.pipeline.volume(x)

while True:
    mlab.process_ui_events()
    time.sleep(.1)
    # play with the volume
```

`mlab.process_ui_events()` didn't seem to let the mayavi figure take over the event loop, all the rotation of the graphics happen after the while loop is interrupted. (Note that this was running in a pure python interactive session.

**Comment by CJ-Wright** [comment]
It seems that the qt kicker works automatically, since it is calling the `qApp.processEvents()` behind the scenes and matplotlib and mayavi share the same Qt app.
