### ISSUE TITLE
AttributeError: 'Texture' object has no attribute 'color_mode'

### ISSUE THREAD

**Issue by enthought-jdragos** [enthought/mayavi#776]
I am trying to create a fresh install of mayavi using the edm system, using the commands:

`edm install mayavi pyqt -e MY_test`

(for test environment MY_test)
but I kept getting the error: 

```
...
 File "/Users/jdragos/.edm/envs/MY_test/lib/python3.6/site-packages/traitsui/qt4/ui_panel.py", line 863, in _add_items
    ui, object, name, item.tooltip, None
  File "/Users/jdragos/.edm/envs/MY_test/lib/python3.6/site-packages/traitsui/editor_factory.py", line 146, in simple_editor
    description=description)
  File "/Users/jdragos/.edm/envs/MY_test/lib/python3.6/site-packages/traitsui/editor.py", line 146, in __init__
    self.old_value = getattr(self.object, self.name)
   AttributeError: 'Texture' object has no attribute 'color_mode'
```

when trying to create any surface module object in the interactive mayavi environment.

the main package versions for this install are:

```
mayavi             4.6.2-1  
pyface             6.0.0-5   
pyqt               4.12.1-1   
qt                 4.8.7-10  
traits             5.1.1-1    
traitsui           6.0.0-4    
vtk                8.0.0-2    
```

I do not get this error when creating a new edm environment and installing through pip:

```
pip install mayavi
pip install PyQt5
```

the main packages when installing though pip are:
  
```
mayavi            4.6.2    
pip               18.1   
pyface            6.0.0    
PyQt5             5.12.1 
PyQt5-sip         4.19.15 
traits            5.1.1  
traitsui          6.0.0  
vtk               8.1.2 
```

Thanks.

**Comment by prabhuramachandran** [comment]
Not sure what is going on here.  Possibly a difference in the VTK version.  It is possible that VTK 8.0.0 does not have the new color_mode variable, in which case I should fix that however, 8.0.0 is pretty old now.

**Comment by arnab-muhuri** [comment]
my image is already an array and I am trying to execute

texture = tvtk.Texture(input_connection=img.output_port, interpolate=0)

but I get an error that states

AttributeError: 'numpy.ndarray' object has no attribute 'output_port'

I don't get this point. The image will always be an array right!

**Comment by JackDra** [comment]
> texture = tvtk.Texture(input_connection=img.output_port, interpolate=0)

Sounds like your img varaiable is a numpy array, not a tvtk.ImageData object, Try using this function to create a tvtk.Texture from a numpy array:

```
def texture_from_np(image):
    """
    Creates a tvtk.Texture object from a numpy image array
    """
    scalars = tvtk.UnsignedCharArray(name='RGB',
                                     number_of_components=3)
    # vtk uses column-major order (Fortan order), whereas
    # numpy array is in row-major order (C order) by default
    scalars.from_array(image.reshape(-1, 3, order='F'))
    tvtk_img = tvtk.ImageData()
    tvtk_img.dimensions = [image.shape[0], image.shape[1], 1]
    tvtk_img.point_data.scalars = scalars
    texture = tvtk.Texture()
    texture.set_input_data(tvtk_img)
    return texture
```

**Comment by arnab-muhuri** [comment]
I just have a single layer in my array in X rows and Y columns. 
It's not a three-layer RGB.
Can you modify the code?

**Comment by JackDra** [comment]
Easiest solution is to just convert your numpy array into RGB. Also keep in mind this forum is for issues, not for help.

**Comment by arnab-muhuri** [comment]
Thanks. 
As far as I understand, your function generates the texture so one doesn't have to really execute,
**texture = tvtk.Texture(input_connection=img.output_port, interpolate=0)**

**Comment by arnab-muhuri** [comment]
I am essentially trying to wrap the image over the digital elevation model (DEM).
However, the contrast is not much between pixels and therefore the wrapped image over the DEM appears dark. Is there a way to contrast stretch the image while wrapping it over the DEM?

**Comment by JackDra** [comment]
This issue seems to have been solved. Current edm install includes vtk version 8.1.2-2

**Comment by arnab-muhuri** [comment]
Can you post the link to the discussion for the last issue I raised here?
