### ISSUE TITLE
Volume rendering outputs a gray screen

### ISSUE THREAD

**Issue by masifv** [enthought/mayavi#781]
Hi,

I'm trying to get volume rendering output something else than a gray screen. I have no previous experience with mayavi so this may very well be a user error. With the example code below I get a gray screen but when uncommenting offsceen rendering I get an output image with rendered volume. What might be the issue? With mlab.show() a "Mayavi scene 1" window pops up where I can for example toggle axes indicator but the background is all gray. 

Example code:

import numpy as np
from mayavi import mlab
(#) mlab.options.offscreen = True

x, y, z = np.ogrid[-10:10:20j, -10:10:20j, -10:10:20j]
volume = np.sin(x * y * z) / (x * y * z)
sf = mlab.pipeline.scalar_field(volume)
mlab.pipeline.volume(sf)

mlab.show()
(#) mlab.savefig('test.png')

Here is the used conda environment:
[volume_render_env.txt](https://github.com/enthought/mayavi/files/3216324/volume_render_env.txt)

I tried with two linux machines and both have the same issue:
Ubuntu 18.04.2 LTS
Output of uname -a:
Linux x1g6 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Manjaro linux 18.0.4
Output of uname -a:
Linux yang 4.19.42-1-MANJARO #1 SMP PREEMPT Fri May 10 20:52:43 UTC 2019 x86_64 GNU/Linux

**Comment by AIRedWood** [comment]
I have encountered the same problem. Is there any solution?

**Comment by prabhuramachandran** [comment]
This looks like the #789 ticket and I suspect a graphics driver issue as this does work for me with Mayavi master.  Closing for now, please try with master and if it is still broken reopen or comment on this ticket.
