### ISSUE TITLE
Issues with Volume rendering got a gray screen

### ISSUE THREAD

**Issue by AIRedWood** [enthought/mayavi#789]
Hello，
I am trying to use Volume rendering in my project.
I ran the code inside the official demo, but couldn't output the image, I got a gray screen.
code show as below：

`import numpy as np`
`from mayavi import mlab`
`x, y, z = np.ogrid[-10:10:20j, -10:10:20j, -10:10:20j]`
`s = np.sin(x*y*z)/(x*y*z)`
`mlab.pipeline.volume(mlab.pipeline.scalar_field(s))`
`mlab.show()`

The system I am using is Ubuntu 16.04

I want to ask what is the reason, thank you very much.

**Comment by prabhuramachandran** [comment]
Works perfectly for me with Mayavi master.  I think this may be a graphics driver issue. Closing for now.  Please reopen or comment if there is a Mayavi issue.
