### ISSUE TITLE
Get points and faces from mesh

### ISSUE THREAD

**Issue by rupeshchandgude** [enthought/mayavi#805]
Hello, I have created the mesh in mayavi using x,y,z coordinates. Mesh is generated by following code 
`pts = mlab.points3d(x, y, z,s)
mesh = mlab.pipeline.delaunay2d(pts)
surf = mlab.pipeline.surface(mesh)
mlab.show()`

I have got following output:
![mayavi_mesh](https://user-images.githubusercontent.com/35450740/61028897-78b5fe80-a3d7-11e9-96b1-e3cb1528fc8a.png)
Now I want the faces of above mesh to do some processing. Is there any way to get point and face data from mesh itself? Thank you in advance.

**Comment by mprogram** [comment]
_It seems that your semicolons/new lines got eated, no `mlab` import, and no `x, y, z,s` defined; perhaps, you suppose it is not a 'run-and-see' the example…_

**Comment by rupeshchandgude** [comment]
> _It seems that your semicolons/new lines got eated, no `mlab` import, and no `x, y, z,s` defined; perhaps, you suppose it is not a 'run-and-see' the example…_

Sorry for that, x,y,z  are taken from .ply file . I had run the code which is giving me above output. So I had points data with me, I want the face data(i.e. which three vertices were use to create a face). 

`from plyfile import PlyData,PlyElement
import numpy as np 
from mayavi import mlab
from tvtk.api import tvtk

plydata = PlyData.read('Box.ply')
points = plydata.elements[0].data

x,y,z = [],[],[]                                                                                                                                                                                    

for i in points: 
    x.append(i[0]) 
    y.append(i[1]) 
    z.append(i[2]) 

s = [0.1]*len(x)

pts = mlab.points3d(x, y, z,s)
mesh = mlab.pipeline.delaunay2d(pts)
surf = mlab.pipeline.surface(mesh)
mlab.show()`

I used above code.

**Comment by rupeshchandgude** [comment]
We can get point and cell(face) data using surf.mlab_source
