### ISSUE TITLE
How can I get triangle data after applying delaunay2d ?

### ISSUE THREAD

**Issue by rupeshchandgude** [enthought/mayavi#823]
I have X,Y,Z point data with me,. From this I created delaunay2d mesh and convert it to surface using following code:
`pts = mlab.points3d(x, y, z, scale_mode='none', scale_factor=0.01)`
`mesh = mlab.pipeline.delaunay2d(pts)`
`surf = mlab.pipeline.surface(mesh)`

Now I have 3D surface with me. I want to access each triangle from mesh and do some calculations on it. Is it any method to do that? Similar to accessing points from mlab_source. i.e.
`surf.mlab_source.x`
`surf.mlab_source.y`
`surf.mlab_source.z`

**Comment by prabhuramachandran** [comment]
This is not an issue, so please do not use the issues to have questions answered, for that please send email on the mailing lists (https://github.com/enthought/mayavi#bug-tracker-mailing-list-etc).

For a quick answer, you'll have to get the cell data from the output of the mesh object.  Here is sample code:
```
x, y = np.random.random((2, 10))
z = np.ones_like(x)
src = mlab.pipeline.scalar_scatter(x, y, z)
d = mlab.pipeline.delaunay2d(src)
s = mlab.pipeline.surface(d)

print(pd.polys.to_array())
```
