### ISSUE TITLE
Mayavi on GPU

### ISSUE THREAD

**Issue by abhigoku10** [enthought/mayavi#828]
@certik @rkern @EdwinWiseOne @mattions @mounte  hello thanks for the wonderful code base just had few queries 
1. is there any separate installation for GPU 
2. when mavayavi it has the same timing on both GPU and CPU 
3. can i make it compatible to work faster on GPU

**Comment by prabhuramachandran** [comment]
VTK depends on OpenGL and if you have a GPU the new VTK 8.x series do use the programmable pipeline so will employ the GPU automatically -- you need to make sure your GPU is setup properly and that OpenGL will work with it.  VTK underneath uses the GPU for the visualization.  For the algorithms that run like contouring they are still CPU based but I believe there are efforts under way to improve this.  Look at the VTK package and the VTK-m package to find out more http://m.vtk.org/index.php/Main_Page
