### ISSUE TITLE
Hoe to save STEP from Surf data ,using mayavi mlab?

### ISSUE THREAD

**Issue by selvakarna** [enthought/mayavi#830]
How to save STEP from Surf data ,using mayavi mlab?

**Comment by prabhuramachandran** [comment]
I don't believe that is supported in VTK, you can export or save something as an STL or PLY using raw VTK or tvtk code if you want, for example:
`$ ipython --gui qt`
```
from mayavi import mlab
c = mlab.test_contour3d()
from tvtk.api import tvtk
w = tvtk.STLWriter()
w.set_input_connection(c.contour.contour_filter.output_port)
w.file_name = '/tmp/junk.stl'
w.write()
```

Also, this isn't the forum to get help but to file issues.

**Comment by selvakarna** [comment]
Hi @prabhuramachandran , 

         How to export as step file ? using tvtk

**Comment by prabhuramachandran** [comment]
Not possible AFAIK.
