### ISSUE TITLE
How to use multiple offscreen rendering displays?

### ISSUE THREAD

**Issue by OlegJakushkin** [enthought/mayavi#890]
So the problem is that I want to have separate. multiple offscreen renderers. Yet I get only one:

![MAYAVI](https://user-images.githubusercontent.com/2915361/73120340-b9ddbc80-3f7d-11ea-9c40-b036c818fa43.gif)

Here is how I set up a display:
```python
import os
import subprocess
import random
import time

os.environ['ETS_TOOLKIT']='null'
import numpy
%matplotlib inline

from xvfbwrapper import Xvfb
from IPython.display import Image
from mayavi import mlab
mlab.options.offscreen = True
def init():
    display = Xvfb(width=500, height=500)
    display.start()
    mlab.init_notebook('ipy')
init()
```

And here is how I start mayavi:
```python
init()
mlab.init_notebook()
mlab.clf()
s = mlab.pipeline.open('./u000000.vtu')
scp = mlab.pipeline.volume(s)
scp = mlab.pipeline.scalar_cut_plane(s, view_controls=True)
s
```

How to get multiple offscreen renderers for different jupyter cells?

**Comment by prabhuramachandran** [comment]
Use `mlab.figure()` to create a new figure as mentioned here: https://github.com/enthought/mayavi/blob/master/examples/mayavi/mayavi_jupyter.ipynb
