### ISSUE TITLE
plot 3d lidar point sequence

### ISSUE THREAD

**Issue by Jinho-P** [enthought/mayavi#903]
I try to plot 3d lidar point sequence using mayavi mlab & animate.
I want to plot whole data sequence not a single frame.
For this, I use .set() method like this,

point = mlab.points3d(x, y, z, ...)
mlab_source_point = point.mlab_source
mlab_source_point.set(x=x, y=y, z=z, col=col)

It looks like well but, when point set size is changed, the error is occured that
"ValueError: could not broadcast input array from shape (129792) into shape (220000)"
Is it impossible animating 3d point sequence which has varying point set size?

**Comment by prabhuramachandran** [comment]
Use the `reset` method when the size changes, see here: https://docs.enthought.com/mayavi/mayavi/mlab_animating.html

**Comment by Jinho-P** [comment]
When I use 'reset' method, there some error.

Traceback (most recent call last):
  File "/home/jinho-sesol/anaconda3/envs/img_lidar/lib/python3.7/site-packages/pyface/timer/i_timer.py", line 195, in perform
    self._perform()
  File "/home/jinho-sesol/anaconda3/envs/img_lidar/lib/python3.7/site-packages/pyface/timer/i_timer.py", line 294, in _perform
    self.callback(*self.args, **self.kwargs)
  File "/home/jinho-sesol/anaconda3/envs/img_lidar/lib/python3.7/site-packages/mayavi/tools/animator.py", line 224, in _step
    self._next()
  File "./read_lidar_ani.py", line 85, in anim
    mlab_source_point.reset(x=x, y=y, z=z)
  File "/home/jinho-sesol/anaconda3/envs/img_lidar/lib/python3.7/site-packages/mayavi/tools/sources.py", line 204, in reset
    assert len(points) == len(scalars.ravel())
AssertionError
Aborted (core dumped)

Do you know about this problem?

**Comment by Jinho-P** [comment]
> Use the `reset` method when the size changes, see here: https://docs.enthought.com/mayavi/mayavi/mlab_animating.html

When I use 'reset' method, there some error.

Traceback (most recent call last):
File "/home/jinho-sesol/anaconda3/envs/img_lidar/lib/python3.7/site-packages/pyface/timer/i_timer.py", line 195, in perform
self._perform()
File "/home/jinho-sesol/anaconda3/envs/img_lidar/lib/python3.7/site-packages/pyface/timer/i_timer.py", line 294, in _perform
self.callback(*self.args, **self.kwargs)
File "/home/jinho-sesol/anaconda3/envs/img_lidar/lib/python3.7/site-packages/mayavi/tools/animator.py", line 224, in _step
self._next()
File "./read_lidar_ani.py", line 85, in anim
mlab_source_point.reset(x=x, y=y, z=z)
File "/home/jinho-sesol/anaconda3/envs/img_lidar/lib/python3.7/site-packages/mayavi/tools/sources.py", line 204, in reset
assert len(points) == len(scalars.ravel())
AssertionError
Aborted (core dumped)

Do you know about this problem?

**Comment by prabhuramachandran** [comment]
If you have also set scalar values, then you should set those too when you reset, otherwise the scalars are inconsistent with the points.

**Comment by Jinho-P** [comment]
Could you let me konw the meaning of 'set scalar values'?
I can not understand what is it exactly. 

In my code, I use figure and points3d method like this,
fig = mlab.figure(bgcolor=(0, 0, 0), size=(640*2, 500*2))
point = mlab.points3d(x, y, z,
					col,          # Values used for Color
					mode="point",
					colormap='spectral', # 'bone', 'copper', 'gnuplot'
					# color=(0, 1, 0),   # Used a fixed (r,g,b) instead
					figure=fig
					)
and my 3d points data is ,
pointcloud = np.fromfile(str(lidar_data), dtype=np.float32, count=-1).reshape([-1,4])
x = pointcloud[:, 0]  # x position of point
y = pointcloud[:, 1]  # y position of point
z = pointcloud[:, 2]  # z position of point
r = pointcloud[:, 3]  # reflectance value of point

'r' is not used at points3d method, only (x,y,z) values are used.
So, I think only (x,y,z) should be inserted to reset method because i don't use scalar value

**Comment by prabhuramachandran** [comment]
`col` is the "scalar" attribute that is being colored.  That should have the same shape as your points.

**Comment by Jinho-P** [comment]
> `col` is the "scalar" attribute that is being colored. That should have the same shape as your points.

I added col array to elements of reset method. but the same error was occured

Here is my full code.
```python
pointcloud = np.fromfile(str(lidar_data), dtype=np.float32, count=-1).reshape([-1,4])
print(pointcloud.shape)	

x = pointcloud[:, 0]  # x position of point
y = pointcloud[:, 1]  # y position of point
z = pointcloud[:, 2]  # z position of point
r = pointcloud[:, 3]  # reflectance value of point
d = np.sqrt(x**2 + y**2)  # Map Distance from sensor

vals='height'
if vals == "height":
	col = z
else:
	col = d

fig = mlab.figure(bgcolor=(0, 0, 0), size=(640*2, 500*2))
point = mlab.points3d(x, y, z,
					col,          # Values used for Color
					mode="point",
					colormap='spectral', # 'bone', 'copper', 'gnuplot'
					# color=(0, 1, 0),   # Used a fixed (r,g,b) instead
					figure=fig
					)

mlab_source_point = point.mlab_source

@mlab.animate(delay=100)
def anim():    
	for i in range(len(lidat_data_list)):		
		if (i != 0):
			lidar_data = lidat_data_list[i]
			pointcloud = np.fromfile(str(lidar_data), dtype=np.float32, count=-1).reshape([-1,4])
			print(pointcloud.shape)			
			x = pointcloud[:, 0]  # x position of point
			y = pointcloud[:, 1]  # y position of point
			z = pointcloud[:, 2]  # z position of point
			r = pointcloud[:, 3]  # reflectance value of point

			d = np.sqrt(x**2 + y**2)  # Map Distance from sensor

			vals='height'
			if vals == "height":
				col = z
			else:
				col = d
			
			mlab_source_point.reset(x=x, y=y, z=z, col=col)
		
		yield   

anim()
mlab.show()
```

But same error is occured and I tried to another way like that,

```ptrhon
# current
mlab_source_point.reset(x=x, y=y, z=z, col=col)

# another way, full reset
mlab_source_point.reset(x=x, y=y, z=z, col=col, mode="point", colormap='spectral', figure=fig)
```

but, problem is not fixed. How can I do something?
And I am truly grateful for your continued reply. Thank you!

**Comment by prabhuramachandran** [comment]
`col` is not a keyword argument, it should be `mlab_source_point.reset(x=x, y=y, z=z, scalars=col)`

**Comment by Jinho-P** [comment]
what a.... I repeats stupid mistake TT...Thank you very much!!
