### ISSUE TITLE
mayavi2 errors of opening mv2 saved by python scripts

### ISSUE THREAD

**Issue by znculee** [enthought/mayavi#915]
How do I correctly save a `mv2` visualization file that can be successfully opened by mayavi2 directly?

Python script:
```python
import numpy as np
from mayavi import mlab

t = np.linspace(0, 4 * np.pi, 20)

x = np.sin(2 * t)
y = np.cos(t)
z = np.cos(2 * t)
s = 2 + np.sin(t)

points = mlab.points3d(
    x, y, z, s,
    colormap="copper",
    scale_factor=.25
)

colorbar_pos = mlab.colorbar(
    points,
    orientation='vertical'
)

engine = mlab.get_engine()
engine.save_visualization('points3d.mv2')

mlab.show()
```
Error generated by `mayavi2 points3d.mv2`:
```
File "path/miniconda3/envs/brain/lib/python3.7/site-packages/apptools/persistence/state_pickler.py", line 833, in _update_and_check_state ' name!'%(cls.__name__, metadata['class_name'])
apptools.persistence.state_pickler.StateSetterError: Instance (DecoratedScene) and state (MayaviScene) do not have the same class name!
```

Python script:
```python
import numpy as np
from mayavi import mlab

t = np.linspace(0, 4 * np.pi, 20)

x = np.sin(2 * t)
y = np.cos(t)
z = np.cos(2 * t)
s = 2 + np.sin(t)

points = mlab.points3d(
    x, y, z, s,
    colormap="copper",
    mode='point',
    scale_factor=.25
)

colorbar_pos = mlab.colorbar(
    points,
    orientation='vertical'
)

engine = mlab.get_engine()
engine.save_visualization('points3d.mv2')

mlab.show()
```
Error generated by `mayavi2 points3d.mv2`:
```
File "path/miniconda3/envs/brain/lib/python3.7/site-packages/apptools/persistence/state_pickler.py", line 912, in _do_dict self._do_object(obj[key], value)
KeyError: 'point_source'
```

**Comment by prabhuramachandran** [comment]
This is not implemented as it is generally hard to persist the data that is created by the user and passed in as numpy arrays.  I have wanted to implement saving a data file in the mv2 file but that is too much work and makes the resulting mayavi2 file rather bulky.  The .mv2 file will only work when you do everything from the UI, it cannot replace a Python script.  In principle this is possible to implement but even the mv2 format is really hard to maintain. So it is unlikely that this would be too useful.  Instead, I find that reproducible Python scripts are usually much more convenient and long lived as you can always edit and update them (and they are also readable).
