### ISSUE TITLE
mayavi compilation fails with vtk 9.0.0

### ISSUE THREAD

**Issue by patquem** [enthought/mayavi#922]
Hello,

I have tried to install mayavi this day according to the last versions of mayavi (4.7.1) and vtk (9.0.0) and my python crashed during the mayavi (pip) installation with the following message (see below)

I have first downgraded mayavi (from 4.7.1 to 4.6.2) -> compilation failed
then, vtk (from 9.0.0 to **8.1.2**) -> **compilation succeed** !! and mayavi works :)
I guess something is wrong with the latest version of vtk (?).

_Some words about my env : 
python-3.6.6.amd64 - pyQt5 (v5.9.2) - traits (v6.0.0*) - Windows7- MS Visual C++ 14.0
*once compiled, mayavi returns error message during 'traits' import if compiled with traits <v6.0.0_

> Failed to build mayavi
Installing collected packages: mayavi
  Running setup.py install for mayavi ... error
    Complete output from command C:\Users\Patrick\AppData\Roaming\WPy-3662\python-3.6.6.amd64\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Patrick\\AppData\\Local\\Temp\\pip-install-ig_c20da\\mayavi\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Patrick\AppData\Local\Temp\pip-record-or3tkap8\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    ----------------------------------------------------------------------
    Building TVTK classes... vtkContextDevice2D: Ignoring method: Get/SetViewportRect
    default: [1, 32, 0, 0], range: None
    vtkContextDevice2D: Ignoring method: Get/SetViewportSize
    default: [-1, -1], range: None
    vtkEventDataForDevice: Ignoring method: Get/SetAction
    default: -1, range: None
    vtkEventDataForDevice: Ignoring method: Get/SetDevice
    default: -1, range: None
    vtkFXAAOptions: Ignoring method: Get/SetDebugOptionValue
    default: 0, range: None
    vtkIncrementalForceLayout: Ignoring method: Get/SetGravityPoint
    default: [200.0, 200.0], range: None
    vtkOpenGLBufferObject: Ignoring method: Get/SetType
    default: 0, range: None
    vtkOpenGLFXAAFilter: Ignoring method: Get/SetDebugOptionValue
    default: 0, range: None
    vtkRenderWidget: Ignoring method: Get/SetPosition
    default: [0, 0], range: None
    vtkRenderWidget: Ignoring method: Get/SetSize
    default: [300, 300], range: None
    vtkShader: Ignoring method: Get/SetType
    default: 3, range: None
    vtkVolumeTexture: Ignoring method: Get/SetPartitions
    default: [1, 1, 1], range: None
    vtkChartMatrix: Ignoring method: Get/SetGutter
    default: [15.0, 15.0], range: None
    vtkChartMatrix: Ignoring method: Get/SetSize
    default: [0, 0], range: None
    vtkContextArea: Ignoring method: Get/SetDrawAreaBounds
    default: [0.0, 0.0, 300.0, 300.0], range: None
    vtkContextArea: Ignoring method: Get/SetDrawAreaResizeBehavior
    default: 0, range: None
    vtkContextArea: Ignoring method: Get/SetFixedMargins
    default: [0, 0, 0, 0], range: None
    vtkContextArea: Ignoring method: Get/SetFixedRect
    default: [0, 0, 300, 300], range: None
    vtkContextArea: Ignoring method: Get/SetGeometry
    default: [0, 0, 300, 300], range: None
    vtkImplicitProjectOnPlaneDistance: Ignoring method: Get/SetNorm
    default: 2, range: None
    vtkOpenGLVertexBufferObject: Ignoring method: Get/SetCoordShiftAndScaleMethod
    default: 0, range: None
    vtkSimple3DCirclesStrategy: Ignoring method: Get/SetMarkedValue
    default: (invalid), range: None
    vtkArrayNorm: Ignoring method: Get/SetWindow
    default: [0, 9223372036854775807), range: None
    vtkChart: Ignoring method: Get/SetSize
    default: [0.0, 0.0, 0.0, 0.0], range: None
    vtkChartXYZ: Ignoring method: Get/SetAxisColor
    default: [0, 0, 0, 255], range: None
    Warning: We cannot determine the trait type of vtkHigherOrderHexahedron.Order
    Warning: We cannot determine the trait type of vtkHigherOrderQuadrilateral.Order
    ----------------------------------------
    Command "C:\Users\Patrick\AppData\Roaming\WPy-3662\python-3.6.6.amd64\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Patrick\\AppData\\Local\\Temp\\pip-install-ig_c20da\\mayavi\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Patrick\AppData\Local\Temp\pip-record-or3tkap8\install-record.txt --single-version-externally-managed --compile" failed with error code 3221225477 in C:\Users\Patrick\AppData\Local\Temp\pip-install-ig_c20da\mayavi\
>

**Comment by prabhuramachandran** [comment]
You need to get mayavi from git master, the pip version is not compatible with VTK 9.

**Comment by kitchoi** [comment]
Perhaps the build script for TVTK could check the VTK version and provide a more helpful error/warning message saying the particular VTK version is not supported?

I haven't checked if this is already done on master though.

**Comment by kitchoi** [comment]
Thank you @patquem for the report and @prabhuramachandran for the clarifications!

**Comment by patquem** [comment]
thanks guys for your answers.
I spend a couple of hours to install mayavi, searching where the problem could come from (google research, etc ...) and when visiting now the closed items I discover that a lot of people were faced to the same problem I was. (rhaaa !).
Is there a way to find this kind of informations (github research engine ?) because google research (as I did) doesn't seem to be able to report this ? (example : previous similar item "pip install mayavi fails to install" (closed 12 days ago) is not found by google)
