### ISSUE TITLE
Doesn't import mayavi on PyCharm

### ISSUE THREAD

**Issue by Idevian** [enthought/mayavi#932]
Hello!

I am having problems importing mayavi into my PyCharm project.

I use a macOS High Sierra 10.13.6 and PyCharm 2018.1.1 with the Anaconda distribution.

When I have to include a library, I usually go to Preferences->Project_interpreter, create a virtual environment, and include a library from the ones available.

When I try to install mayavi (already present in the Anaconda distribution with the latest version 4.7.1) it looks like everything goes smoothly, but it only installs the libraries associated to mayavi (Pygments, apptools, configobj, envisage, numpy, pyface, six, traits, traitsui, vtk) and not mayavi itself. As a result, I can't use it in my code.

I tried following the installation protocols suggested on the website (https://docs.enthought.com/mayavi/mayavi/installation.html#latest-stable-release), in particular doing
     $ conda create -n pyconda python=3.5 pyqt=4
     $ source activate pyconda
     $ conda install -c menpo mayavi
but the problem remains.

I hope I gave you sufficient information and I apologize if I am blundering something trivial.

Thank you in advance for your attention.

**Comment by Idevian** [comment]
I forgot to mention that the Python version is 3.6 (the one used in the conda virtual environment).

**Comment by rahulporuri** [comment]
@Idevian are there any logs on the commandline when mayavi is being installed? Can you tell us what version of vtk was installed in the environment?

**Comment by Idevian** [comment]
> @Idevian are there any logs on the commandline when mayavi is being installed? Can you tell us what version of vtk was installed in the environment?

Thank you for your reply. In the Event Log it just says:
       Packages installed successfully: Installed packages: 'mayavi'
The vtk version is 9.0.0.

**Comment by Idevian** [comment]
@rahulporuri as you said in https://github.com/enthought/mayavi/issues/939 I confirm that the issue seems to be the vtk 9 version. If I use vtk 8.1.2 the mayavi installation in PyCharm is successful. Thank you very much.

**Comment by rahulporuri** [comment]
in that case @Idevian , do you mind if i close this issue. i will add a reference to this issue in #939.

**Comment by Idevian** [comment]
@rahulporuri sure. Thank you very much.
