### ISSUE TITLE
MAINT: Release 4.7.2 / CIBUILDWHEEL?

### ISSUE THREAD

**Issue by larsoner** [enthought/mayavi#959]
> This is fixed in master, we need to cut a new release and make that available on PyPI.

_Originally posted by @prabhuramachandran in https://github.com/enthought/mayavi/issues/939#issuecomment-664545368_

@prabhuramachandran any way to help with this process? FWIW I have had great experiences using CIBUILDWHEEL to build wheels for macOS, Linux, and Windows for all 3.5+ platforms using Azure. If you can tick some boxes I can make a PR to set this up, including automated `PyPi` uploads when tags starting with `v` (e.g., `v4.7.2`) get pushed. Currently used for example in [vispy](https://github.com/vispy/vispy/blob/master/azure-pipelines.yml#L13) and [python-rtmixer](https://github.com/spatialaudio/python-rtmixer/blob/master/azure-pipelines.yml#L10).

For rtmixer the code is about 80 lines of YAML (would be a PR), plus [azure setup](https://github.com/spatialaudio/python-rtmixer/pull/16#issuecomment-524573893) and [PyPi token setup](https://github.com/spatialaudio/python-rtmixer/pull/16#issuecomment-526324693) (needs to be done by someone with org-level permissions).

**Comment by prabhuramachandran** [comment]
@larsoner -- thanks for bringing this up.  I want to cut a release but my semester just started a couple of weeks ago so have been busy.  I think I should be able to get things in order by this weekend and push a release.

As regards wheels, I am not sure wheels make sense as the wheel would be tied to a particular version of VTK and this is not advisable in my opinion.  Instead a source release should be fine and then depending on the user's requirements it will pick up the VTK version that is available on their system.

**Comment by larsoner** [comment]
Ahh yes you're right, that makes sense. In theory we might be able to build wheels for each VTK version (there aren't that many) but this is probably not worth the effort

**Comment by prabhuramachandran** [comment]
@larsoner, @rahulporuri  -- I will work on cutting a release later today.  Are there any outstanding issues that need to be addressed first?  I think just getting a VTK compatible release is more important now and other issues can be fixed later?

**Comment by larsoner** [comment]
I can't think of anything else that needs to be done

**Comment by prabhuramachandran** [comment]
OK 4.7.2 is now out on PyPI.  Will send out the announcements.  Thank you for all your help!

**Comment by mdickinson** [comment]
> In theory we might be able to build wheels for each VTK version (there aren't that many) but this is probably not worth the effort.

I was wondering about this (in a slightly different, but similar context: I have a package containing NumPy extensions, which therefore needs different builds for different versions of NumPy).  The building wheels part is fine, but what's the mechanism by which a `pip install mayavi` from a user selects the appropriate wheel for a particular VTK version?
